// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["./BaseVersionManager"],function(h){function f(){this.versions=[{version:"2.0beta",description:"The version for Developer Edition beta 2.0.",upgrader:function(a){return a},compatible:!0},{version:"2.0",description:"The version for Online 4.1.",upgrader:function(a){return a},compatible:!0},{version:"2.0.1",description:"The version for Developer Edition 2.0.",upgrader:function(a){var d=null,c=0,b=a.widgetOnScreen.widgets;if(b&&0<b.length)for(c=0;c<b.length;c++)d=b[c],"widgets/Viz/Widget"===
d.uri&&(d.uri="widgets/3DFx/Widget",d.name="3DFx");if((b=a.widgetPool.widgets)&&0<b.length)for(c=0;c<b.length;c++)d=b[c],"widgets/Viz/Widget"===d.uri&&(d.uri="widgets/3DFx/Widget",d.name="3DFx");return a},compatible:!0},{version:"2.1",description:"The version for Online 4.2.",upgrader:function(a){return a},compatible:!0},{version:"2.2",description:"The version for Online 4.3.",upgrader:function(a){return a},compatible:!0},{version:"2.3",description:"The version for Online 4.4.",upgrader:function(a){return a},
compatible:!0},{version:"2.4",description:"The version for Online 5.1.",upgrader:function(a){return a},compatible:!0},{version:"2.5",description:"The version for Online 5.2.",upgrader:function(a){return a},compatible:!0},{version:"2.6",description:"The version for Online 5.3.",upgrader:function(a){return a},compatible:!0},{version:"2.7",description:"The version for Online 5.4.",upgrader:function(a){(function(){function d(c){var b=0,e=0;if(a[c].widgets)for(b=0;b<a[c].widgets.length;b++)if("widgets/Environment/Widget"===
a[c].widgets[b].uri){a[c].widgets[b].uri="widgets/Daylight/Widget";break}if(a[c].groups)for(b=0;b<a[c].groups.length;b++){var g=a[c].groups[b];for(e=0;e<g.widgets.length;e++)if("widgets/Environment/Widget"===g.widgets[e].uri){g.widgets[e].uri="widgets/Daylight/Widget";break}}}d("widgetOnScreen");d("widgetPool")})();return a},compatible:!0},{version:"2.8",description:"The version for Online 6.1.",upgrader:function(a){return a},compatible:!0},{version:"2.9",description:"The version for Online 6.2.",
upgrader:function(a){return a},compatible:!0},{version:"2.10",description:"The version for Online 6.3.",upgrader:function(a){return a},compatible:!0},{version:"2.11",description:"The version for Online 6.4.",upgrader:function(a){return a},compatible:!0},{version:"2.12",description:"The version for Online 7.1",upgrader:function(a){return a},compatible:!0},{version:"2.13",description:"The version for Online 7.2",upgrader:function(a){return a},compatible:!0},{version:"2.14",description:"The version for Online 7.3",
upgrader:function(a){return a},compatible:!0},{version:"2.15",description:"The version for Online 7.4",upgrader:function(a){return a},compatible:!0},{version:"2.16",description:"The version for Online 8.1",upgrader:function(a){return a},compatible:!0},{version:"2.17",description:"The version for Online 8.2",upgrader:function(a){return a},compatible:!0},{version:"2.18",description:"The version for Online 8.3",upgrader:function(a){return a},compatible:!0},{version:"2.19",description:"The version for Online 8.4",
upgrader:function(a){return a},compatible:!0},{version:"2.20",description:"The version for Online 9.1",upgrader:function(a){return a},compatible:!0},{version:"2.21",description:"The version for Online 9.2",upgrader:function(a){return a},compatible:!0},{version:"2.22",description:"The version for Online 9.3",upgrader:function(a){return a},compatible:!0},{version:"2.23",description:"The version for Online 9.4",upgrader:function(a){return a},compatible:!0},{version:"2.24",description:"The version for Online 10.1",
upgrader:function(a){return a},compatible:!0},{version:"2.25",description:"The version for Online 10.2",upgrader:function(a){return a},compatible:!0},{version:"2.26",description:"The version for Online 10.3",upgrader:function(a){return a},compatible:!0},{version:"2.27",description:"The version for Online 2023.R01",upgrader:function(a){return a},compatible:!0},{version:"2.28",description:"The version for Online 2023.R02",upgrader:function(a){return a},compatible:!0},{version:"2.29",description:"The version for Online 2023.R03",
upgrader:function(a){return a},compatible:!0}];this.isCompatible=function(a,d){a=this.getVersionIndex(a);d=this.getVersionIndex(d);for(a+=1;a<=d;a++)if(!1===this.versions[a].compatible)return!1;return!0}}f.prototype=new h;return f.prototype.constructor=f});