// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"jimu/layoutManagers/BaseLayoutManager":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dijit/_WidgetBase dojo/Deferred dojo/promise/all ../utils ../WidgetPlaceholder ../OnScreenWidgetIcon".split(" "),function(B,d,k,n,w,u,q,m,r,x){var y=null;var A=B([w],{constructor:function(){this.widgetPlaceholders=[];this.onScreenWidgetIcons=[];this.invisibleWidgetIds=[]},name:"BaseLayoutManager",mapId:"map",sceneView:null,layoutId:"jimu-layout-manager",postCreate:function(){this.containerNode=
this.domNode;this.layoutId=jimuConfig.layoutId},resize:function(){},isSupportEdit:function(){return!1},getMapDiv:function(){},setSceneView:function(c){this.sceneView=c},onEnter:function(c,f){var g=new u;this.appConfig=c;this.mapId=f;g.resolve();return g},onLeave:function(){},onThemeLoad:function(){},loadAndLayout:function(c){},openWidget:function(c){},onLayoutChange:function(c){},onWidgetChange:function(c,f){},onGroupChange:function(c,f){},onWidgetPoolChange:function(c,f){this.reloadControllerWidget(c,
f.controllerId)},onOnScreenOrderChange:function(c,f){k.forEach(f,d.hitch(this,function(g){g.uri?k.some(this.onScreenWidgetIcons,d.hitch(this,function(p){if(p.configId===g.id)return n.setStyle(p.domNode,m.getPositionStyle({top:g.position.top,left:g.position.left,right:g.position.right,bottom:g.position.bottom,width:40,height:40})),p.moveTo(g.position),!0})):k.some(this.widgetPlaceholders,d.hitch(this,function(p){if(p.index===g.placeholderIndex){var v=m.getPositionStyle({top:g.position.top,left:g.position.left,
right:g.position.right,bottom:g.position.bottom,width:40,height:40});n.setStyle(p.domNode,v);return!0}}))}))},onActionTriggered:function(c){},onLayoutDefinitionChange:function(c,f){},onOnScreenGroupsChange:function(c,f){},destroyOnScreenWidgetsAndGroups:function(c){},loadOnScreenWidgets:function(c){var f=[];k.forEach(c.widgetOnScreen.widgets,function(g){!1===g.visible?this.invisibleWidgetIds.push(g.id):f.push(this.loadOnScreenWidget(g,c))},this);return q(f)},loadOnScreenWidget:function(c,f){var g=
new u;if("config"===f.mode&&!c.uri)return f=this._createOnScreenWidgetPlaceHolder(c),g.resolve(f),g;if(!c.uri)return g.resolve(null),g;c.inPanel||c.closeable?(f=this._createOnScreenWidgetIcon(c),g.resolve(f)):this.widgetManager.loadWidget(c).then(d.hitch(this,function(p){try{p.setPosition(p.position),this.widgetManager.openWidget(p)}catch(v){console.log(console.error("fail to startup widget "+p.name+". "+v.stack))}p.configId=c.id;g.resolve(p)}),function(p){g.reject(p)});return g},onOnScreenWidgetChange:function(c,
f){f=c.getConfigElementById(f.id);f.isController?this.reloadControllerWidget(c,f.id):(k.forEach(this.widgetPlaceholders,function(g){g.configId===f.id&&(g.destroy(),this.loadOnScreenWidget(f,c))},this),this.removeDestroyed(this.widgetPlaceholders),this._updatePlaceholder(c),k.forEach(this.onScreenWidgetIcons,function(g){if(g.configId===f.id){var p=g.state;g.destroy();this.loadOnScreenWidget(f,c).then(function(v){if(f.uri&&"opened"===p)v.onClick()})}},this),this.removeDestroyed(this.onScreenWidgetIcons),
k.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(g){g.configId===f.id&&(g.destroy(),!1===f.visible?0>this.invisibleWidgetIds.indexOf(f.id)&&this.invisibleWidgetIds.push(f.id):this.loadOnScreenWidget(f,c))},this),k.forEach(this.invisibleWidgetIds,function(g){g===f.id&&!1!==f.visible&&(this.loadOnScreenWidget(f,c),g=this.invisibleWidgetIds.indexOf(f.id),this.invisibleWidgetIds.splice(g,1))},this),f.isOnScreen||k.forEach(this.widgetManager.getControllerWidgets(),function(g){g.widgetIsControlled(f.id)&&
this.reloadControllerWidget(c,g.id)},this))},destroyOnScreenWidgetIcons:function(){k.forEach(this.onScreenWidgetIcons,function(c){c.destroy()},this);this.onScreenWidgetIcons=[]},destroyOnScreenOffPanelWidgets:function(){k.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(c){c.isController?this._destroyControllerWidget(c):this.widgetManager.destroyWidget(c)},this)},destroyWidgetPlaceholders:function(){k.forEach(this.widgetPlaceholders,function(c){c.destroy()},this);this.widgetPlaceholders=
[]},removeDestroyed:function(c){var f=[];k.forEach(c,function(g){g._destroyed&&f.push(g)});k.forEach(f,function(g){g=c.indexOf(g);c.splice(g,1)})},_createOnScreenWidgetPlaceHolder:function(c){var f="map"===c.position.relativeTo?this.mapId:this.layoutId;var g=d.clone(c);g.position.width=40;g.position.height=40;var p=m.getPositionStyle(g.position);c=new r({index:g.placeholderIndex,configId:c.id});n.setStyle(c.domNode,p);n.place(c.domNode,f);this.widgetPlaceholders.push(c);return c},_createOnScreenWidgetIcon:function(c){var f=
new x({panelManager:this.panelManager,widgetManager:this.widgetManager,widgetConfig:c,configId:c.id,sceneView:this.sceneView});"map"===c.position.relativeTo?n.place(f.domNode,this.mapId):n.place(f.domNode,this.layoutId);n.setStyle(f.domNode,m.getPositionStyle({top:c.position.top,left:c.position.left,right:c.position.right,bottom:c.position.bottom,width:40,height:40}));f.startup();!this.openAtStartWidget&&c.openAtStart&&(f.switchToOpen(),this.openAtStartWidget=c.name);this.onScreenWidgetIcons.push(f);
return f},reloadControllerWidget:function(c,f){var g=this.widgetManager.getWidgetById(f);if(g){var p=g.getOpenedIds(),v=g.windowState;this._destroyControllerWidget(g);this._loadControllerWidget(c,f,p,v)}else this._loadControllerWidget(c,f)},_destroyControllerWidget:function(c){k.forEach(c.getAllConfigs(),function(f){if(f.widgets)this.panelManager.destroyPanel(f.id+"_panel"),k.forEach(f.widgets,function(p){this.panelManager.destroyPanel(p.id+"_panel")},this);else{var g=this.widgetManager.getWidgetById(f.id);
g&&(f.inPanel?this.panelManager.destroyPanel(g.getPanel()):this.widgetManager.destroyWidget(g))}},this);this.widgetManager.destroyWidget(c)},_loadControllerWidget:function(c,f,g,p){f=c.getConfigElementById(f);!1!==f.visible&&this.loadOnScreenWidget(f,c).then(d.hitch(this,function(v){p&&this.widgetManager.changeWindowStateTo(v,p);g&&v.setOpenedIds(g)}))},_updatePlaceholder:function(c){k.forEach(this.widgetPlaceholders,function(f){f.setIndex(c.getConfigElementById(f.configId).placeholderIndex)},this)}});
A.getInstance=function(){null===y&&(y=new A);return y};return A})},"jimu/WidgetPlaceholder":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/html","dijit/_WidgetBase","./utils"],function(B,d,k,n,w){return B(n,{"class":"jimu-widget-placeholder",position:null,postCreate:function(){this.inherited(arguments);this.indexNode=k.create("div",{"class":"inner",innerHTML:this.index},this.domNode);k.setAttr(this.domNode,"title",window.jimuNls.widgetPlaceholderTooltip)},moveTo:function(u){this.position=
d.clone(u);var q={left:"auto",right:"auto",bottom:"auto",top:"auto",width:"auto",height:"auto"};q=d.mixin(q,w.getPositionStyle(u));delete q.width;delete q.height;k.setStyle(this.domNode,q)},setIndex:function(u){this.index=u;this.indexNode.innerHTML=u}})})},"jimu/OnScreenWidgetIcon":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dijit/_WidgetBase ./utils".split(" "),function(B,d,k,n,w,u,q){return B(u,{"class":"jimu-widget-onscreen-icon",postCreate:function(){this.inherited(arguments);
this.iconNode=n.create("img",{src:this.widgetConfig.icon},this.domNode);window.isRTL&&this.widgetConfig.mirrorIconForRTL&&n.addClass(this.iconNode,"jimu-flipx");n.setAttr(this.domNode,"title",this.widgetConfig.label);this.own(w(this.domNode,"click",d.hitch(this,function(){this.onClick()})));this.position=d.clone(this.widgetConfig.position);"map"===this.widgetConfig.position.relativeTo&&this.own(w(this.sceneView,"resize",d.hitch(this,function(){var m=d.clone(this.position);delete m.width;delete m.height;
this.panel&&this.panel.setPosition(m)})));this.state="closed"},startup:function(){this.inherited(arguments)},onClick:function(){"closed"===this.state?this.switchToOpen():this.switchToClose()},moveTo:function(m){var r={left:"auto",right:"auto",bottom:"auto",top:"auto",width:"auto",height:"auto"};r=d.mixin(r,q.getPositionStyle(m));delete r.width;delete r.height;n.setStyle(this.domNode,r);this.position=d.clone(m);this.widgetConfig&&this.widgetConfig.panel&&(this.widgetConfig.panel.position=d.clone(m),
this.widgetConfig.position=d.clone(m));this.panel&&this.panel.setPosition(d.clone(m));this.widget&&this.widget.setPosition(this.getOffPanelWidgetPosition(this.widget))},destroy:function(){this.panel?this.panelManager.destroyPanel(this.panel):this.widget&&this.widgetManager.destroyWidget(this.widget);this.inherited(arguments)},switchToOpen:function(){this.state="opened";this.panelManager.closeAllPanelsInGroup(this.widgetConfig.gid);k.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(m){m.closeable&&
this.widgetManager.closeWidget(m)},this);n.addClass(this.domNode,"jimu-state-selected");this._showLoading();!1===this.widgetConfig.inPanel?this.widgetManager.loadWidget(this.widgetConfig).then(d.hitch(this,function(m){this.widget=m;m.setPosition(this.getOffPanelWidgetPosition(m));this.widgetManager.openWidget(m);this.own(w(m,"close",d.hitch(this,function(){this.switchToClose()})));this._hideLoading()})):this.panelManager.showPanel(d.clone(this.widgetConfig)).then(d.hitch(this,function(m){this.panel=
m;this.own(w(m,"close",d.hitch(this,function(){this.switchToClose()})));this._hideLoading()}))},switchToClose:function(){this.state="closed";n.removeClass(this.domNode,"jimu-state-selected");!1===this.widgetConfig.inPanel?this.widgetManager.closeWidget(this.widget):this.panelManager.closePanel(this.panel)},getOffPanelWidgetPosition:function(m){var r={relativeTo:m.position.relativeTo},x=n.getMarginBox(this.domNode);m=this.widgetManager.getWidgetMarginBox(m);var y=n.getMarginBox("map"===r.relativeTo?
this.sceneView.map.id:jimuConfig.layoutId),A=x.t+x.h+1;A+m.h>y.h?r.bottom=y.h-x.t+1:r.top=A;window.isRTL?r.right=0>x.l+x.w-m.w?0:x.l+x.w-m.w:x.l+m.w>y.w?r.right=0:r.left=x.l;return r},_showLoading:function(){n.setAttr(this.iconNode,"src",require.toUrl("jimu")+"/images/loading_circle.gif")},_hideLoading:function(){n.setAttr(this.iconNode,"src",this.widgetConfig.icon)}})})}}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/topic dojo/on dojo/dom-construct dojo/dom-geometry dojo/Deferred dojo/debounce require ../WidgetManager ../PanelManager ../utils ../dijit/LoadingShelter ./BaseLayoutManager".split(" "),function(B,d,k,n,w,u,q,m,r,x,y,A,c,f,g,p){var v=null;var E=B([p],{isEditing:!1,maxStackId:0,dashboardWidgets:[],dashboardPanels:{},currentMode:0,_createLayoutDeferred:null,_isDestroying:!1,nls:null,_addWidgetTipTemplate:'\x3cdiv class\x3d"tip"\x3e\x3cdiv class\x3d"idx"\x3e${groupIndex}\x3c/div\x3e\x3cdiv class\x3d"label"\x3e${this.nls.addWidgetTip}\x3c/div\x3e\x3c/div\x3e',
name:"GridLayoutManager",constructor:function(a,b){this.widgetManager=A.getInstance();this.panelManager=c.getInstance();this.widgetPlaceholders=[];this.preloadWidgetIcons=[];this.preloadGroupPanels=[];this.invisibleWidgetIds=[];this.own(u(window,"resize",d.hitch(this,this.resize)));this.id=b;this._createLayoutDeferred=null},postMixInProperties:function(){this.inherited(arguments);this.nls={};d.mixin(this.nls,window.jimuNls.gridLayout,window.jimuNls.common);this._addWidgetTipTemplate=this._addWidgetTipTemplate.replace("${this.nls.addWidgetTip}",
this.nls.addWidgetTip)},isSupportEdit:function(){return!0},postCreate:function(){this.containerNode=this.domNode},layout:null,sceneView:null,mapContainer:null,mapId:"map",hlDiv:null,animTime:500,resize:function(){this._resizeLayout();k.forEach(this.widgetManager.getAllWidgets(),function(a){!1===a.inPanel&&a.resize()},this)},setSceneView:function(a){this.inherited(arguments);this.panelManager.setSceneView(a)},_resizeLayout:function(){if(!this.isEditing&&this.layout){var a=$(this.layoutContainer);var b=
a.width();a=a.height();this.layout.updateSize(b,a)}else this.isEditing&&this.editingLayout&&(a=$(this.editLayoutDiv),b=a.width(),a=a.height(),this.editingLayout.updateSize(b,a))},loadAndLayout:function(a){this.appConfig=a;var b=new g;b.placeAt(this.layoutId);b.startup();this._createLayoutDeferred&&!this._createLayoutDeferred.isResolved()?a=this._createLayoutDeferred:(a=new r,a.resolve());a.then(d.hitch(this,this._loadOnScreenGroups)).then(d.hitch(this,this._reArrangeWidgetsLayout,!0)).then(d.hitch(this,
function(){b&&(b.destroy(),b=null);console.timeEnd("Load widgetOnScreen");w.publish("preloadWidgetsLoaded")}),d.hitch(this,function(){b&&(b.destroy(),b=null);console.timeEnd("Load widgetOnScreen");w.publish("preloadWidgetsLoaded")}))},createMapDiv:function(a){n.byId(a)?this.mapDiv=n.byId(a):this.mapDiv=n.create("div",{id:a,style:d.mixin({position:"absolute",backgroundColor:"#EEEEEE",overflow:"hidden",minWidth:"1px",minHeight:"1px"},f.getPositionStyle(this.appConfig.map.position))},this.layoutId)},
getMapDiv:function(){return this.mapDiv},onThemeLoad:function(){this._resizeLayout()},_enableEditing:function(){this.isEditing||(this._createEditingLayout(),$(this.layoutContainer).addClass("hidden"),$(this.editContainer).removeClass("hidden"),$(this.modifyLayoutBtn).addClass("hidden"),this.isEditing=!0,this._resizeLayout())},_disableEditing:function(){$(this.layoutContainer).removeClass("hidden");$(this.editContainer).addClass("hidden");$(this.modifyLayoutBtn).removeClass("hidden");this.isEditing=
!1;this._resizeLayout()},_resetLayoutDefinition:function(){this._disableEditing();this._createLayout(!1,!1);w.publish("editLayoutCancelled")},_saveLayoutDefinition:function(){var a=d.clone(this.editingLayout.toConfig()),b=d.clone(this.appConfig.layoutDefinition);this._simplifyLayoutDefinition(a.content[0]);this._disableEditing();var e=this.editingLayout.root.contentItems[0].getItemsByType("stack"),h=[];k.forEach(e,function(l){!k.some(l.contentItems,d.hitch(this,function(t){if(t.isComponent&&"map"===
t.config.componentName)return!0}))&&/^dd_group_\d+$/.test(l.config.id)&&h.push(l.config.id)});b.layout.config.content=a.content;w.publish("layoutDefinitionChanged",{layoutDefinition:b,groupIds:h})},_simplifyLayoutDefinition:function(a){if("component"!==a.type)if("stack"===a.type){var b;a.activeItemIndex=0;k.some(a.content,d.hitch(this,function(e){if("component"===e.type&&"map"===e.componentName)return b=e,!0}));b?(a.id="map",a.content=[b]):a.content=[]}else k.forEach(a.content,d.hitch(this,function(e){this._simplifyLayoutDefinition(e)}))},
_bindLayoutEvents:function(){this.editingLayout.on("initialised",d.hitch(this,function(){this.editingLayout.createDragSource($(this.dragCreateBtn),{title:" ",type:"component",reorderEnabled:!1,componentName:"widget panel"});var a=this.editingLayout.root.contentItems[0].getItemsByType("stack"),b=[];k.forEach(a,function(e){/^dd_group_\d+$/.test(e.config.id)&&(e=parseInt(e.config.id.split("_")[2],10),b.push(e))});0<b.length?(b=b.sort(function(e,h){return e>h}),this.maxStackId=b[b.length-1]):this.maxStackId=
0;this._arrangeWidgetsInEditingLayout()}));this.editingLayout.on("stackCreated",d.hitch(this,function(a){this.maxStackId++;a.config.id||(a.config.id="dd_group_"+this.maxStackId)}))},_arrangeWidgetsInEditingLayout:function(){k.forEach(this.appConfig.widgetOnScreen.groups,d.hitch(this,function(a){a=this.appConfig.getConfigElementById(a.id);var b=this.editingLayout.root.contentItems[0].getItemsById(a.id),e;b&&0<b.length&&"stack"===b[0].type&&(e=b[0]);e&&k.forEach(a.widgets,d.hitch(this,function(h,l){var t=
{id:h.id,type:"component",title:h.label,reorderEnabled:!1,componentName:"widget panel",componentState:{label:h.label}};e.contentItems.length>l?(l=e.contentItems[l],l.config.id=h.id,l.setTitle(h.label)):e.addChild(t)}))}))},_createActionBar:function(a){if(!this.actionBar){this.actionBar=q.create("div",{"class":"layout-actionbar"},a);this.dragCreateBtn=q.create("div",{"class":"jimu-btn jimu-float-leading jimu-leading-margin2 add-btn",innerHTML:this.nls.dragToAdd},this.actionBar);a=q.create("div",{"class":"jimu-btn-vacation jimu-float-trailing jimu-trailing-margin2 cancel-btn",
innerHTML:this.nls.cancel},this.actionBar);var b=q.create("div",{"class":"jimu-btn jimu-float-trailing save-btn",innerHTML:this.nls.ok},this.actionBar);this.own(u(a,"click",d.hitch(this,this._resetLayoutDefinition)));this.own(u(b,"click",d.hitch(this,this._saveLayoutDefinition)))}},_destroyActionBar:function(){q.destroy(this.actionBar);this.actionBar=null},_createLayout:function(a,b,e){return this._createLayoutDeferred&&!this._createLayoutDeferred.isResolved()?this._createLayoutDeferred.then(d.hitch(this,
function(){return this._doCreateLayout(a,b,e)})):this._doCreateLayout(a,b,e)},_doCreateLayout:function(a,b,e){var h=new r;this._createLayoutDeferred=new r;if(this.isEditing)return this._createEditingLayout();e?this._createNormalLayout().then(d.hitch(this,function(){this._createLayoutDeferred.resolve();h.resolve()})):a?this._createNormalLayout().then(d.hitch(this,this._loadOnScreenGroups)).then(d.hitch(this,this._reArrangeWidgetsLayout,b)).then(d.hitch(this,function(){this._createLayoutDeferred.resolve();
h.resolve()})):this._createNormalLayout().then(d.hitch(this,this._reArrangeWidgetsLayout,b)).then(d.hitch(this,function(){this._createLayoutDeferred.resolve();h.resolve()}));return h},_detachWidgets:function(a){if("stack"===a.type){for(;1<a.contentItems.length;)a.removeChild(a.contentItems[0],!0);var b=a.contentItems[0];a.addChild({type:"component",componentName:"widget panel",title:" ",isClosable:!1});a.removeChild(b,!0)}else k.forEach(a.contentItems,d.hitch(this,function(e){this._detachWidgets(e)}))},
_setupWidgets:function(a,b){a.isClosable=b;"component"!==a.type&&("stack"===a.type?0===a.content.length&&(a.content=[{type:"component",componentName:"widget panel",title:" ",isClosable:b}]):k.forEach(a.content,d.hitch(this,function(e){this._setupWidgets(e)})))},_onActivePanelChanged:function(a){var b;if(!this._isDestroying&&"widget panel"===a.componentName&&a.config.id){(b=this.dashboardPanels[a.config.id])&&b.domNode?(0===a.container.getElement().find(".jimu-panel").length&&(a.container.getElement().html(b.domNode),
a.container.on("resize",x(d.hitch(this,function(){0<a.container.width&&0<a.container.height&&b&&b.resize()}),200))),b.resize(),this.panelManager.openPanel(b)):this._loadDashboardWidget(a.config.id).then(d.hitch(this,function(l){l&&(a.container.getElement().html(l.domNode),a.container.on("resize",x(d.hitch(this,function(){0<a.container.width&&0<a.container.height&&l.resize()}),200)),l.resize(),this.panelManager.openPanel(l))}));var e=a.parent.config.id,h;k.some(this.appConfig.widgetOnScreen.groups,
d.hitch(this,function(l){if(l.id===e)return h=l.widgets,!0}));k.forEach(h,d.hitch(this,function(l){l.id!==a.config.id&&(b=this.dashboardPanels[l.id])&&this.panelManager.closePanel(b)}))}},_createNormalLayout:function(){var a=new r;this._isDestroying=!1;this.layoutContainer||(this.layoutContainer=q.create("div",{"class":"config"===this.appConfig.mode?"jimu-dnd-layout config":"jimu-dnd-layout"},this.layoutId),"config"===this.appConfig.mode&&(this.modifyLayoutBtn=q.create("div",{"class":"jimu-dnd-layout modify-btn",
innerHTML:'\x3cdiv class\x3d"jimu-ellipsis"\x3e\x3cspan class\x3d"feature-action icon-edit"\x3e\x3c/span\x3e'+this.nls.modifyLayout+"\x3c/div\x3e"},this.layoutId),this.own(u(this.modifyLayoutBtn,"click",d.hitch(this,function(){w.publish("editLayout")})))));k.some(this.appConfig.widgetOnScreen.widgets,function(h){if("themes/DashboardTheme/widgets/Header/Widget"===h.uri)return h.visible?n.setStyle(this.layoutContainer,"top","80px"):(this._removeHighLight(h.id),n.setStyle(this.layoutContainer,"top",
0)),!0},this);var b=this.layout,e=d.clone(this.appConfig.layoutDefinition.layout.config);"config"===this.appConfig.mode&&(e.settings.reorderEnabled=!1,e.settings.resizeEnabled=!1,e.settings.enableHeaderDragging=!1,e.dimensions={borderWidth:5,dragProxyWidth:0,dragProxyHeight:0});this._setupWidgets(e.content[0],!1);y(["libs/goldenlayout/goldenlayout"],d.hitch(this,function(h){"config"===this.appConfig.mode&&$(this.modifyLayoutBtn).removeClass("hidden");this.layout=new h(e,this.layoutContainer);this.layout.registerComponent("widget panel",
d.hitch(this,function(l,t){var z=l.parent.parent.config.id,C;t.widgetId||(t=this._addWidgetTipTemplate,k.some(this.appConfig.widgetOnScreen.groups,function(D){if(D.id===z)return"config"===this.appConfig.mode&&0===D.widgets.length&&(C=D.placeholderIndex),!0},this),C&&(t=t.replace("${groupIndex}",C),l.getElement().html(t)))}));this.layout.registerComponent("map",d.hitch(this,function(l){l.setTitle("");this.mapContainer=l.getElement();$("#"+this.mapId).appendTo(this.mapContainer);b&&(this._isDestroying=
!0,this._detachWidgets(b.root.contentItems[0]),b.destroy(),this._isDestroying=!1)}));this.layout.on("initialised",d.hitch(this,function(){a.resolve()}));this.layout.on("stackCreated",d.hitch(this,function(l){l.on("activeContentItemChanged",d.hitch(this,function(t){this._onActivePanelChanged(t)}))}));this.layout.init()}));return a},_createEditingLayout:function(){this.editContainer||(this.editContainer=q.create("div",{"class":"jimu-edit-layout hidden"},this.layoutId),this._createActionBar(this.editContainer),
this.editLayoutDiv=q.create("div",{"class":"layout-container"},this.editContainer));var a=this.editingLayout,b=d.clone(this.appConfig.layoutDefinition.layout.config);b.settings.enableHeaderDropping=!1;b.settings.reorderEnabled=!1;b.dimensions={borderWidth:5,dragProxyWidth:0,dragProxyHeight:0};this._setupWidgets(b.content[0],!0);y(["libs/goldenlayout/goldenlayout"],d.hitch(this,function(e){this.editingLayout=new e(b,this.editLayoutDiv);this.editingLayout.registerComponent("widget panel",d.hitch(this,
function(h){h.getElement().html("")}));this.editingLayout.registerComponent("map",d.hitch(this,function(h){h.setTitle("");h.getElement().html('\x3cdiv class\x3d"maptip"\x3e'+this.nls.sceneArea+"\x3c/div\x3e");a&&a.destroy()}));this._bindLayoutEvents();this.editingLayout.init()}))},_destroyLayout:function(){$("#"+this.mapId).appendTo("#"+this.layoutId);this.layout&&(this.layout.destroy(),this.layout=null,q.destroy(this.layoutContainer),this.layoutContainer=null,this.modifyLayoutBtn&&(q.destroy(this.modifyLayoutBtn),
this.modifyLayoutBtn=null));this.editingLayout&&(this._destroyActionBar(),this.editingLayout.destroy(),this.editingLayout=null,q.destroy(this.editContainer),this.editContainer=null)},destroyOnScreenWidgetsAndGroups:function(){this._destroyOnScreenWidgets();this._destroyOnScreenGroups()},onActionTriggered:function(a){if("editLayout"===a.action)this._enableEditing();else if("highLight"===a.action){var b=this._findContentItemById(a.elementId);b?b.isStack?$(b.element).addClass("highlight"):b.isComponent&&
$(b.tab.element).addClass("highlight"):(k.forEach(this.widgetPlaceholders,function(e){e.configId===a.elementId&&this._highLight(e)},this),k.forEach(this.onScreenWidgetIcons,function(e){e.configId===a.elementId&&this._highLight(e)},this),k.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(e){e.configId===a.elementId&&this._highLight(e)},this))}else"removeHighLight"===a.action?this._removeHighLight(a.elementId):"showLoading"===a.action?(n.setStyle(jimuConfig.loadingId,"display","block"),
n.setStyle(jimuConfig.mainPageId,"display","none")):"showApp"===a.action&&(n.setStyle(jimuConfig.loadingId,"display","none"),n.setStyle(jimuConfig.mainPageId,"display","block"))},_findContentItemById:function(a,b){return(a=this.layout.root.contentItems[0].getItemsById(a))&&0<a.length&&(!b||b===a[0].type)?a[0]:null},_highLight:function(a){if(a.domNode){this.hlDiv&&this._removeHighLight(a);var b=m.getMarginBox(a.domNode);this.hlDiv=q.create("div",{style:{position:"absolute",left:b.l+"px",top:b.t+"px",
width:b.w+"px",height:b.h+"px"},"class":"icon-highlight"},a.domNode,"before")}},_removeHighLight:function(a){/^dd_group_\d+$/.test(a)?(a=this._findContentItemById(a,"stack"))&&$(a.element).removeClass("highlight"):/^widgets_\w+_\d+$/.test(a)&&(a=this._findContentItemById(a,"component"))&&$(a.tab.element).removeClass("highlight");this.hlDiv&&(q.destroy(this.hlDiv),this.hlDiv=null)},onEnter:function(a,b){this.appConfig=a;this.isEditing=!1;this.createMapDiv(b);return this._createLayout(!1,!1,!0)},onLeave:function(){this._destroyLayout();
this.sceneView=null},onWidgetChange:function(a,b){this.appConfig=a;"themes/DashboardTheme/widgets/Header/Widget"===b.uri&&(b.visible?n.setStyle(this.layoutContainer,"top","80px"):(this._removeHighLight(b.id),n.setStyle(this.layoutContainer,"top",0)),this._resizeLayout());b=a.getConfigElementById(b.id);var e=this.dashboardPanels[b.id];if(e)e.reloadWidget(b),(a=this.layout.root.contentItems[0].getItemsByType("component"))&&0<a.length&&a.forEach(function(h){h.config.id===b.id&&h.config.title!==b.label&&
(h.config.title=b.label,h.setTitle(b.label))});else this.onOnScreenWidgetChange(a,b)},onOnScreenGroupsChange:function(a){this.appConfig=a;this._createLayout(!0,!1)},onGroupChange:function(a,b){this.appConfig=a;b=a.getConfigElementById(b.id);b.isOnScreen?this._createLayout(!0,!1):(k.forEach(this.widgetManager.getControllerWidgets(),function(e){e.isControlled(b.id)&&this.reloadControllerWidget(a,e.id)},this),k.forEach(this.panelManager.panels,function(e){e.config.id===b.id&&e.updateConfig(b)},this))},
_reArrangeWidgetsLayout:function(a){a&&this._destroyOnScreenWidgets();a&&this.loadOnScreenWidgets(this.appConfig);this._reArrangeWidgetsInDesktopLayout()},_reArrangeWidgetsInDesktopLayout:function(){k.forEach(this.appConfig.widgetOnScreen.groups,d.hitch(this,function(a){a=this.appConfig.getConfigElementById(a.id);var b=this._findContentItemById(a.id,"stack");b&&k.forEach(a.widgets,d.hitch(this,function(e,h){var l={id:e.id,type:"component",title:e.label,componentName:"widget panel",componentState:{widgetId:e.id}};
b.contentItems.length>h?(h=b.contentItems[h],h.config.id=e.id,h.config.title=e.label,h.config.componentState={widgetId:e.id},h.setTitle(e.label),b.setActiveContentItem(h)):b.addChild(l)}))}))},_loadDashboardWidget:function(a){var b=new r,e=this.dashboardPanels[a];if(e&&e.domNode)return b.resolve(this.dashboardPanels[a]),b;var h;k.some(this.appConfig.widgetOnScreen.groups,d.hitch(this,function(t){return k.some(t.widgets,d.hitch(this,function(z){if(z.id===a)return h=z,!0}))}));if(!h)return b.resolve(null),
b;var l=this.appConfig.layoutDefinition.layout.panel;y([l.uri],d.hitch(this,function(t){var z={config:h,uri:l.uri,sceneView:this.sceneView,widgetManager:this.widgetManager,panelManager:this.panelManager,id:a+"_panel",position:{}};d.mixin(z,h.options);try{var C=new t(z);this.dashboardPanels[a]=C;b.resolve(C);console.log("panel ["+z.id+"] created.")}catch(D){console.log("create panel error: "+D+", panelId: "+z.id),b.reject(D)}}));return b},onLayoutDefinitionChange:function(a){this.appConfig=a;this._createLayout(!1,
!1)},onLayoutChange:function(a){this.isEditing||(this.appConfig=a,this._createLayout(!1,!1).then(d.hitch(this,function(){k.forEach(this.widgetPlaceholders,function(b){b.moveTo(a.getConfigElementById(b.configId).position)},this);k.forEach(this.onScreenWidgetIcons,function(b){b.moveTo(a.getConfigElementById(b.configId).position)},this);k.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(b){if(!b.closeable){var e=a.getConfigElementById(b.id).position;b.setPosition(e)}},this)})))},openWidget:function(a){var b;
(a=this._findContentItemById(a,"component"))&&(b=a.parent)&&b.isStack&&b.setActiveContentItem(a)},_loadOnScreenGroups:function(){var a=this.appConfig.widgetOnScreen.groups,b=[],e=new r;k.forEach(a,d.hitch(this,function(h){h=this.appConfig.getConfigElementById(h.id);k.forEach(h.widgets,function(l){b.push(l.id)})}));k.forEach(this.dashboardWidgets,d.hitch(this,function(h){if(0>b.indexOf(h)){var l=this.dashboardPanels[h];l&&(this.panelManager.closePanel(l),l.destroy());this.dashboardPanels[h]=null}}));
this.dashboardWidgets=b;e.resolve();return e},_destroyOnScreenWidgets:function(){this.destroyOnScreenOffPanelWidgets();this.destroyWidgetPlaceholders();this.destroyOnScreenWidgetIcons()},_destroyOnScreenGroups:function(){k.forEach(this.dashboardWidgets,d.hitch(this,function(a){if(a=this.dashboardPanels[a])this.panelManager.closePanel(a),a.destroy(),a=null}));this.panelManager.destroyAllPanels();this.dashboardWidgets=[];this.dashboardPanels={}}});E.getInstance=function(a,b){null===v&&(v=new E(a,b),
window._layoutManager=v);return v};return E});