//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/declare esri/core/lang esri/views/3d/webgl-engine/lib/Util esri/core/libs/gl-matrix-2/vec3f64 esri/core/libs/gl-matrix-2/vec2f64 esri/core/libs/gl-matrix-2/vec3 esri/core/libs/gl-matrix-2/vec2 ../../webgl-engine-extensions/VertexBufferLayout ../../webgl-engine-extensions/GLVertexArrayObject ../../webgl-engine-extensions/GLXBO ../../webgl-engine-extensions/GLVerTexture ../../support/fx3dUtils ../../support/fx3dUnits ../Effect ./JetTrailMaterial ../../webgl-engine-extensions/constraints".split(" "),
function(u,B,H,v,Q,I,J,n,y,K,z,t,L,h,w,M,N,O){v=I.vec3f64;n=n.vec3;var P=J.vec2f64;y=y.vec2;var p=v.create(),q=v.create(),C=v.create(),r=0,D=O.VertexAttrConstants;return H([M],{declaredClass:"esri.views.3d.effects.JetTrail.JetTrailEffect",effectName:"JetTrail",constructor:function(b){u.hitch(this,b);this.orderId=2;this._needsAllLoaded=!0},_initRenderingInfo:function(){this.renderingInfo.radius=20;this.renderingInfo.pulseRadius=1E5;this.renderingInfo.colors=[h.rgbNames.cadetblue,h.rgbNames.yellowgreen,
h.rgbNames.lightpink,h.rgbNames.orangered,h.rgbNames.green,h.rgbNames.indianred];this._renderingInfoDirty=this._colorBarDirty=this.renderingInfo.showEndPoints=!0;this._curveType=1;this._shapeDirty=this._vacDirty=!0;this._needsRenderPulse=!1;this.inherited(arguments)},_doRenderingInfoChange:function(b){this.inherited(arguments);for(var a in b)b.hasOwnProperty(a)&&this.renderingInfo.hasOwnProperty(a)&&(h.endsWith(a.toLowerCase(),"info")?h.isInforAttrChanged(this.renderingInfo[a],b[a])&&(this._renderingInfoDirty=
!0):h.endsWith(a.toLowerCase(),"colors")?b[a]instanceof Array&&(this.renderingInfo[a]=b[a],this._colorBarDirty=!0,this._renderingInfoDirty=!0):"radius"===a.toLowerCase()||"pulseRadius"===a.toLowerCase()||"transparency"===a.toLowerCase()?(this._clampScope(b,a),"radius"==a&&this._radiusUnit?this.renderingInfo[a]=w.toMeters(this._radiusUnit,b[a],this._view.viewingMode):"pulseRadius"==a&&this._pulseRadiusUnit?this.renderingInfo[a]=w.toMeters(this._pulseRadiusUnit,b[a],this._view.viewingMode):this.renderingInfo[a]=
b[a]):typeof b[a]==typeof this.renderingInfo[a]&&(this.renderingInfo[a]=b[a]))},initEffect:function(b){this.inherited(arguments);this._effectConfig&&u.isArray(this._effectConfig.renderingInfo)&&(this._radiusUnit=null,this._pulseRadiusUnit=null,B.forEach(this._effectConfig.renderingInfo,function(a){"radius"===a.name.toLowerCase()?(this._radiusUnit=a.unit,this.renderingInfo.radius=w.toMeters(this._radiusUnit,this.renderingInfo.radius,this._view.viewingMode)):"pulseRadius"===a.name.toLowerCase()&&(this._pulseRadiusUnit=
a.unit,this.renderingInfo.pulseRadius=w.toMeters(this._pulseRadiusUnit,this.renderingInfo.pulseRadius,this._view.viewingMode))}.bind(this)))},destroy:function(){this._resetXBOs();this._dispose("_aroundVerticesTexture");this._dispose("_headVAO");this._dispose("_tailVAO");this._dispose("_pulseVAO")},_resetXBOs:function(){this._dispose("_headVBO");this._dispose("_tailVBO");this._dispose("_tailIBO");this._dispose("_pulseVBO");this._dispose("_pulseIBO");this._needsRenderPulse=!1},_initVertexLayout:function(){this._vertexAttrConstants=
[D.AUXPOS1,D.AUXPOS2];this._vertexBufferLayout=new K(this._vertexAttrConstants,[2,3],[5126,5126])},_initRenderContext:function(){return this.inherited(arguments),this._vacDirty&&(this._initVertexLayout(),this._resetXBOs(),this._vacDirty=!1,this._headVAO&&(this._headVAO.unbind(),this._headVAO._initialized=!1),this._tailVAO&&(this._tailVAO.unbind(),this._tailVAO._initialized=!1),this._pulseVAO&&(this._pulseVAO.unbind(),this._pulseVAO._initialized=!1)),this._headVBO||(this._headVBO=new t(this._gl,!0,
this._vertexBufferLayout)),this._tailVBO||(this._tailVBO=new t(this._gl,!0,this._vertexBufferLayout)),this._tailIBO||(this._tailIBO=new t(this._gl,!1)),this._pulseVBO||(this._pulseVBO=new t(this._gl,!0,this._vertexBufferLayout)),this._pulseIBO||(this._pulseIBO=new t(this._gl,!1)),this._vaoExt&&(this._headVAO=new z(this._gl,this._vaoExt),this._tailVAO=new z(this._gl,this._vaoExt),this._pulseVAO=new z(this._gl,this._vaoExt)),this._localBindsCallback||(this._localBindsCallback=this._localBinds.bind(this)),
1===this._curveType?this._buildAroundPathGeometries():0===this._curveType&&this._buildAlongPathGeometries()},_buildAroundPathGeometries:function(){if(!this._needsAllLoaded)return console.warn("All features should be loaded first."),!1;var b=this._allGraphics();if(0<b.length){var a,c,e,d,f,m,g,k=[],l=[],E=[],A=0,x=[];return this._pathIdNum=0,B.forEach(b,function(F,G){if(null!==F.geometry)for(f=F.geometry.paths,m=0;m<f.length;m++)if(!(2>f[m].length)){a=f[m][0];null==a[2]&&(a[2]=1.11);c=f[m][f[m].length-
1];null==c[2]&&(c[2]=1.11);n.set(p,a[0],a[1],a[2]);"global"===this._view.viewingMode?h.wgs84ToSphericalEngineCoords(p,0,p,0):"local"===this._view.viewingMode&&h.wgs84ToWebMerc(p,0,p,0);n.set(q,c[0],c[1],c[2]);"global"===this._view.viewingMode?h.wgs84ToSphericalEngineCoords(q,0,q,0):"local"===this._view.viewingMode&&h.wgs84ToWebMerc(q,0,q,0);n.subtract(C,p,q);d=n.length(C);"global"===this._view.viewingMode?e=1E3>=d?32:1E4>=d?24:5E5>=d?18:1E6>=d?40:Math.floor(1E-5*d):"local"===this._view.viewingMode&&
(e=1E3>=d?48:1E4>=d?42:1E5>=d?32:1E6>=d?24:2E6>=d?36:Math.floor(6E-6*d));e=2*e-1;e=Math.max(5,Math.floor(.26*e));k.push(this._pathIdNum,G,1,e-1,e-1);x.push([a[0],a[1],a[2]]);x.push([c[0],c[1],c[2]]);for(g=0;g<e;g++)l.push(this._pathIdNum,G,4,g,e-1),g<e-1&&E.push(A+g,A+g+1);this._pathIdNum++;A+=e}}.bind(this)),this._headVBO.addData(!1,new Float32Array(k)),this._tailVBO.addData(!1,new Float32Array(l)),this._tailIBO.addData(!1,new Uint32Array(E)),this._headVAO&&(this._headVAO._initialized=!1),this._tailVAO&&
(this._tailVAO._initialized=!1),this._resetAddGeometries(),this._initAroundVerticesTexture(x)&&this._initPulseGeometries(x)}return!1},_buildAlongPathGeometries:function(){return!1},_initAroundVerticesTexture:function(b){if(2*this._pathIdNum!==b.length)return console.warn("The quantity of paths and points is invalid."),!1;var a=this._gl.getParameter(3379),c=2*this._pathIdNum,e=h.nextHighestPowerOfTwo(c);e>a&&(e=a,console.warn("Too many graphics, and some data will be discarded."));c=Math.ceil(c/e);
c=h.nextHighestPowerOfTwo(c);c>a&&(c=a,console.warn("Too many graphics, and some data will be discarded."));var d=new Float32Array(e*c*4);for(a=0;a<this._pathIdNum;a++){var f=8*a;d[0+f]=a;d[1+f]=b[2*a][0];d[2+f]=b[2*a][1];d[3+f]=b[2*a][2];d[4+f]=a;d[5+f]=b[2*a+1][0];d[6+f]=b[2*a+1][1];d[7+f]=b[2*a+1][2]}return this._aroundVerticesTexture||(this._aroundVerticesTexture=new L(this._gl),this._aroundVerticesTextureSize=P.create()),this._aroundVerticesTexture.setData(e,c,d),y.set(this._aroundVerticesTextureSize,
e,c),!0},_initPulseGeometries:function(b){if(2*this._pathIdNum!==b.length)return console.warn("The quantity of paths and points is invalid."),!1;if(0<b.length){var a,c,e=this._vertexBufferLayout.getStride(),d=new Float32Array(41*e*this._pathIdNum),f=new Uint32Array(120*this._pathIdNum),m=2*Math.PI;for(a=0;a<this._pathIdNum;a++){var g=41*a*e;var k=b[2*a+1];d[g+2]=k[0];d[g+3]=k[1];d[g+4]=k[2];d[g+0]=-1;d[g+1]=a;g+=e;for(c=0;40>c;c++){var l=g+e*c;d[l+2]=k[0];d[l+3]=k[1];d[l+4]=k[2];d[l+0]=c/40*m;d[l+
1]=a}k=41*a;g=3*k;for(c=0;39>c;c++)l=g+3*c,f[l+0]=0+k,f[l+1]=c+1+k,f[l+2]=c+2+k;l=g+117;f[l+0]=0+k;f[l+1]=40+k;f[l+2]=1+k}return this._pulseVBO.addData(!1,d),this._pulseIBO.addData(!1,f),this._pulseVAO&&(this._pulseVAO._initialized=!1),!0}return!1},_initColourMap:function(){this._colourMapTexture||(this._colourMapTexture=this._gl.createTexture());var b=new Image;b.src=h.spriteImg;var a=this;return b.onload=function(){var c=a._gl.getParameter(a._gl.TEXTURE_BINDING_2D);a._gl.bindTexture(3553,a._colourMapTexture);
a._gl.pixelStorei(37440,!0);a._gl.texParameteri(3553,10240,9728);a._gl.texParameteri(3553,10241,9728);a._gl.texParameteri(3553,10242,33071);a._gl.texParameteri(3553,10243,33071);a._gl.texImage2D(3553,0,6408,6408,5121,b);a._gl.generateMipmap(3553);a._gl.bindTexture(3553,c)},0===this._gl.getError()},_loadShaders:function(){return this.inherited(arguments),this._material||(this._material=new N({pushState:this._pushState.bind(this),restoreState:this._restoreState.bind(this),gl:this._gl,viewingMode:this._view.viewingMode,
shaderSnippets:this._shaderSnippets})),this._material.loadShaders()},_initColorBar:function(){if(!this._colorBarDirty)return!0;this._colorBarTexture||(this._colorBarTexture=this._gl.createTexture());var b=this._gl.getParameter(32873);this._gl.bindTexture(3553,this._colorBarTexture);this._gl.pixelStorei(37440,!0);this._gl.texParameteri(3553,10240,9728);this._gl.texParameteri(3553,10241,9728);this._gl.texParameteri(3553,10242,33071);this._gl.texParameteri(3553,10243,33071);var a=h.createColorBarTexture(32,
1,this.renderingInfo.colors);return this._gl.texImage2D(3553,0,6408,6408,5121,a),this._gl.generateMipmap(3553),this._gl.bindTexture(3553,b),0===this._gl.getError()},_localBinds:function(b,a,c){b.bind(c);this._vertexBufferLayout.enableVertexAttribArrays(this._gl,c);a&&a.bind()},_bindBuffer:function(b,a,c,e){b?(b._initialized||b.initialize(this._localBindsCallback,[a,c,e]),b.bind()):this._localBinds(a,c,e)},_unBindBuffer:function(b,a,c,e){b?b.unbind():(a.unbind(),this._vertexBufferLayout.disableVertexAttribArrays(this._gl,
e),c&&c.unbind())},render:function(b,a){this.inherited(arguments);this._layer.visible&&this.ready&&this._bindPramsReady()&&(this._hasSentReady||(this._layer.emit("fx3d-ready"),this._hasSentReady=!0),this._material.bind(u.mixin({},{li:this._aroundVerticesTexture,im:this._aroundVerticesTextureSize,ll:this._colourMapTexture,es:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],el:this._vizFieldVerTextureSize,mo:this.renderingInfo.animationInterval,oe:this.renderingInfo.radius,ei:this.renderingInfo.transparency,
io:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,ss:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,pe:this._colorBarTexture},b),a),this._material.blend(!0,
a),this._bindBuffer(this._tailVAO,this._tailVBO,this._tailIBO,this._material._program),this._gl.drawElements(1,this._tailIBO.getNum(),5125,0),this._unBindBuffer(this._tailVAO,this._tailVBO,this._tailIBO,this._material._program),this._material.blend(!1,a),this._bindBuffer(this._headVAO,this._headVBO,null,this._material._program),this._gl.drawArrays(0,0,this._headVBO.getNum()),this._unBindBuffer(this._headVAO,this._headVBO,null,this._material._program),this._needsRenderPulse||(r=this.time/this.renderingInfo.animationInterval,
.8<r-Math.floor(r)&&(this._needsRenderPulse=!0)),this._needsRenderPulse&&(this.renderingInfo.showEndPoints&&(this._material.bindPulse(u.mixin({},{es:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],el:this._vizFieldVerTextureSize,mo:this.renderingInfo.animationInterval,ls:[this._scopes.pulseRadius[0]>this._layerView._minDelta?this._layerView._minDelta||10:this._scopes.pulseRadius[0],this.renderingInfo.pulseRadius>this._layerView._minDelta?this._layerView._minDelta||10:this.renderingInfo.pulseRadius],
ei:this.renderingInfo.transparency,io:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,ss:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,pe:this._colorBarTexture},
b),a),this._material.blend(!0,a),this._bindBuffer(this._pulseVAO,this._pulseVBO,this._pulseIBO,this._material._pulseProgram),this._gl.drawElements(4,this._pulseIBO.getNum(),5125,0),this._unBindBuffer(this._pulseVAO,this._pulseVBO,this._pulseIBO,this._material._pulseProgram)),r=this.time/this.renderingInfo.animationInterval,.79<r-Math.floor(r)&&(this._needsRenderPulse=!1)),this._material.release(a))}})});