//>>built
!function(w){"object"==typeof module&&"object"==typeof module.exports?(w=w(),void 0!==w&&(module.exports=w)):"function"==typeof define&&define.amd&&define([],w)}(function(){function w(a,c,b){b=b||2;var f=c&&c.length,e=f?c[0]*b:a.length,h=K(a,0,e,b,!0),k=[];if(!h||h.next===h.prev)return k;var l;if(f){var g=b,q;var d=[];f=0;for(q=c.length;f<q;f++){var p=c[f]*g;var r=f<q-1?c[f+1]*g:a.length;p=K(a,p,r,g,!1);p===p.next&&(p.steiner=!0);r=d;var t=r.push,m=p,n=p;do(m.x<n.x||m.x===n.x&&m.y<n.y)&&(n=m),m=m.next;
while(m!==p);t.call(r,n)}d.sort(P);for(f=0;f<d.length;f++){g=d[f];c=h;if(c=Q(g,c))g=L(c,g),x(c,c.next),x(g,g.next);h=x(h,h.next)}}if(a.length>80*b){var y=l=a[0];var z=f=a[1];for(g=b;g<e;g+=b)d=a[g],c=a[g+1],d<y&&(y=d),c<z&&(z=c),d>l&&(l=d),c>f&&(f=c);l=Math.max(l-y,f-z);l=0!==l?1/l:0}return B(h,k,b,y,z,l),k}function K(a,c,b,f,e){if(e===0<H(a,c,b,f))for(e=c;e<b;e+=f)var h=M(e,a[e],a[e+1],h);else for(e=b-f;e>=c;e-=f)h=M(e,a[e],a[e+1],h);return h&&E(h,h.next)&&(C(h),h=h.next),h}function x(a,c){if(!a)return a;
c||(c=a);var b=a;do if(a=!1,b.steiner||!E(b,b.next)&&0!==u(b.prev,b,b.next))b=b.next;else{if(C(b),b=c=b.prev,b===b.next)break;a=!0}while(a||b!==c);return c}function B(a,c,b,f,e,h,k){if(a){!k&&h&&N(a,f,e,h);for(var l,g,q=a;a.prev!==a.next;){l=a.prev;g=a.next;if(h)a:{var d=a;var p=f,r=e,t=h,m=d.prev,n=d.next;if(0<=u(m,d,n))d=!1;else{var y=m.x>d.x?m.x>n.x?m.x:n.x:d.x>n.x?d.x:n.x,z=m.y>d.y?m.y>n.y?m.y:n.y:d.y>n.y?d.y:n.y,v=I(m.x<d.x?m.x<n.x?m.x:n.x:d.x<n.x?d.x:n.x,m.y<d.y?m.y<n.y?m.y:n.y:d.y<n.y?d.y:
n.y,p,r,t);p=I(y,z,p,r,t);r=d.prevZ;for(t=d.nextZ;r&&r.z>=v&&t&&t.z<=p;){if(r!==d.prev&&r!==d.next&&A(m.x,m.y,d.x,d.y,n.x,n.y,r.x,r.y)&&0<=u(r.prev,r,r.next)||(r=r.prevZ,t!==d.prev&&t!==d.next&&A(m.x,m.y,d.x,d.y,n.x,n.y,t.x,t.y)&&0<=u(t.prev,t,t.next))){d=!1;break a}t=t.nextZ}for(;r&&r.z>=v;){if(r!==d.prev&&r!==d.next&&A(m.x,m.y,d.x,d.y,n.x,n.y,r.x,r.y)&&0<=u(r.prev,r,r.next)){d=!1;break a}r=r.prevZ}for(;t&&t.z<=p;){if(t!==d.prev&&t!==d.next&&A(m.x,m.y,d.x,d.y,n.x,n.y,t.x,t.y)&&0<=u(t.prev,t,t.next)){d=
!1;break a}t=t.nextZ}d=!0}}else a:if(d=a,m=d.prev,n=d,v=d.next,0<=u(m,n,v))d=!1;else{for(p=d.next.next;p!==d.prev;){if(A(m.x,m.y,n.x,n.y,v.x,v.y,p.x,p.y)&&0<=u(p.prev,p,p.next)){d=!1;break a}p=p.next}d=!0}if(d)c.push(l.i/b),c.push(a.i/b),c.push(g.i/b),C(a),q=a=g.next;else if(a=g,a===q){if(k)if(1===k){a=x(a);k=c;l=b;g=a;do q=g.prev,d=g.next.next,!E(q,d)&&O(q,g,g.next,d)&&D(q,d)&&D(d,q)&&(k.push(q.i/l),k.push(g.i/l),k.push(d.i/l),C(g),C(g.next),g=a=d),g=g.next;while(g!==a);a=x(g);B(a,c,b,f,e,h,2)}else{if(2===
k)a:{k=a;do{for(l=k.next.next;l!==k.prev;){if(g=k.i!==l.i){d=d=d=d=void 0;g=k;q=l;if(d=g.next.i!==q.i&&g.prev.i!==q.i){b:{d=g;do{if(d.i!==g.i&&d.next.i!==g.i&&d.i!==q.i&&d.next.i!==q.i&&O(d,d.next,g,q)){d=!0;break b}d=d.next}while(d!==g);d=!1}d=!d}if(d){if(d=D(g,q)&&D(q,g)){d=g;m=!1;n=(g.x+q.x)/2;v=(g.y+q.y)/2;do d.y>v!=d.next.y>v&&d.next.y!==d.y&&n<(d.next.x-d.x)*(v-d.y)/(d.next.y-d.y)+d.x&&(m=!m),d=d.next;while(d!==g);d=m}d=d&&(u(g.prev,g,q.prev)||u(g,q.prev,q))||E(g,q)&&0<u(g.prev,g,g.next)&&0<
u(q.prev,q,q.next)}g=d}if(g){a=L(k,l);k=x(k,k.next);a=x(a,a.next);B(k,c,b,f,e,h);B(a,c,b,f,e,h);break a}l=l.next}k=k.next}while(k!==a)}}else B(x(a),c,b,f,e,h,1);break}}}}function P(a,c){return a.x-c.x}function Q(a,c){var b=c,f=a.x,e=a.y,h=-(1/0);do{if(e<=b.y&&e>=b.next.y&&b.next.y!==b.y){var k=b.x+(e-b.y)*(b.next.x-b.x)/(b.next.y-b.y);if(k<=f&&k>h){if(h=k,k===f){if(e===b.y)return b;if(e===b.next.y)return b.next}var l=b.x<b.next.x?b:b.next}}b=b.next}while(b!==c);if(!l)return null;if(f===h)return l;
k=l;var g=l.x,q=l.y,d=1/0;b=l;do{if(f>=b.x&&b.x>=g&&f!==b.x&&A(e<q?f:h,e,g,q,e<q?h:f,e,b.x,b.y)){c=Math.abs(e-b.y)/(f-b.x);var p;if((p=D(b,a))&&!(p=c<d)&&(p=c===d)&&!(p=b.x>l.x)&&(p=b.x===l.x)){p=l;var r=b;p=0>u(p.prev,p,r.prev)&&0>u(r.next,p,p.next)}p&&(l=b,d=c)}b=b.next}while(b!==k);return l}function N(a,c,b,f){var e=a;do{if(null===e.z&&(e.z=I(e.x,e.y,c,b,f)),e.prev.next!==e||e.next.prev!==e)return e.prev.next=e,e.next.prev=e,N(a,c,b,f);e.prevZ=e.prev;e=e.nextZ=e.next}while(e!==a);e.prevZ.nextZ=
null;e.prevZ=null;a=e;var h,k,l,g=1;do{c=a;f=a=null;for(e=0;c;){e++;b=c;for(h=l=0;h<g&&(l++,b=b.nextZ,b);h++);for(h=g;0<l||0<h&&b;)0!==l&&(0===h||!b||c.z<=b.z)?(k=c,c=c.nextZ,l--):(k=b,b=b.nextZ,h--),f?f.nextZ=k:a=k,k.prevZ=f,f=k;c=b}f.nextZ=null;g*=2}while(1<e)}function I(a,c,b,f,e){return a=32767*(a-b)*e,c=32767*(c-f)*e,a=16711935&(a|a<<8),a=252645135&(a|a<<4),a=858993459&(a|a<<2),a=1431655765&(a|a<<1),c=16711935&(c|c<<8),c=252645135&(c|c<<4),c=858993459&(c|c<<2),c=1431655765&(c|c<<1),a|c<<1}function A(a,
c,b,f,e,h,k,l){return 0<=(e-k)*(c-l)-(a-k)*(h-l)&&0<=(a-k)*(f-l)-(b-k)*(c-l)&&0<=(b-k)*(h-l)-(e-k)*(f-l)}function u(a,c,b){return(c.y-a.y)*(b.x-c.x)-(c.x-a.x)*(b.y-c.y)}function E(a,c){return a.x===c.x&&a.y===c.y}function O(a,c,b,f){var e=F(u(a,c,b)),h=F(u(a,c,f)),k=F(u(b,f,a)),l=F(u(b,f,c));return e!==h&&k!==l||!(0!==e||!G(a,b,c))||!(0!==h||!G(a,f,c))||!(0!==k||!G(b,a,f))||!(0!==l||!G(b,c,f))}function G(a,c,b){return c.x<=Math.max(a.x,b.x)&&c.x>=Math.min(a.x,b.x)&&c.y<=Math.max(a.y,b.y)&&c.y>=Math.min(a.y,
b.y)}function F(a){return 0<a?1:0>a?-1:0}function D(a,c){return 0>u(a.prev,a,a.next)?0<=u(a,c,a.next)&&0<=u(a,a.prev,c):0>u(a,c,a.prev)||0>u(a,a.next,c)}function L(a,c){var b=new J(a.i,a.x,a.y),f=new J(c.i,c.x,c.y),e=a.next,h=c.prev;return a.next=c,c.prev=a,b.next=e,e.prev=b,f.next=b,b.prev=f,h.next=f,f.prev=h,f}function M(a,c,b,f){a=new J(a,c,b);return f?(a.next=f.next,a.prev=f,f.next.prev=a,f.next=a):(a.prev=a,a.next=a),a}function C(a){a.next.prev=a.prev;a.prev.next=a.next;a.prevZ&&(a.prevZ.nextZ=
a.nextZ);a.nextZ&&(a.nextZ.prevZ=a.prevZ)}function J(a,c,b){this.i=a;this.x=c;this.y=b;this.nextZ=this.prevZ=this.z=this.next=this.prev=null;this.steiner=!1}function H(a,c,b,f){for(var e=0,h=b-f;c<b;c+=f)e+=(a[h]-a[c])*(a[c+1]+a[h+1]),h=c;return e}return w.deviation=function(a,c,b,f){var e=c&&c.length,h=Math.abs(H(a,0,e?c[0]*b:a.length,b));if(e){e=0;for(var k=c.length;e<k;e++)h-=Math.abs(H(a,c[e]*b,e<k-1?c[e+1]*b:a.length,b))}for(e=c=0;e<f.length;e+=3){k=f[e]*b;var l=f[e+1]*b,g=f[e+2]*b;c+=Math.abs((a[k]-
a[g])*(a[l+1]-a[k+1])-(a[k]-a[l])*(a[g+1]-a[k+1]))}return 0===h&&0===c?0:Math.abs((c-h)/h)},w.flatten=function(a){for(var c=a[0][0].length,b={vertices:[],holes:[],dimensions:c},f=0,e=0;e<a.length;e++){for(var h=0;h<a[e].length;h++)for(var k=0;k<c;k++)b.vertices.push(a[e][h][k]);0<e&&(f+=a[e-1].length,b.holes.push(f))}return b},w});