//>>built
define("dojo/_base/declare esri/geometry/support/centroid ../../webgl-engine-extensions/earcut esri/core/libs/gl-matrix-2/vec3f64 esri/core/libs/gl-matrix-2/vec3 ../../support/geometryUtils esri/geometry/support/triangulationUtils esri/geometry/projection esri/geometry/projection/projectBuffer".split(" "),function(K,L,M,N,n,O,P,S,Q){var u=N.vec3f64;n=n.vec3;var D=u.create(),E=u.create(),H=u.create(),I=u.create(),J=u.create(),z=u.create(),A=u.create(),B=u.create(),F=Math.cos(Math.PI/180*5);return K(null,
{constructor:function(b,e,f){var a=b.geometry.rings;this.center=L.polygonCentroid({rings:a,hasZ:!1});b=P.pathsToTriangulationInfo(a,b.geometry.hasZ);(this._geometryData={vertexData:b.position,polygons:b.polygons,outlines:b.outlines},0<=e)&&0<=f&&(this.index=e,this.stride=f)},createBuffers:function(b,e){var f,a,y=this._geometryData.polygons,v=[],p=this._geometryData.vertexData;if(!p)return v;var r=p.length/3,h=new Float64Array(p.length);Q.projectBuffer(p,b,0,h,e,0,r);e=new Float64Array(h);for(var k=
0;k<y.length;++k){b=y[k];var d=b.count;var l=b.index;var q=new Float64Array(p.buffer,3*l*p.BYTES_PER_ELEMENT,3*d);if(f=b.holeIndices.map(function(R){return R-l}),a=M(q,f,3),!(1>a.length)){var m={polygonIndex:k},t=new Float64Array(e.buffer,3*l*e.BYTES_PER_ELEMENT,3*d),c=this._computeNormalAndDistance(t);m.dist=c.distance;if(d=O.getOrigin(h,r,l,d)){m.origin=d;c=[];var C=[];d=b.count;for(var w=0;w<d;w++){var g=w*this.stride;c[0+g]=q[3*w];c[1+g]=q[1+3*w];c[2+g]=1;c[3+g]=this.index;c[4+g]=0;c[5+g]=this.center[0];
c[6+g]=this.center[1];g=(w+d)*this.stride;c[0+g]=q[3*w];c[1+g]=q[1+3*w];c[2+g]=100.11;c[3+g]=this.index;c[4+g]=1;c[5+g]=this.center[0];c[6+g]=this.center[1]}for(var G=w=g=0;G<b.pathLengths.length;G++){w=b.pathLengths[G];for(var x=0;x<w;x++)x!==w-1?C.push(x+1+g,x+g,x+1+d+g,x+1+d+g,x+g,x+d+g):C.push(0+g,x+g,0+d+g,0+d+g,x+g,x+d+g);g+=w}this._subdivision2(q,t,a,d,c,C);m.indexNums=C.length;m.vertexNum=c.length/this.stride;m.vertices=new Float32Array(c);m.indices=new Uint32Array(C);v.push(m)}}}return v},
_computeNormalAndDistance:function(b){var e=0,f=3,a=6;n.set(D,b[e++],b[e++],b[e++]);n.set(E,b[f++],b[f++],b[f++]);n.set(H,b[a++],b[a++],b[a++]);n.subtract(I,D,E);n.subtract(J,H,E);b=u.create();n.cross(b,I,J);n.normalize(b,b);e=6378137-Math.abs(n.dot(b,D));f=n.normalize(D,D);f=n.dot(b,f);return{normal:b,distance:Math.abs(e/f)}},_subdivision:function(b,e,f,a,y,v){for(var p,r,h,k,d,l,q,m=e.length/3,t=0,c=0,C=0;C<m;C++)k=e[t++],d=e[t++],l=e[t++],p=3*k,r=3*d,h=3*l,q=(b[p]+b[r]+b[h])/3,p=(b[p+1]+b[r+1]+
b[h+1])/3,y.push(q,p,100.11,this.index,1,this.center[0],this.center[1]),v.push(k+f,d+f,a+c),v.push(d+f,l+f,a+c),v.push(l+f,k+f,a+c),c++},_doSubdivision:function(b,e,f){if(0<b.length)for(var a,y,v,p,r,h,k,d,l,q,m=-1,t=e.length/this.stride;null!=(a=b.pop());)if(n.copy(z,a.pt0),n.copy(A,a.pt1),n.copy(B,a.pt2),a.n0||(a.n0=u.create(),n.normalize(a.n0,z)),a.n1||(a.n1=u.create(),n.normalize(a.n1,A)),a.n2||(a.n2=u.create(),n.normalize(a.n2,B)),y=n.dot(a.n0,a.n1),v=n.dot(a.n1,a.n2),p=n.dot(a.n0,a.n2),y<F||
v<F||p<F){if(r=Math.min(y,v,p),!isNaN(r)&&null!=r)if(r==y){m++;h=.5*(z[0]+A[0]);k=.5*(z[1]+A[1]);d=.5*(z[2]+A[2]);l=.5*(a.pt00[0]+a.pt11[0]);q=.5*(a.pt00[1]+a.pt11[1]);var c=u.fromValues(h,k,d);n.normalize(c,c);b.push({pt0:a.pt0,pt1:[h,k,d],pt2:a.pt2,pt00:a.pt00,pt11:[l,q],pt22:a.pt22,index0:a.index0,index1:t+m,index2:a.index2,n0:a.n0,n1:c,n2:a.n2});b.push({pt0:[h,k,d],pt1:a.pt1,pt2:a.pt2,pt00:[l,q],pt11:a.pt11,pt22:a.pt22,index0:t+m,index1:a.index1,index2:a.index2,n0:c,n1:a.n1,n2:a.n2});e.push(l,
q,100.11,this.index,1,this.center[0],this.center[1]);f.push(t+m,a.index0,a.index1)}else r==v?(m++,h=.5*(A[0]+B[0]),k=.5*(A[1]+B[1]),d=.5*(A[2]+B[2]),l=.5*(a.pt22[0]+a.pt11[0]),q=.5*(a.pt22[1]+a.pt11[1]),c=u.fromValues(h,k,d),n.normalize(c,c),b.push({pt0:a.pt0,pt1:a.pt1,pt2:[h,k,d],pt00:a.pt00,pt11:a.pt11,pt22:[l,q],index0:a.index0,index1:a.index1,index2:t+m,n0:a.n0,n1:a.n1,n2:c}),b.push({pt0:a.pt0,pt1:[h,k,d],pt2:a.pt2,pt00:a.pt00,pt11:[l,q],pt22:a.pt22,index0:a.index0,index1:t+m,index2:a.index2,
n0:a.n0,n1:c,n2:a.n2}),e.push(l,q,100.11,this.index,1,this.center[0],this.center[1]),f.push(t+m,a.index1,a.index2)):r==p&&(m++,h=.5*(z[0]+B[0]),k=.5*(z[1]+B[1]),d=.5*(z[2]+B[2]),l=.5*(a.pt22[0]+a.pt00[0]),q=.5*(a.pt22[1]+a.pt00[1]),c=u.fromValues(h,k,d),n.normalize(c,c),b.push({pt0:a.pt0,pt1:a.pt1,pt2:[h,k,d],pt00:a.pt00,pt11:a.pt11,pt22:[l,q],index0:a.index0,index1:a.index1,index2:t+m,n0:a.n0,n1:a.n1,n2:c}),b.push({pt0:[h,k,d],pt1:a.pt1,pt2:a.pt2,pt00:[l,q],pt11:a.pt11,pt22:a.pt22,index0:t+m,index1:a.index1,
index2:a.index2,n0:c,n1:a.n1,n2:a.n2}),e.push(l,q,100.11,this.index,1,this.center[0],this.center[1]),f.push(t+m,a.index2,a.index0))}else f.push(a.index0,a.index1,a.index2)},_subdivision2:function(b,e,f,a,y,v){for(var p,r,h,k,d,l,q=f.length/3,m=0,t=0;t<q;t++)k=f[m++],d=f[m++],l=f[m++],p=3*k,r=3*d,h=3*l,this._doSubdivision([{pt0:[e[p],e[p+1],e[p+2]],pt1:[e[r],e[r+1],e[r+2]],pt2:[e[h],e[h+1],e[h+2]],pt00:[b[p],b[p+1]],pt11:[b[r],b[r+1]],pt22:[b[h],b[h+1]],index0:k+a,index1:d+a,index2:l+a}],y,v)},destroy:function(){this.isFulfilled()||
this.reject()}})});