//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/declare esri/core/lang esri/views/3d/webgl-engine/lib/Util ../../webgl-engine-extensions/VertexBufferLayout ../../webgl-engine-extensions/GLVertexArrayObject ../../webgl-engine-extensions/GLXBO ../../webgl-engine-extensions/GLVerTexture ../../support/fx3dUtils ../../support/fx3dUnits ../Effect ./AreaExtrudeMaterial ./AreaExtrudeGeometry ../../webgl-engine-extensions/constraints".split(" "),function(r,t,x,E,F,y,z,u,G,k,v,A,B,C,D){var h,q=D.VertexAttrConstants;
return x([A],{declaredClass:"esri.views.3d.effects.AreaExtrude.AreaExtrudeEffect",effectName:"AreaExtrude",constructor:function(a){this.orderId=2;this._polygonIndex=this._polygonIdNum=0;this._polygonNormals=[];this._vertexNums=this._indexNums=0;this._renderObjects={};this._maxDist=0;this._needsAllLoaded=!1},_initRenderingInfo:function(){this.renderingInfo.height=1E4;this.renderingInfo.topColors=[[128,100,253],[160,162,140],[255,100,128]];this._colorBarDirty=!0;this.renderingInfo.bottomColor=[0,255,
0];this._shapeDirty=this._vacDirty=this._renderingInfoDirty=!0;this.inherited(arguments)},_doRenderingInfoChange:function(a){this.inherited(arguments);for(var b in a)a.hasOwnProperty(b)&&this.renderingInfo.hasOwnProperty(b)&&(k.endsWith(b.toLowerCase(),"info")?k.isInforAttrChanged(this.renderingInfo[b],a[b])&&(this._renderingInfoDirty=!0):k.endsWith(b.toLowerCase(),"color")?a[b]instanceof Array&&3==a[b].length&&(this.renderingInfo[b]=[a[b][0]/255,a[b][1]/255,a[b][2]/255]):k.endsWith(b.toLowerCase(),
"colors")?a[b]instanceof Array&&(this.renderingInfo[b]=a[b],this._colorBarDirty=!0,this._renderingInfoDirty=!0):"height"===b.toLowerCase()||"transparency"===b.toLowerCase()?(this._clampScope(a,b),"height"==b&&this._heightUnit?(this.renderingInfo[b]=v.toMeters(this._heightUnit,a[b],this._view.viewingMode),this._updateDefaultLabelHeight()):this.renderingInfo[b]=a[b]):typeof a[b]==typeof this.renderingInfo[b]&&(this.renderingInfo[b]=a[b]))},_updateDefaultLabelHeight:function(){this._layer._labelDefaultHeight=
{flag:1,min:this._scopes.height[0],max:this.renderingInfo.height}},initEffect:function(a){this.inherited(arguments);this._effectConfig&&r.isArray(this._effectConfig.renderingInfo)&&(this._heightUnit=null,t.forEach(this._effectConfig.renderingInfo,function(b){"height"===b.name.toLowerCase()&&(this._heightUnit=b.unit,this.renderingInfo.height=v.toMeters(this._heightUnit,this.renderingInfo.height,this._view.viewingMode),this._updateDefaultLabelHeight())}.bind(this)))},destroy:function(){this._resetBuffers()},
_resetBuffers:function(){for(var a in this._renderObjects)this._dispose(this._renderObjects[a].vbo),this._dispose(this._renderObjects[a].ibo),this._dispose(this._renderObjects[a].vao);this._renderObjects={}},_initVertexLayout:function(){this._vertexAttrConstants=[q.POSITION,q.AUXPOS1,q.AUXPOS2];this._vertexBufferLayout=new y(this._vertexAttrConstants,[3,2,2],[5126,5126,5126])},_initRenderContext:function(){if(this.inherited(arguments),this._vacDirty)if(this._initVertexLayout(),this._vacDirty=!1,this._isAddingGeometry)for(var a in this._renderObjects)this._unBindBuffer(this._renderObjects[a].vao,
this._renderObjects[a].vbo,this._renderObjects[a].ibo),this._renderObjects[a].vao&&(this._renderObjects[a].vao._initialized=!1);else this._resetBuffers();return this._localBindsCallback||(this._localBindsCallback=this._localBinds.bind(this)),this._buildAreaGeometries()},_buildAreaGeometries:function(){var a=this._isAddingGeometry?this._addedGraphics:this._allGraphics();if(0<a.length){var b=this._vertexBufferLayout.getStride();this._isAddingGeometry||(this._polygonIdNum=0,this._indexNums=0,this._vertexNums=
0);for(var c=[],d=0;d<a.length;d++){var e=a[d];if(null!=e.geometry){var g=e.geometry.rings;g&&0!==g.length&&(c.push(new C(e,this._polygonIdNum,b)),this._polygonIdNum++)}}for(a=0;a<c.length;a++)this.waitForGeometry(c[a]);return this._resetAddGeometries(),!0}return!1},waitForGeometry:function(a){if(a){a=a.createBuffers(this._wgs84SpatialReference,this._view.renderSpatialReference);for(var b=0;b<a.length;b++){var c=a[b];c&&(this._renderObjects[c.origin.id]||(this._renderObjects[c.origin.id]={vbo:new u(this._gl,
!0,this._vertexBufferLayout),ibo:new u(this._gl,!1),vao:this._vaoExt?new z(this._gl,this._vaoExt):null,offset:0,origin:c.origin.vec3,buffers:[]}));var d=this._renderObjects[c.origin.id];d.vbo.addData(!0,c.vertices);for(var e=c.indices,g=0;g<e.length;g++)e[g]+=d.offset;d.ibo.addData(!0,c.indices);d.offset+=c.vertexNum;d.buffers.push(c);this._maxDist<c.dist&&(this._maxDist=c.dist);1E5<this._maxDist&&(this._maxDist=1E5);d.vao&&(d.vao._initialized=!1)}this._polygonIndex+=a.length}},_initPolygonNormalVerTexture:function(){var a=
this._allGraphics();if(0<a.length){var b=this._gl.getParameter(3379),c=a.length,d=k.nextHighestPowerOfTwo(c);d>b&&(d=b,console.warn("Too many graphics, and extra features will be discarded."));var e=Math.ceil(c/d);e=k.nextHighestPowerOfTwo(e);e>b&&(e=b,console.warn("Too many graphics, and extra features will be discarded."));this._vizFieldVerTextures[this._vizFieldDefault].setData(d,e,new Float32Array(d*e*4));var g,f,m,n;return t.forEach(this._vizFields,function(l){var w=new Float32Array(d*e*4);(f=
a[0].attributes[l])||(f=0);(!f||"number"!=typeof f||0>f)&&(f=0);m=n=f;for(var p=0;p<a.length;p++)g=a[p].attributes,f=g[l],(!f||"number"!=typeof f||0>f)&&(f=0),w[4*p]=f,n<f&&(n=f),m>f&&(m=f);this._vizFieldVerTextures[l].setData(d,e,w);this._vizFieldMinMaxs[l].min=m;this._vizFieldMinMaxs[l].max=n;this._updateVizFieldMinMaxToLayer()}.bind(this)),vec2d.set2(d,e,this._vizFieldVerTextureSize),!0}return!1},_loadShaders:function(){return this.inherited(arguments),this._material||(this._material=new B({pushState:this._pushState.bind(this),
restoreState:this._restoreState.bind(this),gl:this._gl,viewingMode:this._view.viewingMode,shaderSnippets:this._shaderSnippets})),this._material.loadShaders()},_initColorBar:function(){if(!this._colorBarDirty)return!0;this._colorBarTexture||(this._colorBarTexture=this._gl.createTexture());var a=this._gl.getParameter(32873);this._gl.bindTexture(3553,this._colorBarTexture);this._gl.pixelStorei(37440,!0);this._gl.texParameteri(3553,10240,9728);this._gl.texParameteri(3553,10241,9728);this._gl.texParameteri(3553,
10242,33071);this._gl.texParameteri(3553,10243,33071);var b=k.createColorBarTexture(32,1,this.renderingInfo.topColors);return this._gl.texImage2D(3553,0,6408,6408,5121,b),this._gl.generateMipmap(3553),this._gl.bindTexture(3553,a),0===this._gl.getError()},_localBinds:function(a,b){a.bind(this._material._program);this._vertexBufferLayout.enableVertexAttribArrays(this._gl,this._material._program);b.bind()},_bindBuffer:function(a,b,c){a?(a._initialized||a.initialize(this._localBindsCallback,[b,c]),a.bind()):
this._localBinds(b,c)},_unBindBuffer:function(a,b,c){a?a.unbind():(b.unbind(),this._vertexBufferLayout.disableVertexAttribArrays(this._gl,this._material._program),c.unbind())},render:function(a,b){if(this.inherited(arguments),this._layer.visible&&this.ready&&this._bindPramsReady()){this._hasSentReady||(this._layer.emit("fx3d-ready"),this._hasSentReady=!0);this._material.bind(r.mixin({},{el:this._vizFieldVerTextures[this._vizFieldDefault],il:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],
ei:this._vizFieldVerTextureSize,li:this.renderingInfo.animationInterval,lm:[this._scopes.height[0],this.renderingInfo.height],pm:this.renderingInfo.transparency,os:this.renderingInfo.bottomColor,eo:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,ip:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?
this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,po:this._colorBarTexture,ee:this._maxDist},a),b);for(var c in this._renderObjects)h=this._renderObjects[c],this._bindBuffer(h.vao,h.vbo,h.ibo),this._gl.drawElements(4,h.ibo.getNum(),5125,0);this._material.release(b);this._unBindBuffer(h.vao,h.vbo,h.ibo)}}})});