//>>built
define("dojo/_base/lang dojo/_base/array esri/views/layers/LayerView ./SnapshotController esri/geometry/Point esri/geometry/Extent esri/geometry/projection esri/geometry/projection/projectXYZToVector esri/core/libs/gl-matrix-2/vec3f64 esri/core/libs/gl-matrix-2/vec3 esri/geometry/SpatialReference esri/core/reactiveUtils esri/core/Collection esri/Graphic esri/symbols/PictureMarkerSymbol esri/geometry/support/centroid ../effects/FxEffectRendererManager ../effects/FxEffectFactory ../support/fx3dUtils".split(" "),
function(n,A,B,C,D,x,p,y,E,m,F,G,H,w,I,J,t,K,u){p=E.vec3f64;m=m.vec3;var l=p.create(),q=p.create(),r=p.create(),v=p.create(),z=p.create();return B.createSubclass({declaredClass:"esri.views.3d.layers.FxLayerView3D",constructor:function(a){this.supportsDraping=!1;this._fx3dSpatialReference=F.WGS84;a.layer&&(this.layer=a.layer);a.view&&(this.view=a.view);this.availableFields=["*"]},initialize:function(){t.init(this.view);this.layer.when().then(function(){this._eventHandles=[];this.loadedGraphics=null;
this._graphicsLoading=!0;this._graphicsCollectionEventHandle=null;this._graphicsControllerEventHandles=[];var a=this._initEffect();a.then(n.hitch(this,this._initGraphicsController));this.layer.addResolvingPromise(a);this._eventHandles.push(this.layer.on("destroy-fxlayer",function(){t.pause();t.destroy(this._layerVizType,this._layerId);this.view.map.remove(this.layer)}.bind(this)));this._eventHandles.push(this.layer.on("show-feature-label",n.hitch(this,this._onShowFeatureLabel)));this._eventHandles.push(this.layer.on("hide-feature-label",
function(){this.layer&&this.layer._labelsLayer&&(this.layer._labelsLayer.removeAll(),this._selectedFeature=null)}.bind(this)));this._eventHandles.push(this.view.on("click",n.hitch(this,this._viewClicked)))}.bind(this))},destroy:function(){this._viewModelHandler&&(this._viewModelHandler.remove(),this._viewModelHandler=null);var a=function(b){b.remove()};this.controller&&(this.controller.destroy(),this.controller=null);this._graphicsCollectionEventHandle&&this._graphicsCollectionEventHandle.remove();
this._graphicsControllerEventHandles&&this._graphicsControllerEventHandles.forEach(a);this._tilingSchemeHandle&&this._tilingSchemeHandle.remove();this._eventHandles&&this._eventHandles.forEach(a);this.inherited(arguments)},getLoadedGraphics:function(){return this.loadedGraphics&&this.loadedGraphics.toArray?[].concat(this.loadedGraphics.toArray()):[]},_initEffect:function(){return K.make({layer:this.layer,layerView:this,view:this.view})},_calculateExtentCenter:function(a){var b=a.length;if(b){var c,
f,e;if("point"==this.layer.geometryType){var d=c=a[0].geometry.longitude;var g=f=a[0].geometry.latitude;for(e=1;e<b;e++){var h=a[e];null!=h.geometry&&(h.geometry.longitude<d&&(d=h.geometry.longitude),h.geometry.longitude>c&&(c=h.geometry.longitude),h.geometry.latitude<g&&(g=h.geometry.latitude),h.geometry.latitude>f&&(f=h.geometry.latitude))}}else if("polyline"==this.layer.geometryType||"polygon"==this.layer.geometryType){var k=a[0].geometry.extent;d=k.xmin;c=k.xmax;g=k.ymin;f=k.ymax;for(e=1;e<b;e++)h=
a[e],null!=h.geometry&&null!=h.geometry.extent&&(k=h.geometry.extent,k.xmin<d&&(d=k.xmin),k.xmax>c&&(c=k.xmax),k.ymin<g&&(g=k.ymin),k.ymax>f&&(f=k.ymax))}return this._minDelta=6937.5*Math.min(c-d,f-g),new x(d,g,c,f,this._fx3dSpatialReference)}return null},_getGeomZFromPolyline:function(a,b){return m.set(q,a[0],a[1],a[2]||1),u.wgs84ToSphericalEngineCoords(q,0,q,0),m.set(r,b[0],b[1],b[2]||1),u.wgs84ToSphericalEngineCoords(r,0,r,0),m.subtract(z,q,r),m.add(v,q,r),m.scale(v,v,.5),m.length(v)+.6*m.length(z)-
6378137},_calculatePerfectPosition:function(a){var b={};if(null==a||null==a.geometry)return console.warn("Feature or geometry is invalid."),b;var c,f,e,d=a.geometry;if("point"===this.layer.geometryType)b.x=d.longitude,b.y=d.latitude,d=this.layer._labelDefaultHeight,b.z=5E3,d&&this.layer._currentVizFieldMinMax&&(e=this.layer._currentVizFieldMinMax.max-this.layer._currentVizFieldMinMax.min,isNaN(e)||"number"==typeof this.layer._currentVizPage&&(c=this.layer.vizFields[this.layer._currentVizPage],f=a.attributes[c],
null!=f&&(0===d.flag?(b.z+=d.max,0!=e?b.z*=(f-this.layer._currentVizFieldMinMax.min)/e:b.z=d.min):1===d.flag&&(d.max===d.min?b.z+=d.max:0!=e?b.z+=1.2*(d.min+(d.max-d.min)*(f-this.layer._currentVizFieldMinMax.min)/e):0!=this.layer._currentVizFieldMinMax.max?b.z+=d.max:b.z=d.min))));else if("polyline"===this.layer.geometryType){if(null==d.paths)return console.warn("Paths of feature is invalid."),b;a=d.paths[0];c=a.length;b.x=(a[0][0]+a[c-1][0])/2;b.y=(a[0][1]+a[c-1][1])/2;b.z=1.1*this._getGeomZFromPolyline(a[0],
a[c-1])}else if("polygon"===this.layer.geometryType){if(null==d.rings)return console.warn("Rings of feature is invalid."),b;e=J.polygonCentroid({rings:d.rings,hasZ:!1});if(isNaN(e[0])||isNaN(e[1]))return null;b.x=e[0];b.y=e[1];d=this.layer._labelDefaultHeight;b.z=10;e=this.layer._currentVizFieldMinMax.max-this.layer._currentVizFieldMinMax.min;isNaN(e)||(c=this.layer.vizFields[this.layer._currentVizPage],f=a.attributes[c],null!=f&&(0===d.flag?(b.z+=d.max,0!=e?b.z*=(f-this.layer._currentVizFieldMinMax.min)/
e:b.z=d.min):1===d.flag&&(d.max===d.min?b.z+=d.max:0!=e?b.z+=1.3*(d.min+(d.max-d.min)*(f-this.layer._currentVizFieldMinMax.min)/e):0!=this.layer._currentVizFieldMinMax.max?b.z+=d.max:b.z=d.min)))}return isNaN(b.z)&&(b.z=null),b},_calculatePerfectHeight:function(){var a=this.layer._labelDefaultHeight,b=10;this.layer._currentVizFieldMinMax.max==this.layer._currentVizFieldMinMax.min&&0==this.layer._currentVizFieldMinMax.max?b=a&&a.min||1E3:a&&(0===a.flag?b+=a.max:1===a.flag&&(b+=a.max===a.min?a.max:
1.2*(a.min+(a.max-a.min))));a=Math.abs(b)/111E3;return"local"==this.view.viewModel&&(a=Math.abs(b)/235596.8),10<a&&(a=10),{z:b,lonD:a}},_onShowFeatureLabel:function(a){if(this.layer._labelsLayer&&this.layer._labelsLayer.visible){if(this._selectedFeature=null,a.feature){if(null==a.feature.geometry)return void console.warn("The feature with FID has no geometry content.");this.layer._labelsLayer.removeAll();var b=this._calculatePerfectPosition(a.feature);if(null==b.x||null==b.y)return;null==b.z?b.z=
10:b.z+=1E3;var c=u.createTextTexture(""+a.feature.attributes[this.layer.displayField],14,"#ffffff","center","Arial","rgba(0,0,0,0.5)");c=new I({url:c.toDataURL(),width:c.width,height:c.height,contentType:"image/png"});var f=new D(b.x,b.y,b.z,this._fx3dSpatialReference);c=new w(f,c,a.feature.attributes,this.layer.popupTemplate);this.layer._labelsLayer.add(c);c=Math.abs(b.z)/111E3;f=Math.abs(b.z)/(111E3*Math.cos(b.y*Math.PI/180));"local"==this.view.viewModel&&(c=Math.abs(b.z)/111319.5,f=Math.abs(b.z)/
235596.8);10<f&&(f=10);20<c&&(c=20);c=new x(b.x-c,b.y-f,b.x+c,b.y+f,this._fx3dSpatialReference);this._fixCameraPosition(b,c);this._animateTo(c)}else this.layer._labelsLayer.removeAll();this._selectedFeature=a.feature}},_updateSelectedFeatureLabel:function(){if(this.layer._labelsLayer){var a=0<this.layer._labelsLayer.graphics.toArray().length;this.layer._labelsLayer.removeAll();a&&this._selectedFeature&&this._onShowFeatureLabel({feature:this._selectedFeature})}},_viewClicked:function(a){if(a.graphic)if(this.layer._labelsLayer&&
a.graphic.layer===this.layer._labelsLayer)0==this.layer._labelsLayer.graphics.length&&this._onShowFeatureLabel({feature:a.graphic});else{if(a.graphic.layer===this.layer&&this.view&&this.view.popup.viewModel&&this.view.popup.viewModel.selectedFeature){a=this.view.popup.viewModel.selectedFeature;var b=new w({attributes:n.clone(a.attributes),geometry:a.geometry&&a.geometry.clone()||null,popupTemplate:a.popupTemplate||null,symbol:a.symbol||null,visible:a.visible});null!=b&&(this._onShowFeatureLabel({feature:b}),
this.layer.emit("selected-feature-from-globe",{selectedFeature:b}),this.view.popup.viewModel._set("selectedFeature",null))}}else if(this.layer&&this.layer._labelsLayer&&0<this.layer._labelsLayer.graphics.length&&(this.layer._labelsLayer.removeAll(),this._selectedFeature=null,this.layer.emit("abandon-selected-feature"),this.view&&this.view.popup.viewModel&&this.view.popup.viewModel._set("selectedFeature",null)),this.view&&this.view.popup.viewModel&&this.view.popup.viewModel.selectedFeature)try{this.view.popup.viewModel.selectedFeature.symbol=
null,this.view.popup.viewModel.selectedFeature.popupTemplate=null,b=this.view.popup.viewModel.selectedFeature.clone(),this._onShowFeatureLabel({feature:b}),this.layer.emit("selected-feature-from-globe",{selectedFeature:b})}finally{this.view.popup.viewModel._set("selectedFeature",null)}},_fixCameraPosition:function(a,b){var c=a.z;1E4<=c&&(c=1E3);a=a.z;1E4<=a&&(b.center.z=1E3);a=u.clamp(a,1E3,1E4);b.zmin=c;b.zmax=a},_animateTo:function(a,b,c){this.view&&this.view.goTo({target:a,heading:this.view.camera.heading,
tilt:this.view.camera.tilt})},_initGraphicsController:function(a){if(this._layerId=this.layer.id,this._layerVizType=this.layer.vizType,t.addEffect(this.layer,a)){var b=this.view.map.layers.find(function(e){return e.url===this.layer.url&&"esri.layers.FeatureLayer"===e.declaredClass&&"Feature Layer"===e.type&&!0===e.loaded}.bind(this)),c=this;a=function(){var e=H.ofType(w);e={layer:c.layer,layerView:c,graphics:new e};c.controller=new C(e);G.whenOnce(n.hitch(this,function(){return!0===c.view.basemapTerrain.ready})).then(n.hitch(this,
function(){c.controller.when().then(function(){var d=null;c.loadedGraphics=c.controller.graphics;c._graphicsCollectionEventHandle=c.loadedGraphics.on("change",c._collectionChangeHandler.bind(c));0<c.loadedGraphics.length&&(d=c.loadedGraphics.toArray(),c._add([].concat(d)));c._graphicsControllerEventHandles.push(c.controller.on("query-end",function(){c._graphicsLoading=!1}));c.controller.startup()},function(d){console.log(d)})}))};if(b){var f=this.view.layerViews.find(function(e){return e.layer.url===
b.url&&e.layer.id===b.id}.bind(this));f?(b.source&&this.layer._initLayerProperties(b.source),this.loadedGraphics=f.loadedGraphics,0<this.loadedGraphics.length&&this._add([].concat(this.loadedGraphics.toArray())),this.layer.emit("all-features-loaded",{graphics:[].concat(this.loadedGraphics.toArray())})):a()}else a()}},_collectionChangeHandler:function(a){this._add([].concat(a.added));this._remove([].concat(a.removed))},_add:function(a){function b(f){var e,d;f=[].concat(f);A.forEach(f,function(g){if(e=
g.geometry)if("point"==c.layer.geometryType)y.projectXYZToVector(e.x,e.y,e.z,e.spatialReference,l,c._fx3dSpatialReference),e.longitude=l[0],e.latitude=l[1],e.altitude=isNaN(l[2])?null:l[2];else{if("polyline"==c.layer.geometryType||"polygon"==c.layer.geometryType)for(d=e.paths||e.rings,g=0;g<d.length;g++)for(var h=0;h<d[g].length;h++)y.projectXYZToVector(d[g][h][0],d[g][h][1],d[g][h][2],e.spatialReference,l,c._fx3dSpatialReference),d[g][h][0]=l[0],d[g][h][1]=l[1],d[g][h][2]=isNaN(l[2])?null:l[2]}else console.warn("No geometry information found in feature: "+
g.attributes.FID)});c.layer.emit("fx3d-add-graphics",{graphics:f});c._graphicsLoading||(c.layer.on("can-locating-now",function(){var g=c._calculateExtentCenter(c.getLoadedGraphics());if(g){var h=c._calculatePerfectHeight();g.zmax=h.z;g.zmin=h.z-1;g.xmax+=2+h.lonD;g.xmin-=2+h.lonD;g.ymax+=1+h.lonD;g.ymin-=1+h.lonD;c._animateTo(g)}}),c.layer.emit("all-features-loaded",{graphics:c.getLoadedGraphics()}))}if(n.isArray(a)&&0<a.length){var c=this;this.isResolved()?b(a):this.when().then(function(){b(a)})}},
_remove:function(a){n.isArray(a)&&0<a.length}})});