//>>built
define(["esri/core/Accessor"],function(p){var q=0;return p.createSubclass({constructor:function(){this._deletedGraphicsIndex=new Set;this._intentsIndex=new Map},destroy:function(){this.removeAll();this._intentsIndex=this._deletedGraphicsIndex=null},properties:{graphics:null,indexById:{value:null,dependsOn:["graphics","objectIdField"],get:function(){return this._createIndexById(this.graphics&&this.graphics.toArray(),this.objectIdField)}},numGraphics:{value:0,dependsOn:["indexById"],get:function(){return this.indexById?
this.indexById.size:0}},objectIdField:null,updating:{value:!1,dependsOn:["_intentsIndex"],get:function(){return!!(this._intentsIndex&&0<this._intentsIndex.size)}},_intentsIndex:{value:null}},_oldIndex:null,_deletedGraphicsIndex:null,beginPagedUpdate:function(){this._oldIndex=this.indexById;this.indexById=null;this.notifyChange("numGraphics")},addPage:function(a,c){this.add(a,c)},revertPagedUpdate:function(){var a=this._removeLeftOnly(this.indexById,this._oldIndex);this.indexById=this._oldIndex;this._oldIndex=
null;this.graphics.removeMany(a);this.notifyChange("numGraphics")},endPagedUpdate:function(){var a=this._removeLeftOnly(this._oldIndex,this.indexById);this._oldIndex=null;this.graphics.removeMany(a);this.notifyChange("numGraphics")},findGraphic:function(a){return(a=this.indexById&&this.indexById.get(a))&&a.graphic},removeAll:function(){this.indexById=this._oldIndex=null;this.graphics.removeAll();this.notifyChange("numGraphics")},add:function(a,c){if(a&&a.length){var d=this.objectIdField,b=this.indexById=
this.indexById||new Map,e=this._oldIndex,f=this._createIndexById(a,d);f=this._extractObjectIds(f);b=this._extractObjectIds(b);e=this._extractObjectIds(e);b=b.concat(e);var g=[],m=b.length;for(e=0;e<m;e++){var h=b[e];-1<f.indexOf(h)&&g.push(h)}g.length&&this._remove(g,!1);c=this.findIntent(c);f=new Map;b=a.length;for(e=0;e<b;e++)(g=a[e])&&g.attributes&&f.set(g.attributes[d],c);a.length&&this._add(a,f)}},remove:function(a){this._remove(a,!1)},"delete":function(a){this._remove(a,!0)},isDeleted:function(a){return this._deletedGraphicsIndex.has(a)},
createIntentToAdd:function(a){a&&this._intentsIndex.forEach(function(d,b){a.forEach(function(e){d.ignoredIds.add(e)})},this);var c=q++;return this._intentsIndex.set(c,{ignoredIds:new Set}),this.notifyChange("updating"),c},findIntent:function(a){return this._intentsIndex.get(a)},removeIntent:function(a){this._intentsIndex["delete"](a);this.notifyChange("updating")},update:function(a,c){if(a&&a.length){var d=this.objectIdField,b=this.indexById=this.indexById||new Map,e=this._oldIndex;a=this._createIndexById(a,
d);d=this._extractObjectIds(a);var f=this._extractObjectIds(b),g=this._extractObjectIds(e);f=f.concat(g);g=[];for(var m=f.length,h=0;h<m;h++){var k=f[h];if(-1===d.indexOf(k))g.push(k);else{var l=b.get(k)||e.get(k);l=l&&l.graphic&&l.graphic._ts;var n=a.get(k);(n&&n.graphic&&n.graphic._ts)>l&&g.push(k)}}b=[];e=d.length;for(h=0;h<e;h++)k=d[h],(-1===f.indexOf(k)||-1<g.indexOf(k))&&b.push(k);g.length&&this._remove(g,!1);b.length&&this._add(this._extractGraphics(b,a),c)}},_createIndexById:function(a,c){if(a&&
a.length&&c){var d,b;var e=new Map;for(d=0;b=a[d];d++){var f=b.attributes&&b.attributes[c];null!=f&&e.set(f,{graphic:b,refCount:1})}}return e},_add:function(a,c){var d=this.objectIdField;a.forEach(function(b){var e=c.get(b.attributes&&b.attributes[d]);this._addToIndex(b,this.indexById,e)},this);this.graphics.addMany(a);this.notifyChange("numGraphics")},_addToIndex:function(a,c,d){var b=a.attributes&&a.attributes[this.objectIdField];c&&null!=b&&(c.has(b)?d&&d.ignoredIds.has(b)||(d=c.get(b),c.set(b,
{graphic:a,refCount:d.refCount+1})):this.isDeleted(b)||c.set(b,{graphic:a,refCount:1}))},_remove:function(a,c){a=a||[];a="object"==typeof a[0]?a.map(function(e){return e.attributes&&e.attributes[this.objectIdField]}.bind(this)):a;var d=this._extractGraphics(a,this._oldIndex),b=this._extractGraphics(a,this.indexById);a.forEach(function(e){c&&this._deletedGraphicsIndex.add(e);this._removeFromIndex(e,this._oldIndex,c);this._removeFromIndex(e,this.indexById,c)}.bind(this));this.graphics.removeMany(d.concat(b));
this.notifyChange("numGraphics")},_removeFromIndex:function(a,c,d){if(c&&c.has(a))if(d)c["delete"](a);else{d=c.get(a);var b=d.refCount-1;0===b?c["delete"](a):d.refCount=b}},_removeLeftOnly:function(a,c){var d=[];return a&&a.forEach(function(b,e){var f=b.graphic;!f||c&&c.has(e)||(--b.refCount,0===b.refCount&&a["delete"](e),d.push(f))}),d},_extractGraphics:function(a,c){return a&&c?a.map(function(d){return(d=c.get(d))&&d.graphic}):[]},_extractObjectIds:function(a){var c=[];return a&&a.forEach(function(d,
b){c.push(b)}),c}})});