//>>built
/*
 @esri/arcgis-html-sanitizer - v2.2.0 - Tue Feb 04 2020 08:00:46 GMT-0500 (Eastern Standard Time)
 Copyright (c) 2020 - Environmental Systems Research Institute, Inc.
 Apache-2.0

 js-xss
 Copyright (c) 2012-2017 Zongmin Lei(雷宗民) <leizongmin@gmail.com>
 http://ucdok.com
 MIT License, see https://github.com/leizongmin/js-xss/blob/master/LICENSE for details

 Lodash/isPlainObject
 Copyright (c) JS Foundation and other contributors <https://js.foundation/>
 MIT License, see https://raw.githubusercontent.com/lodash/lodash/4.17.10-npm/LICENSE for details
*/
require({cache:{"libs/usng/usng":function(){window.console||(window.console={warn:function(){}});define(["dojo/_base/declare","dojo/string"],function(Q,z){var J,K,D,r=Math.PI/180,A=180/Math.PI;var F=6378137;var t=.006694380023;var w=t/(1-t),u=(1-Math.sqrt(1-t))/(1+Math.sqrt(1-t));return{getZoneNumber:function(g,f){g=parseFloat(g);f=parseFloat(f);(360<f||-180>f||90<g||-90>g)&&console.warn("Bad input. lat: "+g+" lon: "+f);f=f+180-360*parseInt((f+180)/360)-180;var c=parseInt((f+180)/6)+1;56<=g&&64>g&&
3<=f&&12>f&&(c=32);72<=g&&84>g&&(0<=f&&9>f?c=31:9<=f&&21>f?c=33:21<=f&&33>f?c=35:33<=f&&42>f&&(c=37));return c},LLtoUTM:function(g,f,c,d){g=parseFloat(g);f=parseFloat(f);if(84<g||-80>g)return"undefined";(360<f||-180>f||90<g||-90>g)&&console.warn("Bad input. lat: "+g+" lon: "+f);var e=f+180-360*parseInt((f+180)/360)-180,m=g*r;e*=r;D=d?d:this.getZoneNumber(g,f);var a=(6*(D-1)-180+3)*r;this.UTMLetterDesignator(g);g=F/Math.sqrt(1-t*Math.sin(m)*Math.sin(m));f=Math.tan(m)*Math.tan(m);d=w*Math.cos(m)*Math.cos(m);
e=Math.cos(m)*(e-a);a=F*((1-t/4-3*t*t/64-5*t*t*t/256)*m-(3*t/8+3*t*t/32+45*t*t*t/1024)*Math.sin(2*m)+(15*t*t/256+45*t*t*t/1024)*Math.sin(4*m)-35*t*t*t/3072*Math.sin(6*m));J=.9996*g*(e+(1-f+d)*e*e*e/6+(5-18*f+f*f+72*d-58*w)*e*e*e*e*e/120)+5E5;K=.9996*(a+g*Math.tan(m)*(e*e/2+(5-f+9*d+4*d*d)*e*e*e*e/24+(61-58*f+f*f+600*d-330*w)*e*e*e*e*e*e/720));c[0]=J;c[1]=K;c[2]=D},LLtoUSNG:function(g,f,c){g=parseFloat(g);f=parseFloat(f);var d=[];this.LLtoUTM(g,f,d);var e=d[0];d=d[1];0>g&&(d+=1E7);var m=this.findGridLetters(D,
d,e);d=Math.round(d)%1E5;e=Math.round(e)%1E5;d=Math.floor(d/Math.pow(10,5-c));e=Math.floor(e/Math.pow(10,5-c));g=this.getZoneNumber(g,f)+this.UTMLetterDesignator(g)+" "+m+" ";for(f=String(e).length;f<c;f++)g+="0";g+=e+" ";for(f=String(d).length;f<c;f++)g+="0";return g+d},UTMLetterDesignator:function(g){g=parseFloat(g);return 84>=g&&72<=g?"X":72>g&&64<=g?"W":64>g&&56<=g?"V":56>g&&48<=g?"U":48>g&&40<=g?"T":40>g&&32<=g?"S":32>g&&24<=g?"R":24>g&&16<=g?"Q":16>g&&8<=g?"P":8>g&&0<=g?"N":0>g&&-8<=g?"M":-8>
g&&-16<=g?"L":-16>g&&-24<=g?"K":-24>g&&-32<=g?"J":-32>g&&-40<=g?"H":-40>g&&-48<=g?"G":-48>g&&-56<=g?"F":-56>g&&-64<=g?"E":-64>g&&-72<=g?"D":-72>g&&-80<=g?"C":"Z"},findSet:function(g){g=parseInt(g);switch(g%6){case 0:return 6;case 1:return 1;case 2:return 2;case 3:return 3;case 4:return 4;case 5:return 5;default:return-1}},findGridLetters:function(g,f,c){g=parseInt(g);f=parseFloat(f);c=parseFloat(c);var d=1;for(f=Math.round(f);1E5<=f;)f-=1E5,d++;d%=20;f=0;for(c=Math.round(c);1E5<=c;)c-=1E5,f++;f%=
8;return this.lettersHelper(this.findSet(g),d,f)},lettersHelper:function(g,f,c){0===f?f=19:f--;0===c?c=7:c--;switch(g){case 1:return g="ABCDEFGHJKLMNPQRSTUV","ABCDEFGH".charAt(c)+g.charAt(f);case 2:return g="FGHJKLMNPQRSTUVABCDE","JKLMNPQR".charAt(c)+g.charAt(f);case 3:return g="ABCDEFGHJKLMNPQRSTUV","STUVWXYZ".charAt(c)+g.charAt(f);case 4:return g="FGHJKLMNPQRSTUVABCDE","ABCDEFGH".charAt(c)+g.charAt(f);case 5:return g="ABCDEFGHJKLMNPQRSTUV","JKLMNPQR".charAt(c)+g.charAt(f);case 6:return g="FGHJKLMNPQRSTUVABCDE",
"STUVWXYZ".charAt(c)+g.charAt(f)}},UTMtoLL:function(g,f,c,d){f=parseFloat(f)-5E5;g=parseFloat(g);c=parseInt(c);g=g/.9996/(F*(1-t/4-3*t*t/64-5*t*t*t/256));g=g+(3*u/2-27*u*u*u/32)*Math.sin(2*g)+(21*u*u/16-55*u*u*u*u/32)*Math.sin(4*g)+151*u*u*u/96*Math.sin(6*g);var e=F/Math.sqrt(1-t*Math.sin(g)*Math.sin(g)),m=Math.tan(g)*Math.tan(g),a=w*Math.cos(g)*Math.cos(g);f/=.9996*e;e=g-e*Math.tan(g)/(F*(1-t)/Math.pow(1-t*Math.sin(g)*Math.sin(g),1.5))*(f*f/2-(5+3*m+10*a-4*a*a-9*w)*f*f*f*f/24+(61+90*m+298*a+45*m*
m-252*w-3*a*a)*f*f*f*f*f*f/720);e*=A;f=(f-(1+2*m+a)*f*f*f/6+(5-2*a+28*m-3*a*a+8*w+24*m*m)*f*f*f*f*f/120)/Math.cos(g);f=6*(c-1)-180+3+f*A;d.lat=e;d.lon=f},USNGtoUTM:function(g,f,c,d,e,m,a){c=1+"ABCDEFGHJKLMNPQRSTUVWXYZ".indexOf(c)%8;var b="CDEFGHJKLMNPQRSTUVWX".indexOf(f);d=g%2?"ABCDEFGHJKLMNPQRSTUV".indexOf(d):"FGHJKLMNPQRSTUVABCDE".indexOf(d);d=Number([0,2,2,2,4,4,6,6,8,8,0,0,0,2,2,4,4,6,6,6][b])+d/10;d<[1.1,2,2.9,3.8,4.7,5.6,6.5,7.3,8.2,9.1,0,.8,1.7,2.6,3.5,4.4,5.3,6.2,7,7.9][b]&&(d+=2);a.N=1E6*
d+Number(m)*Math.pow(10,5-m.length);a.E=1E5*c+Number(e)*Math.pow(10,5-e.length);a.zone=g;a.letter=f},USNGtoLL:function(g,f){var c={};this.parseUSNG_str(g,c);g={};this.USNGtoUTM(c.zone,c.let,c.sq1,c.sq2,c.east,c.north,g);"N">c.let&&(g.N-=1E7);this.UTMtoLL(g.N,g.E,c.zone,g);f[0]=g.lat;f[1]=g.lon},parseUSNG_str:function(g,f){var c=0,d=[];var e=[];e=g.toUpperCase();d=/%20/g;d=e.replace(d,"");d=/ /g;d=e.replace(d,"");if(7>d.length)return console.warn("This application requires minimum USNG precision of 10,000 meters"),
0;f.zone=10*d.charAt(c++)+1*d.charAt(c++);f.let=d.charAt(c++);f.sq1=d.charAt(c++);f.sq2=d.charAt(c++);f.precision=(d.length-c)/2;f.east="";f.north="";for(e=0;e<f.precision;e++)f.east+=d.charAt(c++);" "==d[c]&&c++;for(e=0;e<f.precision;e++)f.north+=d.charAt(c++)},isUSNG:function(g){var f=[];f=g.toUpperCase();g=/%20/g;f=f.replace(g,"");g=/ /g;f=f.replace(g,"");if(15<f.length)return 0;g=RegExp("^[0-9]{2}[CDEFGHJKLMNPQRSTUVWX]$");if(f.match(g))return console.warn("Input appears to be a UTM zone...more precision is required to display a correct result."),
0;g=RegExp("^[0-9]{2}[CDEFGHJKLMNPQRSTUVWX][ABCDEFGHJKLMNPQRSTUVWXYZ][ABCDEFGHJKLMNPQRSTUV]([0-9][0-9]){0,5}");return f.match(g)?7>f.length?(alert(f+" Appears to be a USNG string, but this application requires precision of at least 10,000 meters"),0):f:0},LLtoMGRS:function(g,f,c){var d="";return d=this.LLtoUSNG(g,f,c).replace(/ /g,"")},LLtoUSNG_nad27:function(g,f,c){F=6378206.4;t=.006768658;g=this.LLtoUSNG(g,f,c);F=6378137;t=.006694380023;return g+" (NAD27)"}}})},"dojo/string":function(){define(["./_base/kernel",
"./_base/lang"],function(Q,z){var J=/[&<>'"\/]/g,K={"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;","/":"\x26#x2F;"},D={};z.setObject("dojo.string",D);D.escape=function(r){return r?r.replace(J,function(A){return K[A]}):""};D.codePointAt=String.prototype.codePointAt?function(r,A){return String.prototype.codePointAt.call(r,A)}:function(r,A){if(null==r)throw new TypeError("codePointAt called on null or undefined");r=String(r);var F=r.length;var t=A?Number(A):0;t!=
t&&(t=0);if(!(0>t||t>=F))return A=r.charCodeAt(t),55296<=A&&56319>=A&&F>t+1&&(r=r.charCodeAt(t+1),56320<=r&&57343>=r)?1024*(A-55296)+r-56320+65536:A};D.fromCodePoint=String.fromCodePoint||function(){var r=[],A=0,F="";var t=0;for(len=arguments.length;t!==len;++t){A=+arguments[t];if(!(1114111>A&&A>>>0===A))throw RangeError("Invalid code point: "+A);65535>=A?A=r.push(A):(A-=65536,A=r.push((A>>10)+55296,A%1024+56320));16383<=A&&(F+=String.fromCharCode.apply(null,r),r.length=0)}return F+String.fromCharCode.apply(null,
r)};D.rep=function(r,A){if(0>=A||!r)return"";for(var F=[];;){A&1&&F.push(r);if(!(A>>=1))break;r+=r}return F.join("")};D.pad=function(r,A,F,t){F||(F="0");r=String(r);A=D.rep(F,Math.ceil((A-r.length)/F.length));return t?r+A:A+r};D.substitute=function(r,A,F,t){t=t||Q.global;F=F?z.hitch(t,F):function(w){return w};return r.replace(/\$\{([^\s:\}]*)(?::([^\s:\}]+))?\}/g,function(w,u,g){if(""==u)return"$";w=z.getObject(u,!1,A);g&&(w=z.getObject(g,!1,t).call(t,w,u));g=F(w,u);if("undefined"===typeof g)throw Error('string.substitute could not find key "'+
u+'" in template');return g.toString()})};D.trim=String.prototype.trim?z.trim:function(r){r=r.replace(/^\s+/,"");for(var A=r.length-1;0<=A;A--)if(/\S/.test(r.charAt(A))){r=r.substring(0,A+1);break}return r};return D})},"libs/storejs/json":function(){define(["dojo","dijit","dojox"],function(Q,z,J){this.JSON||(this.JSON={});(function(){function K(f){return 10>f?"0"+f:f}function D(f){F.lastIndex=0;return F.test(f)?'"'+f.replace(F,function(c){var d=u[c];return"string"===typeof d?d:"\\u"+("0000"+c.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+f+'"'}function r(f,c){var d=t,e=c[f];e&&"object"===typeof e&&"function"===typeof e.toJSON&&(e=e.toJSON(f));"function"===typeof g&&(e=g.call(c,f,e));switch(typeof e){case "string":return D(e);case "number":return isFinite(e)?String(e):"null";case "boolean":case "null":return String(e);case "object":if(!e)return"null";t+=w;var m=[];if("[object Array]"===Object.prototype.toString.apply(e)){var a=e.length;for(f=0;f<a;f+=1)m[f]=r(f,e)||"null";c=0===m.length?"[]":t?"[\n"+t+m.join(",\n"+t)+"\n"+
d+"]":"["+m.join(",")+"]";t=d;return c}if(g&&"object"===typeof g)for(a=g.length,f=0;f<a;f+=1){var b=g[f];"string"===typeof b&&(c=r(b,e))&&m.push(D(b)+(t?": ":":")+c)}else for(b in e)Object.hasOwnProperty.call(e,b)&&(c=r(b,e))&&m.push(D(b)+(t?": ":":")+c);c=0===m.length?"{}":t?"{\n"+t+m.join(",\n"+t)+"\n"+d+"}":"{"+m.join(",")+"}";t=d;return c}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(f){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+K(this.getUTCMonth()+
1)+"-"+K(this.getUTCDate())+"T"+K(this.getUTCHours())+":"+K(this.getUTCMinutes())+":"+K(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(f){return this.valueOf()});var A=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,F=/[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,t,w,u={"\b":"\\b","\t":"\\t","\n":"\\n",
"\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;"function"!==typeof JSON.stringify&&(JSON.stringify=function(f,c,d){var e;w=t="";if("number"===typeof d)for(e=0;e<d;e+=1)w+=" ";else"string"===typeof d&&(w=d);if((g=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return r("",{"":f})});"function"!==typeof JSON.parse&&(JSON.parse=function(f,c){function d(e,m){var a,b=e[m];if(b&&"object"===typeof b)for(a in b)if(Object.hasOwnProperty.call(b,a)){var k=
d(b,a);void 0!==k?b[a]=k:delete b[a]}return c.call(e,m,b)}f=String(f);A.lastIndex=0;A.test(f)&&(f=f.replace(A,function(e){return"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(f.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+f+")"),"function"===typeof c?d({"":f},""):f;throw new SyntaxError("JSON.parse");})})()})},"dijit/main":function(){define(["dojo/_base/kernel"],
function(Q){return Q.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],function(Q){return Q.dojox})},"libs/storejs/store":function(){(function(Q){var z={},J=Q.document;z.disabled=!1;z.set=function(w,u){};z.get=function(w){};z.remove=function(w){};z.clear=function(){};z.transact=function(w,u,g){var f=z.get(w);null==g&&(g=u,u=null);"undefined"==typeof f&&(f=u||{});g(f);z.set(w,f)};z.getAll=function(){};z.forEach=function(){};z.serialize=function(w){return JSON.stringify(w)};z.deserialize=
function(w){if("string"==typeof w)try{return JSON.parse(w)}catch(u){return w||void 0}};try{var K="localStorage"in Q&&Q.localStorage}catch(w){K=!1}if(K){var D=Q.localStorage;z.set=function(w,u){if(void 0===u)return z.remove(w);D.setItem(w,z.serialize(u));return u};z.get=function(w){return z.deserialize(D.getItem(w))};z.remove=function(w){D.removeItem(w)};z.clear=function(){D.clear()};z.getAll=function(){var w={};z.forEach(function(u,g){w[u]=g});return w};z.forEach=function(w){for(var u=0;u<D.length;u++){var g=
D.key(u);w(g,z.get(g))}}}else if(J.documentElement.addBehavior){try{var r=new ActiveXObject("htmlfile");r.open();r.write('\x3cscript\x3edocument.w\x3dwindow\x3c/script\x3e\x3ciframe src\x3d"/favicon.ico"\x3e\x3c/iframe\x3e');r.close();var A=r.w.frames[0].document;D=A.createElement("div")}catch(w){D=J.createElement("div"),A=J.body}J=function(w){return function(){var u=Array.prototype.slice.call(arguments,0);u.unshift(D);A.appendChild(D);D.addBehavior("#default#userData");D.load("localStorage");u=w.apply(z,
u);A.removeChild(D);return u}};var F=RegExp("[!\"#$%\x26'()*+,/\\\\:;\x3c\x3d\x3e?@[\\]^`{|}~]","g"),t=function(w){return w.replace(/^d/,"___$\x26").replace(F,"___")};z.set=J(function(w,u,g){u=t(u);if(void 0===g)return z.remove(u);w.setAttribute(u,z.serialize(g));w.save("localStorage");return g});z.get=J(function(w,u){u=t(u);return z.deserialize(w.getAttribute(u))});z.remove=J(function(w,u){u=t(u);w.removeAttribute(u);w.save("localStorage")});z.clear=J(function(w){var u=w.XMLDocument.documentElement.attributes;
w.load("localStorage");for(var g=0,f;f=u[g];g++)w.removeAttribute(f.name);w.save("localStorage")});z.getAll=function(w){var u={};z.forEach(function(g,f){u[g]=f});return u};z.forEach=J(function(w,u){for(var g=w.XMLDocument.documentElement.attributes,f=0,c;c=g[f];++f)u(c.name,z.deserialize(w.getAttribute(c.name)))})}try{z.set("__storejs__","__storejs__"),"__storejs__"!=z.get("__storejs__")&&(z.disabled=!0),z.remove("__storejs__")}catch(w){z.disabled=!0}z.enabled=!z.disabled;"undefined"!=typeof module&&
module.exports&&this.module!==module?module.exports=z:"function"===typeof define&&define.amd?define(z):Q.store=z})(Function("return this")())},"libs/md5/md5":function(){(function(Q){function z(c,d){var e=(c&65535)+(d&65535);return(c>>16)+(d>>16)+(e>>16)<<16|e&65535}function J(c,d,e,m,a,b){c=z(z(d,c),z(m,b));return z(c<<a|c>>>32-a,e)}function K(c,d,e,m,a,b,k){return J(d&e|~d&m,c,d,a,b,k)}function D(c,d,e,m,a,b,k){return J(d&m|e&~m,c,d,a,b,k)}function r(c,d,e,m,a,b,k){return J(e^(d|~m),c,d,a,b,k)}function A(c,
d){c[d>>5]|=128<<d%32;c[(d+64>>>9<<4)+14]=d;var e=1732584193,m=-271733879,a=-1732584194,b=271733878;for(d=0;d<c.length;d+=16){var k=e;var l=m;var q=a;var y=b;e=K(e,m,a,b,c[d],7,-680876936);b=K(b,e,m,a,c[d+1],12,-389564586);a=K(a,b,e,m,c[d+2],17,606105819);m=K(m,a,b,e,c[d+3],22,-1044525330);e=K(e,m,a,b,c[d+4],7,-176418897);b=K(b,e,m,a,c[d+5],12,1200080426);a=K(a,b,e,m,c[d+6],17,-1473231341);m=K(m,a,b,e,c[d+7],22,-45705983);e=K(e,m,a,b,c[d+8],7,1770035416);b=K(b,e,m,a,c[d+9],12,-1958414417);a=K(a,b,
e,m,c[d+10],17,-42063);m=K(m,a,b,e,c[d+11],22,-1990404162);e=K(e,m,a,b,c[d+12],7,1804603682);b=K(b,e,m,a,c[d+13],12,-40341101);a=K(a,b,e,m,c[d+14],17,-1502002290);m=K(m,a,b,e,c[d+15],22,1236535329);e=D(e,m,a,b,c[d+1],5,-165796510);b=D(b,e,m,a,c[d+6],9,-1069501632);a=D(a,b,e,m,c[d+11],14,643717713);m=D(m,a,b,e,c[d],20,-373897302);e=D(e,m,a,b,c[d+5],5,-701558691);b=D(b,e,m,a,c[d+10],9,38016083);a=D(a,b,e,m,c[d+15],14,-660478335);m=D(m,a,b,e,c[d+4],20,-405537848);e=D(e,m,a,b,c[d+9],5,568446438);b=D(b,
e,m,a,c[d+14],9,-1019803690);a=D(a,b,e,m,c[d+3],14,-187363961);m=D(m,a,b,e,c[d+8],20,1163531501);e=D(e,m,a,b,c[d+13],5,-1444681467);b=D(b,e,m,a,c[d+2],9,-51403784);a=D(a,b,e,m,c[d+7],14,1735328473);m=D(m,a,b,e,c[d+12],20,-1926607734);e=J(m^a^b,e,m,c[d+5],4,-378558);b=J(e^m^a,b,e,c[d+8],11,-2022574463);a=J(b^e^m,a,b,c[d+11],16,1839030562);m=J(a^b^e,m,a,c[d+14],23,-35309556);e=J(m^a^b,e,m,c[d+1],4,-1530992060);b=J(e^m^a,b,e,c[d+4],11,1272893353);a=J(b^e^m,a,b,c[d+7],16,-155497632);m=J(a^b^e,m,a,c[d+
10],23,-1094730640);e=J(m^a^b,e,m,c[d+13],4,681279174);b=J(e^m^a,b,e,c[d],11,-358537222);a=J(b^e^m,a,b,c[d+3],16,-722521979);m=J(a^b^e,m,a,c[d+6],23,76029189);e=J(m^a^b,e,m,c[d+9],4,-640364487);b=J(e^m^a,b,e,c[d+12],11,-421815835);a=J(b^e^m,a,b,c[d+15],16,530742520);m=J(a^b^e,m,a,c[d+2],23,-995338651);e=r(e,m,a,b,c[d],6,-198630844);b=r(b,e,m,a,c[d+7],10,1126891415);a=r(a,b,e,m,c[d+14],15,-1416354905);m=r(m,a,b,e,c[d+5],21,-57434055);e=r(e,m,a,b,c[d+12],6,1700485571);b=r(b,e,m,a,c[d+3],10,-1894986606);
a=r(a,b,e,m,c[d+10],15,-1051523);m=r(m,a,b,e,c[d+1],21,-2054922799);e=r(e,m,a,b,c[d+8],6,1873313359);b=r(b,e,m,a,c[d+15],10,-30611744);a=r(a,b,e,m,c[d+6],15,-1560198380);m=r(m,a,b,e,c[d+13],21,1309151649);e=r(e,m,a,b,c[d+4],6,-145523070);b=r(b,e,m,a,c[d+11],10,-1120210379);a=r(a,b,e,m,c[d+2],15,718787259);m=r(m,a,b,e,c[d+9],21,-343485551);e=z(e,k);m=z(m,l);a=z(a,q);b=z(b,y)}return[e,m,a,b]}function F(c){var d,e="";for(d=0;d<32*c.length;d+=8)e+=String.fromCharCode(c[d>>5]>>>d%32&255);return e}function t(c){var d,
e=[];e[(c.length>>2)-1]=void 0;for(d=0;d<e.length;d+=1)e[d]=0;for(d=0;d<8*c.length;d+=8)e[d>>5]|=(c.charCodeAt(d/8)&255)<<d%32;return e}function w(c){return F(A(t(c),8*c.length))}function u(c,d){var e=t(c),m=[],a=[];m[15]=a[15]=void 0;16<e.length&&(e=A(e,8*c.length));for(c=0;16>c;c+=1)m[c]=e[c]^909522486,a[c]=e[c]^1549556828;d=A(m.concat(t(d)),512+8*d.length);return F(A(a.concat(d),640))}function g(c){var d="",e;for(e=0;e<c.length;e+=1){var m=c.charCodeAt(e);d+="0123456789abcdef".charAt(m>>>4&15)+
"0123456789abcdef".charAt(m&15)}return d}function f(c,d,e){d?e?c=u(unescape(encodeURIComponent(d)),unescape(encodeURIComponent(c))):(c=u(unescape(encodeURIComponent(d)),unescape(encodeURIComponent(c))),c=g(c)):c=e?w(unescape(encodeURIComponent(c))):g(w(unescape(encodeURIComponent(c))));return c}"function"===typeof define&&define.amd?define(function(){return f}):Q.md5=f})(this)},"libs/qrcode":function(){define(["dojo","dijit","dojox"],function(Q,z,J){var K;(function(){function D(a){this.mode=u.MODE_8BIT_BYTE;
this.data=a;this.parsedData=[];a=0;for(var b=this.data.length;a<b;a++){var k=[],l=this.data.charCodeAt(a);65536<l?(k[0]=240|(l&1835008)>>>18,k[1]=128|(l&258048)>>>12,k[2]=128|(l&4032)>>>6,k[3]=128|l&63):2048<l?(k[0]=224|(l&61440)>>>12,k[1]=128|(l&4032)>>>6,k[2]=128|l&63):128<l?(k[0]=192|(l&1984)>>>6,k[1]=128|l&63):k[0]=l;this.parsedData.push(k)}this.parsedData=Array.prototype.concat.apply([],this.parsedData);this.parsedData.length!=this.data.length&&(this.parsedData.unshift(191),this.parsedData.unshift(187),
this.parsedData.unshift(239))}function r(a,b){this.typeNumber=a;this.errorCorrectLevel=b;this.modules=null;this.moduleCount=0;this.dataCache=null;this.dataList=[]}function A(a,b){if(void 0==a.length)throw Error(a.length+"/"+b);for(var k=0;k<a.length&&0==a[k];)k++;this.num=Array(a.length-k+b);for(b=0;b<a.length-k;b++)this.num[b]=a[b+k]}function F(a,b){this.totalCount=a;this.dataCount=b}function t(){this.buffer=[];this.length=0}function w(){var a=!1,b=navigator.userAgent;/android/i.test(b)&&(a=!0,(aMat=
b.toString().match(/android ([0-9]\.[0-9])/i))&&aMat[1]&&(a=parseFloat(aMat[1])));return a}D.prototype={getLength:function(a){return this.parsedData.length},write:function(a){for(var b=0,k=this.parsedData.length;b<k;b++)a.put(this.parsedData[b],8)}};r.prototype={addData:function(a){a=new D(a);this.dataList.push(a);this.dataCache=null},isDark:function(a,b){if(0>a||this.moduleCount<=a||0>b||this.moduleCount<=b)throw Error(a+","+b);return this.modules[a][b]},getModuleCount:function(){return this.moduleCount},
make:function(){this.makeImpl(!1,this.getBestMaskPattern())},makeImpl:function(a,b){this.moduleCount=4*this.typeNumber+17;this.modules=Array(this.moduleCount);for(var k=0;k<this.moduleCount;k++){this.modules[k]=Array(this.moduleCount);for(var l=0;l<this.moduleCount;l++)this.modules[k][l]=null}this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-7,0);this.setupPositionProbePattern(0,this.moduleCount-7);this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(a,
b);7<=this.typeNumber&&this.setupTypeNumber(a);null==this.dataCache&&(this.dataCache=r.createData(this.typeNumber,this.errorCorrectLevel,this.dataList));this.mapData(this.dataCache,b)},setupPositionProbePattern:function(a,b){for(var k=-1;7>=k;k++)if(!(-1>=a+k||this.moduleCount<=a+k))for(var l=-1;7>=l;l++)-1>=b+l||this.moduleCount<=b+l||(this.modules[a+k][b+l]=0<=k&&6>=k&&(0==l||6==l)||0<=l&&6>=l&&(0==k||6==k)||2<=k&&4>=k&&2<=l&&4>=l?!0:!1)},getBestMaskPattern:function(){for(var a=0,b=0,k=0;8>k;k++){this.makeImpl(!0,
k);var l=f.getLostPoint(this);if(0==k||a>l)a=l,b=k}return b},createMovieClip:function(a,b,k){a=a.createEmptyMovieClip(b,k);this.make();for(b=0;b<this.modules.length;b++){k=1*b;for(var l=0;l<this.modules[b].length;l++){var q=1*l;this.modules[b][l]&&(a.beginFill(0,100),a.moveTo(q,k),a.lineTo(q+1,k),a.lineTo(q+1,k+1),a.lineTo(q,k+1),a.endFill())}}return a},setupTimingPattern:function(){for(var a=8;a<this.moduleCount-8;a++)null==this.modules[a][6]&&(this.modules[a][6]=0==a%2);for(a=8;a<this.moduleCount-
8;a++)null==this.modules[6][a]&&(this.modules[6][a]=0==a%2)},setupPositionAdjustPattern:function(){for(var a=f.getPatternPosition(this.typeNumber),b=0;b<a.length;b++)for(var k=0;k<a.length;k++){var l=a[b],q=a[k];if(null==this.modules[l][q])for(var y=-2;2>=y;y++)for(var C=-2;2>=C;C++)this.modules[l+y][q+C]=-2==y||2==y||-2==C||2==C||0==y&&0==C?!0:!1}},setupTypeNumber:function(a){for(var b=f.getBCHTypeNumber(this.typeNumber),k=0;18>k;k++){var l=!a&&1==(b>>k&1);this.modules[Math.floor(k/3)][k%3+this.moduleCount-
8-3]=l}for(k=0;18>k;k++)l=!a&&1==(b>>k&1),this.modules[k%3+this.moduleCount-8-3][Math.floor(k/3)]=l},setupTypeInfo:function(a,b){b=f.getBCHTypeInfo(this.errorCorrectLevel<<3|b);for(var k=0;15>k;k++){var l=!a&&1==(b>>k&1);6>k?this.modules[k][8]=l:8>k?this.modules[k+1][8]=l:this.modules[this.moduleCount-15+k][8]=l}for(k=0;15>k;k++)l=!a&&1==(b>>k&1),8>k?this.modules[8][this.moduleCount-k-1]=l:9>k?this.modules[8][15-k-1+1]=l:this.modules[8][15-k-1]=l;this.modules[this.moduleCount-8][8]=!a},mapData:function(a,
b){for(var k=-1,l=this.moduleCount-1,q=7,y=0,C=this.moduleCount-1;0<C;C-=2)for(6==C&&C--;;){for(var v=0;2>v;v++)if(null==this.modules[l][C-v]){var H=!1;y<a.length&&(H=1==(a[y]>>>q&1));f.getMask(b,l,C-v)&&(H=!H);this.modules[l][C-v]=H;q--;-1==q&&(y++,q=7)}l+=k;if(0>l||this.moduleCount<=l){l-=k;k=-k;break}}}};r.PAD0=236;r.PAD1=17;r.createData=function(a,b,k){b=F.getRSBlocks(a,b);for(var l=new t,q=0;q<k.length;q++){var y=k[q];l.put(y.mode,4);l.put(y.getLength(),f.getLengthInBits(y.mode,a));y.write(l)}for(q=
a=0;q<b.length;q++)a+=b[q].dataCount;if(l.getLengthInBits()>8*a)throw Error("code length overflow. ("+l.getLengthInBits()+"\x3e"+8*a+")");for(l.getLengthInBits()+4<=8*a&&l.put(0,4);0!=l.getLengthInBits()%8;)l.putBit(!1);for(;!(l.getLengthInBits()>=8*a);){l.put(r.PAD0,8);if(l.getLengthInBits()>=8*a)break;l.put(r.PAD1,8)}return r.createBytes(l,b)};r.createBytes=function(a,b){for(var k=0,l=0,q=0,y=Array(b.length),C=Array(b.length),v=0;v<b.length;v++){var H=b[v].dataCount,P=b[v].totalCount-H;l=Math.max(l,
H);q=Math.max(q,P);y[v]=Array(H);for(var M=0;M<y[v].length;M++)y[v][M]=255&a.buffer[M+k];k+=H;M=f.getErrorCorrectPolynomial(P);H=(new A(y[v],M.getLength()-1)).mod(M);C[v]=Array(M.getLength()-1);for(M=0;M<C[v].length;M++)P=M+H.getLength()-C[v].length,C[v][M]=0<=P?H.get(P):0}for(M=v=0;M<b.length;M++)v+=b[M].totalCount;a=Array(v);for(M=k=0;M<l;M++)for(v=0;v<b.length;v++)M<y[v].length&&(a[k++]=y[v][M]);for(M=0;M<q;M++)for(v=0;v<b.length;v++)M<C[v].length&&(a[k++]=C[v][M]);return a};for(var u={MODE_NUMBER:1,
MODE_ALPHA_NUM:2,MODE_8BIT_BYTE:4,MODE_KANJI:8},g={L:1,M:0,Q:3,H:2},f={PATTERN_POSITION_TABLE:[[],[6,18],[6,22],[6,26],[6,30],[6,34],[6,22,38],[6,24,42],[6,26,46],[6,28,50],[6,30,54],[6,32,58],[6,34,62],[6,26,46,66],[6,26,48,70],[6,26,50,74],[6,30,54,78],[6,30,56,82],[6,30,58,86],[6,34,62,90],[6,28,50,72,94],[6,26,50,74,98],[6,30,54,78,102],[6,28,54,80,106],[6,32,58,84,110],[6,30,58,86,114],[6,34,62,90,118],[6,26,50,74,98,122],[6,30,54,78,102,126],[6,26,52,78,104,130],[6,30,56,82,108,134],[6,34,60,
86,112,138],[6,30,58,86,114,142],[6,34,62,90,118,146],[6,30,54,78,102,126,150],[6,24,50,76,102,128,154],[6,28,54,80,106,132,158],[6,32,58,84,110,136,162],[6,26,54,82,110,138,166],[6,30,58,86,114,142,170]],G15:1335,G18:7973,G15_MASK:21522,getBCHTypeInfo:function(a){for(var b=a<<10;0<=f.getBCHDigit(b)-f.getBCHDigit(f.G15);)b^=f.G15<<f.getBCHDigit(b)-f.getBCHDigit(f.G15);return(a<<10|b)^f.G15_MASK},getBCHTypeNumber:function(a){for(var b=a<<12;0<=f.getBCHDigit(b)-f.getBCHDigit(f.G18);)b^=f.G18<<f.getBCHDigit(b)-
f.getBCHDigit(f.G18);return a<<12|b},getBCHDigit:function(a){for(var b=0;0!=a;)b++,a>>>=1;return b},getPatternPosition:function(a){return f.PATTERN_POSITION_TABLE[a-1]},getMask:function(a,b,k){switch(a){case 0:return 0==(b+k)%2;case 1:return 0==b%2;case 2:return 0==k%3;case 3:return 0==(b+k)%3;case 4:return 0==(Math.floor(b/2)+Math.floor(k/3))%2;case 5:return 0==b*k%2+b*k%3;case 6:return 0==(b*k%2+b*k%3)%2;case 7:return 0==(b*k%3+(b+k)%2)%2;default:throw Error("bad maskPattern:"+a);}},getErrorCorrectPolynomial:function(a){for(var b=
new A([1],0),k=0;k<a;k++)b=b.multiply(new A([1,c.gexp(k)],0));return b},getLengthInBits:function(a,b){if(1<=b&&10>b)switch(a){case u.MODE_NUMBER:return 10;case u.MODE_ALPHA_NUM:return 9;case u.MODE_8BIT_BYTE:return 8;case u.MODE_KANJI:return 8;default:throw Error("mode:"+a);}else if(27>b)switch(a){case u.MODE_NUMBER:return 12;case u.MODE_ALPHA_NUM:return 11;case u.MODE_8BIT_BYTE:return 16;case u.MODE_KANJI:return 10;default:throw Error("mode:"+a);}else if(41>b)switch(a){case u.MODE_NUMBER:return 14;
case u.MODE_ALPHA_NUM:return 13;case u.MODE_8BIT_BYTE:return 16;case u.MODE_KANJI:return 12;default:throw Error("mode:"+a);}else throw Error("type:"+b);},getLostPoint:function(a){for(var b=a.getModuleCount(),k=0,l=0;l<b;l++)for(var q=0;q<b;q++){for(var y=0,C=a.isDark(l,q),v=-1;1>=v;v++)if(!(0>l+v||b<=l+v))for(var H=-1;1>=H;H++)0>q+H||b<=q+H||(0!=v||0!=H)&&C==a.isDark(l+v,q+H)&&y++;5<y&&(k+=3+y-5)}for(l=0;l<b-1;l++)for(q=0;q<b-1;q++)if(y=0,a.isDark(l,q)&&y++,a.isDark(l+1,q)&&y++,a.isDark(l,q+1)&&y++,
a.isDark(l+1,q+1)&&y++,0==y||4==y)k+=3;for(l=0;l<b;l++)for(q=0;q<b-6;q++)a.isDark(l,q)&&!a.isDark(l,q+1)&&a.isDark(l,q+2)&&a.isDark(l,q+3)&&a.isDark(l,q+4)&&!a.isDark(l,q+5)&&a.isDark(l,q+6)&&(k+=40);for(q=0;q<b;q++)for(l=0;l<b-6;l++)a.isDark(l,q)&&!a.isDark(l+1,q)&&a.isDark(l+2,q)&&a.isDark(l+3,q)&&a.isDark(l+4,q)&&!a.isDark(l+5,q)&&a.isDark(l+6,q)&&(k+=40);for(q=y=0;q<b;q++)for(l=0;l<b;l++)a.isDark(l,q)&&y++;return k+Math.abs(100*y/b/b-50)/5*10}},c={glog:function(a){if(1>a)throw Error("glog("+a+
")");return c.LOG_TABLE[a]},gexp:function(a){for(;0>a;)a+=255;for(;256<=a;)a-=255;return c.EXP_TABLE[a]},EXP_TABLE:Array(256),LOG_TABLE:Array(256)},d=0;8>d;d++)c.EXP_TABLE[d]=1<<d;for(d=8;256>d;d++)c.EXP_TABLE[d]=c.EXP_TABLE[d-4]^c.EXP_TABLE[d-5]^c.EXP_TABLE[d-6]^c.EXP_TABLE[d-8];for(d=0;255>d;d++)c.LOG_TABLE[c.EXP_TABLE[d]]=d;A.prototype={get:function(a){return this.num[a]},getLength:function(){return this.num.length},multiply:function(a){for(var b=Array(this.getLength()+a.getLength()-1),k=0;k<this.getLength();k++)for(var l=
0;l<a.getLength();l++)b[k+l]^=c.gexp(c.glog(this.get(k))+c.glog(a.get(l)));return new A(b,0)},mod:function(a){if(0>this.getLength()-a.getLength())return this;for(var b=c.glog(this.get(0))-c.glog(a.get(0)),k=Array(this.getLength()),l=0;l<this.getLength();l++)k[l]=this.get(l);for(l=0;l<a.getLength();l++)k[l]^=c.gexp(c.glog(a.get(l))+b);return(new A(k,0)).mod(a)}};F.RS_BLOCK_TABLE=[[1,26,19],[1,26,16],[1,26,13],[1,26,9],[1,44,34],[1,44,28],[1,44,22],[1,44,16],[1,70,55],[1,70,44],[2,35,17],[2,35,13],
[1,100,80],[2,50,32],[2,50,24],[4,25,9],[1,134,108],[2,67,43],[2,33,15,2,34,16],[2,33,11,2,34,12],[2,86,68],[4,43,27],[4,43,19],[4,43,15],[2,98,78],[4,49,31],[2,32,14,4,33,15],[4,39,13,1,40,14],[2,121,97],[2,60,38,2,61,39],[4,40,18,2,41,19],[4,40,14,2,41,15],[2,146,116],[3,58,36,2,59,37],[4,36,16,4,37,17],[4,36,12,4,37,13],[2,86,68,2,87,69],[4,69,43,1,70,44],[6,43,19,2,44,20],[6,43,15,2,44,16],[4,101,81],[1,80,50,4,81,51],[4,50,22,4,51,23],[3,36,12,8,37,13],[2,116,92,2,117,93],[6,58,36,2,59,37],[4,
46,20,6,47,21],[7,42,14,4,43,15],[4,133,107],[8,59,37,1,60,38],[8,44,20,4,45,21],[12,33,11,4,34,12],[3,145,115,1,146,116],[4,64,40,5,65,41],[11,36,16,5,37,17],[11,36,12,5,37,13],[5,109,87,1,110,88],[5,65,41,5,66,42],[5,54,24,7,55,25],[11,36,12],[5,122,98,1,123,99],[7,73,45,3,74,46],[15,43,19,2,44,20],[3,45,15,13,46,16],[1,135,107,5,136,108],[10,74,46,1,75,47],[1,50,22,15,51,23],[2,42,14,17,43,15],[5,150,120,1,151,121],[9,69,43,4,70,44],[17,50,22,1,51,23],[2,42,14,19,43,15],[3,141,113,4,142,114],[3,
70,44,11,71,45],[17,47,21,4,48,22],[9,39,13,16,40,14],[3,135,107,5,136,108],[3,67,41,13,68,42],[15,54,24,5,55,25],[15,43,15,10,44,16],[4,144,116,4,145,117],[17,68,42],[17,50,22,6,51,23],[19,46,16,6,47,17],[2,139,111,7,140,112],[17,74,46],[7,54,24,16,55,25],[34,37,13],[4,151,121,5,152,122],[4,75,47,14,76,48],[11,54,24,14,55,25],[16,45,15,14,46,16],[6,147,117,4,148,118],[6,73,45,14,74,46],[11,54,24,16,55,25],[30,46,16,2,47,17],[8,132,106,4,133,107],[8,75,47,13,76,48],[7,54,24,22,55,25],[22,45,15,13,
46,16],[10,142,114,2,143,115],[19,74,46,4,75,47],[28,50,22,6,51,23],[33,46,16,4,47,17],[8,152,122,4,153,123],[22,73,45,3,74,46],[8,53,23,26,54,24],[12,45,15,28,46,16],[3,147,117,10,148,118],[3,73,45,23,74,46],[4,54,24,31,55,25],[11,45,15,31,46,16],[7,146,116,7,147,117],[21,73,45,7,74,46],[1,53,23,37,54,24],[19,45,15,26,46,16],[5,145,115,10,146,116],[19,75,47,10,76,48],[15,54,24,25,55,25],[23,45,15,25,46,16],[13,145,115,3,146,116],[2,74,46,29,75,47],[42,54,24,1,55,25],[23,45,15,28,46,16],[17,145,115],
[10,74,46,23,75,47],[10,54,24,35,55,25],[19,45,15,35,46,16],[17,145,115,1,146,116],[14,74,46,21,75,47],[29,54,24,19,55,25],[11,45,15,46,46,16],[13,145,115,6,146,116],[14,74,46,23,75,47],[44,54,24,7,55,25],[59,46,16,1,47,17],[12,151,121,7,152,122],[12,75,47,26,76,48],[39,54,24,14,55,25],[22,45,15,41,46,16],[6,151,121,14,152,122],[6,75,47,34,76,48],[46,54,24,10,55,25],[2,45,15,64,46,16],[17,152,122,4,153,123],[29,74,46,14,75,47],[49,54,24,10,55,25],[24,45,15,46,46,16],[4,152,122,18,153,123],[13,74,
46,32,75,47],[48,54,24,14,55,25],[42,45,15,32,46,16],[20,147,117,4,148,118],[40,75,47,7,76,48],[43,54,24,22,55,25],[10,45,15,67,46,16],[19,148,118,6,149,119],[18,75,47,31,76,48],[34,54,24,34,55,25],[20,45,15,61,46,16]];F.getRSBlocks=function(a,b){var k=F.getRsBlockTable(a,b);if(void 0==k)throw Error("bad rs block @ typeNumber:"+a+"/errorCorrectLevel:"+b);a=k.length/3;b=[];for(var l=0;l<a;l++)for(var q=k[3*l],y=k[3*l+1],C=k[3*l+2],v=0;v<q;v++)b.push(new F(y,C));return b};F.getRsBlockTable=function(a,
b){switch(b){case g.L:return F.RS_BLOCK_TABLE[4*(a-1)];case g.M:return F.RS_BLOCK_TABLE[4*(a-1)+1];case g.Q:return F.RS_BLOCK_TABLE[4*(a-1)+2];case g.H:return F.RS_BLOCK_TABLE[4*(a-1)+3]}};t.prototype={get:function(a){return 1==(this.buffer[Math.floor(a/8)]>>>7-a%8&1)},put:function(a,b){for(var k=0;k<b;k++)this.putBit(1==(a>>>b-k-1&1))},getLengthInBits:function(){return this.length},putBit:function(a){var b=Math.floor(this.length/8);this.buffer.length<=b&&this.buffer.push(0);a&&(this.buffer[b]|=128>>>
this.length%8);this.length++}};var e=[[17,14,11,7],[32,26,20,14],[53,42,32,24],[78,62,46,34],[106,84,60,44],[134,106,74,58],[154,122,86,64],[192,152,108,84],[230,180,130,98],[271,213,151,119],[321,251,177,137],[367,287,203,155],[425,331,241,177],[458,362,258,194],[520,412,292,220],[586,450,322,250],[644,504,364,280],[718,560,394,310],[792,624,442,338],[858,666,482,382],[929,711,509,403],[1003,779,565,439],[1091,857,611,461],[1171,911,661,511],[1273,997,715,535],[1367,1059,751,593],[1465,1125,805,
625],[1528,1190,868,658],[1628,1264,908,698],[1732,1370,982,742],[1840,1452,1030,790],[1952,1538,1112,842],[2068,1628,1168,898],[2188,1722,1228,958],[2303,1809,1283,983],[2431,1911,1351,1051],[2563,1989,1423,1093],[2699,2099,1499,1139],[2809,2213,1579,1219],[2953,2331,1663,1273]];d=function(){var a=function(b,k){this._el=b;this._htOption=k};a.prototype.draw=function(b){function k(H,P){H=document.createElementNS("http://www.w3.org/2000/svg",H);for(var M in P)P.hasOwnProperty(M)&&H.setAttribute(M,P[M]);
return H}var l=this._htOption,q=this._el,y=b.getModuleCount();this.clear();var C=k("svg",{viewBox:"0 0 "+String(y)+" "+String(y),width:"100%",height:"100%",fill:l.colorLight});C.setAttributeNS("http://www.w3.org/2000/xmlns/","xmlns:xlink","http://www.w3.org/1999/xlink");q.appendChild(C);C.appendChild(k("rect",{fill:l.colorDark,width:"1",height:"1",id:"template"}));for(l=0;l<y;l++)for(q=0;q<y;q++)if(b.isDark(l,q)){var v=k("use",{x:String(l),y:String(q)});v.setAttributeNS("http://www.w3.org/1999/xlink",
"href","#template");C.appendChild(v)}};a.prototype.clear=function(){for(;this._el.hasChildNodes();)this._el.removeChild(this._el.lastChild)};return a}();var m="svg"===document.documentElement.tagName.toLowerCase()?d:"undefined"==typeof CanvasRenderingContext2D?function(){var a=function(b,k){this._el=b;this._htOption=k};a.prototype.draw=function(b){for(var k=this._htOption,l=this._el,q=b.getModuleCount(),y=Math.floor(k.width/q),C=Math.floor(k.height/q),v=['\x3ctable style\x3d"border:0;border-collapse:collapse;"\x3e'],
H=0;H<q;H++){v.push("\x3ctr\x3e");for(var P=0;P<q;P++)v.push('\x3ctd style\x3d"border:0;border-collapse:collapse;padding:0;margin:0;width:'+y+"px;height:"+C+"px;background-color:"+(b.isDark(H,P)?k.colorDark:k.colorLight)+';"\x3e\x3c/td\x3e');v.push("\x3c/tr\x3e")}v.push("\x3c/table\x3e");l.innerHTML=v.join("");b=l.childNodes[0];l=(k.width-b.offsetWidth)/2;k=(k.height-b.offsetHeight)/2;0<l&&0<k&&(b.style.margin=k+"px "+l+"px")};a.prototype.clear=function(){this._el.innerHTML=""};return a}():function(){function a(){this._elImage.src=
this._elCanvas.toDataURL("image/png");this._elImage.style.display="block";this._elCanvas.style.display="none"}function b(y,C){var v=this;v._fFail=C;v._fSuccess=y;null===v._bSupportDataURI?(y=document.createElement("img"),C=function(){v._bSupportDataURI=!1;v._fFail&&_fFail.call(v)},y.onabort=C,y.onerror=C,y.onload=function(){v._bSupportDataURI=!0;v._fSuccess&&v._fSuccess.call(v)},y.src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg\x3d\x3d"):
!0===v._bSupportDataURI&&v._fSuccess?v._fSuccess.call(v):!1===v._bSupportDataURI&&v._fFail&&v._fFail.call(v)}if(this._android&&2.1>=this._android){var k=1/window.devicePixelRatio,l=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(y,C,v,H,P,M,aa,Z,da){if("nodeName"in y&&/img/i.test(y.nodeName))for(var R=arguments.length-1;1<=R;R--)arguments[R]*=k;else"undefined"==typeof Z&&(arguments[1]*=k,arguments[2]*=k,arguments[3]*=k,arguments[4]*=k);l.apply(this,
arguments)}}var q=function(y,C){this._bIsPainted=!1;this._android=w();this._htOption=C;this._elCanvas=document.createElement("canvas");this._elCanvas.width=C.width;this._elCanvas.height=C.height;y.appendChild(this._elCanvas);this._el=y;this._oContext=this._elCanvas.getContext("2d");this._bIsPainted=!1;this._elImage=document.createElement("img");this._elImage.alt="Scan me!";this._elImage.style.display="none";this._el.appendChild(this._elImage);this._bSupportDataURI=null};q.prototype.draw=function(y){var C=
this._elImage,v=this._oContext,H=this._htOption,P=y.getModuleCount(),M=H.width/P,aa=H.height/P,Z=Math.round(M),da=Math.round(aa);C.style.display="none";this.clear();for(C=0;C<P;C++)for(var R=0;R<P;R++){var ea=y.isDark(C,R),fa=R*M,ba=C*aa;v.strokeStyle=ea?H.colorDark:H.colorLight;v.lineWidth=1;v.fillStyle=ea?H.colorDark:H.colorLight;v.fillRect(fa,ba,M,aa);v.strokeRect(Math.floor(fa)+.5,Math.floor(ba)+.5,Z,da);v.strokeRect(Math.ceil(fa)-.5,Math.ceil(ba)-.5,Z,da)}this._bIsPainted=!0};q.prototype.makeImage=
function(){this._bIsPainted&&b.call(this,a)};q.prototype.isPainted=function(){return this._bIsPainted};q.prototype.clear=function(){this._oContext.clearRect(0,0,this._elCanvas.width,this._elCanvas.height);this._bIsPainted=!1};q.prototype.round=function(y){return y?Math.floor(1E3*y)/1E3:y};return q}();K=function(a,b){this._htOption={width:256,height:256,typeNumber:4,colorDark:"#000000",colorLight:"#ffffff",correctLevel:g.H};"string"===typeof b&&(b={text:b});if(b)for(var k in b)this._htOption[k]=b[k];
"string"==typeof a&&(a=document.getElementById(a));this._android=w();this._el=a;this._oQRCode=null;this._oDrawing=new m(this._el,this._htOption);this._htOption.text&&this.makeCode(this._htOption.text)};K.prototype.makeCode=function(a){var b=this._htOption.correctLevel,k=1;var l=encodeURI(a).toString().replace(/%[0-9a-fA-F]{2}/g,"a");l=l.length+(l.length!=a?3:0);for(var q=0,y=e.length;q<=y;q++){var C=0;switch(b){case g.L:C=e[q][0];break;case g.M:C=e[q][1];break;case g.Q:C=e[q][2];break;case g.H:C=
e[q][3]}if(l<=C)break;else k++}if(k>e.length)throw Error("Too long data");this._oQRCode=new r(k,this._htOption.correctLevel);this._oQRCode.addData(a);this._oQRCode.make();this._el.title=a;this._oDrawing.draw(this._oQRCode);this.makeImage()};K.prototype.makeImage=function(){"function"==typeof this._oDrawing.makeImage&&(!this._android||3<=this._android)&&this._oDrawing.makeImage()};K.prototype.clear=function(){this._oDrawing.clear()};K.CorrectLevel=g;window.QRCode=K})()})},"libs/arcgis-html-sanitizer/arcgis-html-sanitizer":function(){!function(Q,
z){"object"==typeof exports&&"undefined"!=typeof module?module.exports=z():"function"==typeof define&&define.amd?define(z):(Q=Q||self).Sanitizer=z()}(this,function(){function Q(h,n){return h(n={exports:{}},n.exports),n.exports}function z(){return{"align-content":!1,"align-items":!1,"align-self":!1,"alignment-adjust":!1,"alignment-baseline":!1,all:!1,"anchor-point":!1,animation:!1,"animation-delay":!1,"animation-direction":!1,"animation-duration":!1,"animation-fill-mode":!1,"animation-iteration-count":!1,
"animation-name":!1,"animation-play-state":!1,"animation-timing-function":!1,azimuth:!1,"backface-visibility":!1,background:!0,"background-attachment":!0,"background-clip":!0,"background-color":!0,"background-image":!0,"background-origin":!0,"background-position":!0,"background-repeat":!0,"background-size":!0,"baseline-shift":!1,binding:!1,bleed:!1,"bookmark-label":!1,"bookmark-level":!1,"bookmark-state":!1,border:!0,"border-bottom":!0,"border-bottom-color":!0,"border-bottom-left-radius":!0,"border-bottom-right-radius":!0,
"border-bottom-style":!0,"border-bottom-width":!0,"border-collapse":!0,"border-color":!0,"border-image":!0,"border-image-outset":!0,"border-image-repeat":!0,"border-image-slice":!0,"border-image-source":!0,"border-image-width":!0,"border-left":!0,"border-left-color":!0,"border-left-style":!0,"border-left-width":!0,"border-radius":!0,"border-right":!0,"border-right-color":!0,"border-right-style":!0,"border-right-width":!0,"border-spacing":!0,"border-style":!0,"border-top":!0,"border-top-color":!0,
"border-top-left-radius":!0,"border-top-right-radius":!0,"border-top-style":!0,"border-top-width":!0,"border-width":!0,bottom:!1,"box-decoration-break":!0,"box-shadow":!0,"box-sizing":!0,"box-snap":!0,"box-suppress":!0,"break-after":!0,"break-before":!0,"break-inside":!0,"caption-side":!1,chains:!1,clear:!0,clip:!1,"clip-path":!1,"clip-rule":!1,color:!0,"color-interpolation-filters":!0,"column-count":!1,"column-fill":!1,"column-gap":!1,"column-rule":!1,"column-rule-color":!1,"column-rule-style":!1,
"column-rule-width":!1,"column-span":!1,"column-width":!1,columns:!1,contain:!1,content:!1,"counter-increment":!1,"counter-reset":!1,"counter-set":!1,crop:!1,cue:!1,"cue-after":!1,"cue-before":!1,cursor:!1,direction:!1,display:!0,"display-inside":!0,"display-list":!0,"display-outside":!0,"dominant-baseline":!1,elevation:!1,"empty-cells":!1,filter:!1,flex:!1,"flex-basis":!1,"flex-direction":!1,"flex-flow":!1,"flex-grow":!1,"flex-shrink":!1,"flex-wrap":!1,float:!1,"float-offset":!1,"flood-color":!1,
"flood-opacity":!1,"flow-from":!1,"flow-into":!1,font:!0,"font-family":!0,"font-feature-settings":!0,"font-kerning":!0,"font-language-override":!0,"font-size":!0,"font-size-adjust":!0,"font-stretch":!0,"font-style":!0,"font-synthesis":!0,"font-variant":!0,"font-variant-alternates":!0,"font-variant-caps":!0,"font-variant-east-asian":!0,"font-variant-ligatures":!0,"font-variant-numeric":!0,"font-variant-position":!0,"font-weight":!0,grid:!1,"grid-area":!1,"grid-auto-columns":!1,"grid-auto-flow":!1,
"grid-auto-rows":!1,"grid-column":!1,"grid-column-end":!1,"grid-column-start":!1,"grid-row":!1,"grid-row-end":!1,"grid-row-start":!1,"grid-template":!1,"grid-template-areas":!1,"grid-template-columns":!1,"grid-template-rows":!1,"hanging-punctuation":!1,height:!0,hyphens:!1,icon:!1,"image-orientation":!1,"image-resolution":!1,"ime-mode":!1,"initial-letters":!1,"inline-box-align":!1,"justify-content":!1,"justify-items":!1,"justify-self":!1,left:!1,"letter-spacing":!0,"lighting-color":!0,"line-box-contain":!1,
"line-break":!1,"line-grid":!1,"line-height":!1,"line-snap":!1,"line-stacking":!1,"line-stacking-ruby":!1,"line-stacking-shift":!1,"line-stacking-strategy":!1,"list-style":!0,"list-style-image":!0,"list-style-position":!0,"list-style-type":!0,margin:!0,"margin-bottom":!0,"margin-left":!0,"margin-right":!0,"margin-top":!0,"marker-offset":!1,"marker-side":!1,marks:!1,mask:!1,"mask-box":!1,"mask-box-outset":!1,"mask-box-repeat":!1,"mask-box-slice":!1,"mask-box-source":!1,"mask-box-width":!1,"mask-clip":!1,
"mask-image":!1,"mask-origin":!1,"mask-position":!1,"mask-repeat":!1,"mask-size":!1,"mask-source-type":!1,"mask-type":!1,"max-height":!0,"max-lines":!1,"max-width":!0,"min-height":!0,"min-width":!0,"move-to":!1,"nav-down":!1,"nav-index":!1,"nav-left":!1,"nav-right":!1,"nav-up":!1,"object-fit":!1,"object-position":!1,opacity:!1,order:!1,orphans:!1,outline:!1,"outline-color":!1,"outline-offset":!1,"outline-style":!1,"outline-width":!1,overflow:!1,"overflow-wrap":!1,"overflow-x":!1,"overflow-y":!1,padding:!0,
"padding-bottom":!0,"padding-left":!0,"padding-right":!0,"padding-top":!0,page:!1,"page-break-after":!1,"page-break-before":!1,"page-break-inside":!1,"page-policy":!1,pause:!1,"pause-after":!1,"pause-before":!1,perspective:!1,"perspective-origin":!1,pitch:!1,"pitch-range":!1,"play-during":!1,position:!1,"presentation-level":!1,quotes:!1,"region-fragment":!1,resize:!1,rest:!1,"rest-after":!1,"rest-before":!1,richness:!1,right:!1,rotation:!1,"rotation-point":!1,"ruby-align":!1,"ruby-merge":!1,"ruby-position":!1,
"shape-image-threshold":!1,"shape-outside":!1,"shape-margin":!1,size:!1,speak:!1,"speak-as":!1,"speak-header":!1,"speak-numeral":!1,"speak-punctuation":!1,"speech-rate":!1,stress:!1,"string-set":!1,"tab-size":!1,"table-layout":!1,"text-align":!0,"text-align-last":!0,"text-combine-upright":!0,"text-decoration":!0,"text-decoration-color":!0,"text-decoration-line":!0,"text-decoration-skip":!0,"text-decoration-style":!0,"text-emphasis":!0,"text-emphasis-color":!0,"text-emphasis-position":!0,"text-emphasis-style":!0,
"text-height":!0,"text-indent":!0,"text-justify":!0,"text-orientation":!0,"text-overflow":!0,"text-shadow":!0,"text-space-collapse":!0,"text-transform":!0,"text-underline-position":!0,"text-wrap":!0,top:!1,transform:!1,"transform-origin":!1,"transform-style":!1,transition:!1,"transition-delay":!1,"transition-duration":!1,"transition-property":!1,"transition-timing-function":!1,"unicode-bidi":!1,"vertical-align":!1,visibility:!1,"voice-balance":!1,"voice-duration":!1,"voice-family":!1,"voice-pitch":!1,
"voice-range":!1,"voice-rate":!1,"voice-stress":!1,"voice-volume":!1,volume:!1,"white-space":!1,widows:!1,width:!0,"will-change":!1,"word-break":!0,"word-spacing":!0,"word-wrap":!0,"wrap-flow":!1,"wrap-through":!1,"writing-mode":!1,"z-index":!1}}function J(h){var n=h||{},p={},x;for(x in n)p[x]=n[x];(h=p).whiteList=h.whiteList||H.whiteList;h.onAttr=h.onAttr||H.onAttr;h.onIgnoreAttr=h.onIgnoreAttr||H.onIgnoreAttr;h.safeAttrValue=h.safeAttrValue||H.safeAttrValue;this.options=h}function K(h){return h.replace(na,
"\x26lt;").replace(oa,"\x26gt;")}function D(h){return h.replace(pa,"\x26quot;")}function r(h){return h.replace(qa,'"')}function A(h){return h.replace(ra,function(n,p){return"x"===p[0]||"X"===p[0]?String.fromCharCode(parseInt(p.substr(1),16)):String.fromCharCode(parseInt(p,10))})}function F(h){return h.replace(sa,":").replace(ta," ")}function t(h){for(var n="",p=0,x=h.length;p<x;p++)n+=32>h.charCodeAt(p)?" ":h.charAt(p);return R(n)}function w(h){return h=t(h=F(h=A(h=r(h))))}function u(h){return h=
K(h=D(h))}function g(h,n){for(;n<h.length;n++){var p=h[n];if(" "!==p)return"\x3d"===p?n:-1}}function f(h,n){for(;0<n;n--){var p=h[n];if(" "!==p)return"\x3d"===p?n:-1}}function c(h){return'"'===h[0]&&'"'===h[h.length-1]||"'"===h[0]&&"'"===h[h.length-1]?h.substr(1,h.length-2):h}function d(h){var n=h||{},p={},x;for(x in n)p[x]=n[x];(h=p).stripIgnoreTag&&(h.onIgnoreTag&&console.error('Notes: cannot use these two options "stripIgnoreTag" and "onIgnoreTag" at the same time'),h.onIgnoreTag=W.onIgnoreTagStripAll);
h.whiteList=h.whiteList||W.whiteList;h.onTag=h.onTag||W.onTag;h.onTagAttr=h.onTagAttr||W.onTagAttr;h.onIgnoreTag=h.onIgnoreTag||W.onIgnoreTag;h.onIgnoreTagAttr=h.onIgnoreTagAttr||W.onIgnoreTagAttr;h.safeAttrValue=h.safeAttrValue||W.safeAttrValue;h.escapeHtml=h.escapeHtml||W.escapeHtml;this.options=h;!1===h.css?this.cssFilter=!1:(h.css=h.css||{},this.cssFilter=new ua(h.css))}var e,m,a=Object.prototype,b=Function.prototype.toString,k=a.hasOwnProperty,l=b.call(Object),q=a.toString,y=(e=Object.getPrototypeOf,
m=Object,function(h){return e(m(h))}),C=function(h){var n;if(!(n=!h||"object"!=typeof h||"[object Object]"!=q.call(h))&&(n=!1,null!=h&&"function"!=typeof h.toString))try{n=!!(h+"")}catch(p){}if(n)return!1;h=y(h);if(null===h)return!0;h=k.call(h,"constructor")&&h.constructor;return"function"==typeof h&&h instanceof h&&b.call(h)==l},v=/javascript\s*:/gim,H={whiteList:z(),getDefaultWhiteList:z,onAttr:function(h,n,p){},onIgnoreAttr:function(h,n,p){},safeAttrValue:function(h,n){return v.test(n)?"":n}},
P=function(h){return String.prototype.trim?h.trim():h.replace(/(^\s*)|(\s*$)/g,"")},M=function(h){return String.prototype.trimRight?h.trimRight():h.replace(/(\s*$)/g,"")},aa=function(h,n){function p(){if(!B){var N=P(h.slice(G,L)),O=N.indexOf(":");if(-1!==O){var S=P(N.slice(0,O));O=P(N.slice(O+1));S&&(N=n(G,E.length,S,O,N))&&(E+=N+"; ")}}G=L+1}";"!==(h=M(h))[h.length-1]&&(h+=";");for(var x=h.length,B=!1,G=0,L=0,E="";L<x;L++){var I=h[L];if("/"===I&&"*"===h[L+1]){I=h.indexOf("*/",L+2);if(-1===I)break;
G=(L=I+1)+1;B=!1}else"("===I?B=!0:")"===I?B=!1:";"===I?B||p():"\n"===I&&p()}return P(E)};J.prototype.process=function(h){if(!(h=(h=h||"").toString()))return"";var n=this.options,p=n.whiteList,x=n.onAttr,B=n.onIgnoreAttr,G=n.safeAttrValue;return aa(h,function(L,E,I,N,O){var S=p[I],T=!1;if(!0===S?T=S:"function"==typeof S?T=S(N):S instanceof RegExp&&(T=S.test(N)),!0!==T&&(T=!1),N=G(I,N)){var V;L={position:E,sourcePosition:L,source:O,isWhite:T};return T?null==(V=x(I,N,L))?I+":"+N:V:null==(V=B(I,N,L))?
void 0:V}})};a=Q(function(h,n){for(var p in(n=h.exports=function(x,B){return(new J(B)).process(x)}).FilterCSS=J,H)n[p]=H[p]});var Z=(a.FilterCSS,function(h,n){var p;if(Array.prototype.indexOf)return h.indexOf(n);var x=0;for(p=h.length;x<p;x++)if(h[x]===n)return x;return-1}),da=function(h,n,p){var x;if(Array.prototype.forEach)return h.forEach(n,p);var B=0;for(x=h.length;B<x;B++)n.call(p,h[B],B,h)},R=function(h){return String.prototype.trim?h.trim():h.replace(/(^\s*)|(\s*$)/g,"")},ea=function(h){return(h=
/\s|\n|\t/.exec(h))?h.index:-1},fa=a.getDefaultWhiteList,ba=new a.FilterCSS,na=/</g,oa=/>/g,pa=/"/g,qa=/&quot;/g,ra=/&#([a-zA-Z0-9]*);?/gim,sa=/&colon;?/gim,ta=/&newline;?/gim,ha=/((j\s*a\s*v\s*a|v\s*b|l\s*i\s*v\s*e)\s*s\s*c\s*r\s*i\s*p\s*t\s*|m\s*o\s*c\s*h\s*a):/gi,la=/e\s*x\s*p\s*r\s*e\s*s\s*s\s*i\s*o\s*n\s*\(.*/gi,ma=/u\s*r\s*l\s*\(.*/gi,va=/\x3c!--[\s\S]*?--\x3e/g,W={whiteList:{a:["target","href","title"],abbr:["title"],address:[],area:["shape","coords","href","alt"],article:[],aside:[],audio:["autoplay",
"controls","loop","preload","src"],b:[],bdi:["dir"],bdo:["dir"],big:[],blockquote:["cite"],br:[],caption:[],center:[],cite:[],code:[],col:["align","valign","span","width"],colgroup:["align","valign","span","width"],dd:[],del:["datetime"],details:["open"],div:[],dl:[],dt:[],em:[],font:["color","size","face"],footer:[],h1:[],h2:[],h3:[],h4:[],h5:[],h6:[],header:[],hr:[],i:[],img:["src","alt","title","width","height"],ins:["datetime"],li:[],mark:[],nav:[],ol:[],p:[],pre:[],s:[],section:[],small:[],span:[],
sub:[],sup:[],strong:[],table:["width","border","align","valign"],tbody:["align","valign"],td:["width","rowspan","colspan","align","valign"],tfoot:["align","valign"],th:["width","rowspan","colspan","align","valign"],thead:["align","valign"],tr:["rowspan","align","valign"],tt:[],u:[],ul:[],video:"autoplay controls loop preload src height width".split(" ")},getDefaultWhiteList:function(){return{a:["target","href","title"],abbr:["title"],address:[],area:["shape","coords","href","alt"],article:[],aside:[],
audio:["autoplay","controls","loop","preload","src"],b:[],bdi:["dir"],bdo:["dir"],big:[],blockquote:["cite"],br:[],caption:[],center:[],cite:[],code:[],col:["align","valign","span","width"],colgroup:["align","valign","span","width"],dd:[],del:["datetime"],details:["open"],div:[],dl:[],dt:[],em:[],font:["color","size","face"],footer:[],h1:[],h2:[],h3:[],h4:[],h5:[],h6:[],header:[],hr:[],i:[],img:["src","alt","title","width","height"],ins:["datetime"],li:[],mark:[],nav:[],ol:[],p:[],pre:[],s:[],section:[],
small:[],span:[],sub:[],sup:[],strong:[],table:["width","border","align","valign"],tbody:["align","valign"],td:["width","rowspan","colspan","align","valign"],tfoot:["align","valign"],th:["width","rowspan","colspan","align","valign"],thead:["align","valign"],tr:["rowspan","align","valign"],tt:[],u:[],ul:[],video:"autoplay controls loop preload src height width".split(" ")}},onTag:function(h,n,p){},onIgnoreTag:function(h,n,p){},onTagAttr:function(h,n,p){},onIgnoreTagAttr:function(h,n,p){},safeAttrValue:function(h,
n,p,x){if(p=w(p),"href"===n||"src"===n){if("#"===(p=R(p)))return"#";if("http://"!==p.substr(0,7)&&"https://"!==p.substr(0,8)&&"mailto:"!==p.substr(0,7)&&"tel:"!==p.substr(0,4)&&"#"!==p[0]&&"/"!==p[0])return""}else if("background"===n){if(ha.lastIndex=0,ha.test(p))return""}else if("style"===n){if((la.lastIndex=0,la.test(p))||(ma.lastIndex=0,ma.test(p)&&(ha.lastIndex=0,ha.test(p))))return"";!1!==x&&(p=(x=x||ba).process(p))}return p=u(p)},escapeHtml:K,escapeQuote:D,unescapeQuote:r,escapeHtmlEntities:A,
escapeDangerHtml5Entities:F,clearNonPrintableCharacter:t,friendlyAttrValue:w,escapeAttrValue:u,onIgnoreTagStripAll:function(){return""},StripTagBody:function(h,n){"function"!=typeof n&&(n=function(){});var p=!Array.isArray(h),x=[],B=!1;return{onIgnoreTag:function(G,L,E){return p||-1!==Z(h,G)?E.isClosing?(x.push([!1!==B?B:E.position,E.position+10]),B=!1,"[/removed]"):(B||(B=E.position),"[removed]"):n(G,L,E)},remove:function(G){var L="",E=0;return da(x,function(I){L+=G.slice(E,I[0]);E=I[1]}),L+=G.slice(E)}}},
stripCommentTag:function(h){return h.replace(va,"")},stripBlankChar:function(h){h=h.split("");return(h=h.filter(function(n){n=n.charCodeAt(0);return 127!==n&&(!(31>=n)||10===n||13===n)})).join("")},cssFilter:ba,getDefaultCSSWhiteList:fa},wa=/[^a-zA-Z0-9_:\.\-]/gim,ia={parseTag:function(h,n,p){var x="",B=0,G=!1,L=!1,E=0,I=h.length,N="",O="";for(E=0;E<I;E++)O=h.charAt(E),!1===G?"\x3c"===O&&(G=E):!1===L?"\x3c"===O?(x+=p(h.slice(B,E)),B=G=E):"\x3e"===O?(x+=p(h.slice(B,G)),B=O=h.slice(G,E+1),N=ea(B),B=
-1===N?B.slice(1,-1):B.slice(1,N+1),N=("/"===(B=R(B).toLowerCase()).slice(0,1)&&(B=B.slice(1)),"/"===B.slice(-1)&&(B=B.slice(0,-1)),B),x+=n(G,x.length,N,O,"\x3c/"===O.slice(0,2)),B=E+1,G=!1):'"'!==O&&"'"!==O||"\x3d"!==h.charAt(E-1)||(L=O):O===L&&(L=!1);return B<h.length&&(x+=p(h.substr(B))),x},parseAttr:function(h,n){function p(N,O){1>(N=(N=R(N)).replace(wa,"").toLowerCase()).length||(N=n(N,O||""))&&B.push(N)}for(var x=0,B=[],G=!1,L=h.length,E=0;E<L;E++){var I=h.charAt(E);if(!1!==G||"\x3d"!==I)if(!1===
G||E!==x||'"'!==I&&"'"!==I||"\x3d"!==h.charAt(E-1))/\s|\n|\t/.test(I)&&((h=h.replace(/\s|\n|\t/g," "),!1===G)?-1===(I=g(h,E))?(p(R(h.slice(x,E))),G=!1,x=E+1):E=I-1:-1===(I=f(h,E-1))&&(p(G,c(R(h.slice(x,E)))),G=!1,x=E+1));else{if(-1===(I=h.indexOf(I,E+1)))break;p(G,R(h.slice(x+1,I)));G=!1;x=(E=I)+1}else G=h.slice(x,E),x=E+1}return x<h.length&&(!1===G?p(h.slice(x)):p(G,c(R(h.slice(x))))),R(B.join(" "))}},ua=a.FilterCSS,xa=ia.parseTag,ya=ia.parseAttr;d.prototype.process=function(h){if(!(h=(h=h||"").toString()))return"";
var n=this.options,p=n.whiteList,x=n.onTag,B=n.onIgnoreTag,G=n.onTagAttr,L=n.onIgnoreTagAttr,E=n.safeAttrValue,I=n.escapeHtml,N=this.cssFilter;n.stripBlankChar&&(h=W.stripBlankChar(h));n.allowCommentTag||(h=W.stripCommentTag(h));var O=!1;n.stripIgnoreTagBody&&(O=W.StripTagBody(n.stripIgnoreTagBody,B),B=O.onIgnoreTag);h=xa(h,function(S,T,V,Y,za){T={sourcePosition:S,position:T,isClosing:za,isWhite:p.hasOwnProperty(V)};if(null!=(S=x(V,Y,T)))return S;if(T.isWhite){if(T.isClosing)return"\x3c/"+V+"\x3e";
S=function(U){var X=ea(U);if(-1===X)return{html:"",closing:"/"===U[U.length-2]};X="/"===(U=R(U.slice(X+1,-1)))[U.length-1];return X&&(U=R(U.slice(0,-1))),{html:U,closing:X}}(Y);var Aa=p[V];T=ya(S.html,function(U,X){var ja,ka=-1!==Z(Aa,U);return null==(ja=G(V,U,X,ka))?ka?(X=E(V,U,X,N))?U+'\x3d"'+X+'"':U:null==(ja=L(V,U,X,ka))?void 0:ja:ja});Y="\x3c"+V;return T&&(Y+=" "+T),S.closing&&(Y+=" /"),Y+="\x3e"}return null==(S=B(V,Y,T))?I(Y):S},I);return O&&(h=O.remove(h)),h};var ca=Q(function(h,n){function p(B,
G){return(new d(G)).process(B)}for(var x in(n=h.exports=p).filterXSS=p,n.FilterXSS=d,W)n[x]=W[x];for(x in ia)n[x]=ia[x];"undefined"!=typeof self&&"undefined"!=typeof DedicatedWorkerGlobalScope&&self instanceof DedicatedWorkerGlobalScope&&(self.filterXSS=h.exports)});ca.filterXSS;ca.FilterXSS;return function(){function h(n,p){var x,B=this;this.arcgisWhiteList={a:["href","target","style"],img:"src width height border alt style".split(" "),video:"autoplay controls height loop muted poster preload width".split(" "),
audio:["autoplay","controls","loop","muted","preload"],source:["media","src","type"],span:["style"],table:"width height cellpadding cellspacing border style".split(" "),div:["style","align"],font:["size","color","style"],tr:["height","valign","align","style"],td:"height width valign align colspan rowspan nowrap style".split(" "),th:"height width valign align colspan rowspan nowrap style".split(" "),p:["style"],b:[],strong:[],i:[],em:[],u:[],br:[],li:[],ul:[],ol:[],hr:[],tbody:[]};this.allowedProtocols=
"http https mailto iform tel flow lfmobile arcgis-navigator arcgis-appstudio-player arcgis-survey123 arcgis-collector arcgis-workforce arcgis-explorer arcgis-trek2there mspbi comgooglemaps pdfefile pdfehttp pdfehttps boxapp boxemm awb awbs gropen radarscope".split(" ");this.arcgisFilterOptions={allowCommentTag:!0,safeAttrValue:function(G,L,E,I){return"a"===G&&"href"===L||("img"===G||"source"===G)&&"src"===L?B.sanitizeUrl(E):ca.safeAttrValue(G,L,E,I)}};n&&!p?x=n:n&&p?(x=Object.create(this.arcgisFilterOptions),
Object.keys(n).forEach(function(G){"whiteList"===G?x.whiteList=B._extendObjectOfArrays([B.arcgisWhiteList,n.whiteList||{}]):x[G]=n[G]})):(x=Object.create(this.arcgisFilterOptions)).whiteList=this.arcgisWhiteList;this.xssFilterOptions=x;this._xssFilter=new ca.FilterXSS(x);this.xss=ca}return h.prototype.sanitize=function(n,p){switch(void 0===p&&(p={}),typeof n){case "number":return isNaN(n)||!isFinite(n)?null:n;case "boolean":return n;case "string":return this._xssFilter.process(n);case "object":return this._iterateOverObject(n,
p);default:if(!p.allowUndefined||void 0!==n)return null}},h.prototype.sanitizeUrl=function(n){var p=this._trim(n.substring(0,n.indexOf(":")));return"/"===n||"#"===n||"#"===n[0]||-1<this.allowedProtocols.indexOf(p.toLowerCase())?ca.escapeAttrValue(n):""},h.prototype.validate=function(n,p){void 0===p&&(p={});p=this.sanitize(n,p);return{isValid:n===p,sanitized:p}},h.prototype._extendObjectOfArrays=function(n){var p={};return n.forEach(function(x){Object.keys(x).forEach(function(B){Array.isArray(x[B])&&
Array.isArray(p[B])?p[B]=p[B].concat(x[B]):p[B]=x[B]})}),p},h.prototype._iterateOverObject=function(n,p){var x=this;void 0===p&&(p={});try{var B=!1,G=void 0;if(Array.isArray(n))G=n.reduce(function(L,E){var I=x.validate(E,p);return I.isValid?L.concat([E]):(B=!0,L.concat([I.sanitized]))},[]);else{if(!C(n))return p.allowUndefined&&void 0===n?void 0:null;G=Object.keys(n).reduce(function(L,E){var I=n[E],N=x.validate(I,p);return N.isValid?L[E]=I:(B=!0,L[E]=N.sanitized),L},{})}return B?G:n}catch(L){return null}},
h.prototype._trim=function(n){return String.prototype.trim?n.trim():n.replace(/(^\s*)|(\s*$)/g,"")},h}()})}}});define("./usng/usng ./storejs/json ./storejs/store ./md5/md5 ./qrcode ./arcgis-html-sanitizer/arcgis-html-sanitizer".split(" "),function(){});