//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/declare esri/core/lang esri/views/3d/webgl-engine/lib/Util esri/core/libs/gl-matrix-2/vec3f64 esri/core/libs/gl-matrix-2/vec2f64 esri/core/libs/gl-matrix-2/vec3 esri/core/libs/gl-matrix-2/vec2 ../../webgl-engine-extensions/VertexBufferLayout ../../webgl-engine-extensions/GLVertexArrayObject ../../webgl-engine-extensions/GLXBO ../../webgl-engine-extensions/GLVerTexture ../../support/fx3dUtils ../../support/fx3dUnits ../Effect ./FireballMaterial ../../webgl-engine-extensions/constraints".split(" "),
function(x,E,L,u,U,M,N,l,y,O,F,z,P,f,m,G,Q,R){u=M.vec3f64;l=l.vec3;var S=N.vec2f64;y=y.vec2;var n=u.create(),p=u.create(),H=u.create(),T=R.VertexAttrConstants;return L([G],{declaredClass:"esri.views.3d.effects.Fireball.FireballEffect",effectName:"Fireball",constructor:function(b){x.hitch(this,b);this.orderId=2;this._pathIdNum=0;this._tmpPoints=[];this.localOriginFactory=G.createLocalOriginFactory();this._renderObjects={};this._needsAllLoaded=!0},_initRenderingInfo:function(){this.renderingInfo.radius=
40;this.renderingInfo.width=50;this.renderingInfo.height=50;this.renderingInfo.colors=[f.rgbNames.cadetblue,f.rgbNames.yellowgreen,f.rgbNames.lightpink,f.rgbNames.orangered,f.rgbNames.green,f.rgbNames.indianred];this._renderingInfoDirty=this._colorBarDirty=!0;this._curveType=1;this._shapeDirty=this._vacDirty=!0;this.inherited(arguments)},_doRenderingInfoChange:function(b){this.inherited(arguments);for(var a in b)b.hasOwnProperty(a)&&this.renderingInfo.hasOwnProperty(a)&&(f.endsWith(a.toLowerCase(),
"info")?f.isInforAttrChanged(this.renderingInfo[a],b[a])&&(this._renderingInfoDirty=!0):f.endsWith(a.toLowerCase(),"colors")?b[a]instanceof Array&&(this.renderingInfo[a]=b[a],this._colorBarDirty=!0,this._renderingInfoDirty=!0):"radius"===a.toLowerCase()||"width"===a.toLowerCase()||"height"===a.toLowerCase()||"transparency"===a.toLowerCase()?(this._clampScope(b,a),"radius"==a&&this._radiusUnit?this.renderingInfo[a]=m.toMeters(this._radiusUnit,b[a],this._view.viewingMode):"width"==a&&this._widthUnit?
this.renderingInfo[a]=m.toMeters(this._widthUnit,b[a],this._view.viewingMode):"height"==a&&this._heightUnit?this.renderingInfo[a]=m.toMeters(this._heightUnit,b[a],this._view.viewingMode):this.renderingInfo[a]=b[a]):typeof b[a]==typeof this.renderingInfo[a]&&(this.renderingInfo[a]=b[a]))},initEffect:function(b){this.inherited(arguments);this._effectConfig&&x.isArray(this._effectConfig.renderingInfo)&&(this._radiusUnit=null,this._widthUnit=null,this._heightUnit=null,E.forEach(this._effectConfig.renderingInfo,
function(a){"radius"===a.name.toLowerCase()?(this._radiusUnit=a.unit,this.renderingInfo.radius=m.toMeters(this._radiusUnit,this.renderingInfo.radius,this._view.viewingMode)):"width"===a.name.toLowerCase()?(this._widthUnit=a.unit,this.renderingInfo.width=m.toMeters(this._widthUnit,this.renderingInfo.width,this._view.viewingMode)):"height"===a.name.toLowerCase()&&(this._heightUnit=a.unit,this.renderingInfo.height=m.toMeters(this._heightUnit,this.renderingInfo.height,this._view.viewingMode))}.bind(this)))},
destroy:function(){this._resetXBOs();this._dispose("_aroundVerticesTexture");this._dispose("_vao");this._dispose("_particleVAO")},_resetXBOs:function(){this._dispose("_vbo");this._dispose("_ibo");this._dispose("_particleVBO")},_initVertexLayout:function(){this._vertexAttrConstants=[T.AUXPOS1];this._vertexBufferLayout=new O(this._vertexAttrConstants,[3],[5126])},_initRenderContext:function(){return this.inherited(arguments),this._vacDirty&&(this._initVertexLayout(),this._resetXBOs(),this._vacDirty=
!1,this._vao&&(this._vao.unbind(),this._vao._initialized=!1),this._particleVAO&&(this._particleVAO.unbind(),this._particleVAO._initialized=!1)),this._vbo||(this._vbo=new z(this._gl,!0,this._vertexBufferLayout)),this._particleVBO||(this._particleVBO=new z(this._gl,!0,this._vertexBufferLayout)),this._ibo||(this._ibo=new z(this._gl,!1)),this._vaoExt&&(this._vao=new F(this._gl,this._vaoExt),this._particleVAO=new F(this._gl,this._vaoExt)),this._localBindsCallback||(this._localBindsCallback=this._localBinds.bind(this)),
1===this._curveType?this._buildAroundPathGeometries():0===this._curveType&&this._buildAlongPathGeometries()},_buildAroundPathGeometries:function(){var b=this._allGraphics();if(0<b.length){var a,d,e,c,h,q,k,g,r,A=0,v=[],B=[],t=0,I=0,C=1,w=[];this._isAddingGeometry||(this._pathIdNum=0,this._tmpPoints=[]);var J=this._vertexBufferLayout.getStride();return E.forEach(b,function(K,D){if(null!=K.geometry)for(q=K.geometry.paths,k=0;k<q.length;k++)if(!(2>q[k].length)){c=e=0;a=q[k][0];a[2]||(a[2]=40.11);d=q[k][q[k].length-
1];d[2]||(d[2]=40.11);l.set(n,a[0],a[1],a[2]);"global"===this._view.viewingMode?f.wgs84ToSphericalEngineCoords(n,0,n,0):"local"===this._view.viewingMode&&f.wgs84ToWebMerc(n,0,n,0);l.set(p,d[0],d[1],d[2]);"global"===this._view.viewingMode?f.wgs84ToSphericalEngineCoords(p,0,p,0):"local"===this._view.viewingMode&&f.wgs84ToWebMerc(p,0,p,0);l.subtract(H,n,p);c=l.length(H);"global"===this._view.viewingMode?e=1E3>=c?32:1E4>=c?24:5E5>=c?18:1E6>=c?40:Math.floor(1E-5*c):"local"===this._view.viewingMode&&(e=
1E3>=c?48:1E4>=c?42:1E5>=c?32:1E6>=c?24:2E6>=c?36:Math.floor(6E-6*c));e=2*e+1;for(g=0;g<e;g++)h=J*(g+t),v[0+h]=this._pathIdNum,v[1+h]=D+0,v[2+h]=g,g<e-1&&(A=2*(g+t-D),B[A+0]=g+t+0,B[A+1]=g+t+0+1);t+=e;C=Math.max(1,Math.floor(e/20));for(r=0;r<C;r++)h=J*(r+I),w[0+h]=this._pathIdNum,w[1+h]=D+0,w[2+h]=18*r;I+=C;this._pathIdNum++;this._tmpPoints.push([a[0],a[1],a[2]]);this._tmpPoints.push([d[0],d[1],d[2]])}}.bind(this)),this._vbo.addData(this._isAddingGeometry,new Float32Array(v)),this._ibo.addData(this._isAddingGeometry,
new Uint32Array(B)),this._particleVBO.addData(this._isAddingGeometry,new Float32Array(w)),this._vao&&(this._vao._initialized=!1),this._particleVAO&&(this._particleVAO._initialized=!1),this._resetAddGeometries(),this._initAroundVerticesTexture()}return!1},_buildAlongPathGeometries:function(){return!1},_initAroundVerticesTexture:function(){if(2*this._pathIdNum!==this._tmpPoints.length)return!1;var b=this._gl.getParameter(3379),a=2*this._pathIdNum,d=f.nextHighestPowerOfTwo(a);d>b&&(d=b,console.warn("Too many graphics, and some data will be discarded."));
a=Math.ceil(a/d);a=f.nextHighestPowerOfTwo(a);a>b&&(a=b,console.warn("Too many graphics, and some data will be discarded."));for(var e=new Float32Array(d*a*4),c=0;c<this._pathIdNum;c++)b=8*c,e[0+b]=c,e[1+b]=this._tmpPoints[2*c][0],e[2+b]=this._tmpPoints[2*c][1],e[3+b]=this._tmpPoints[2*c][2],e[4+b]=c,e[5+b]=this._tmpPoints[2*c+1][0],e[6+b]=this._tmpPoints[2*c+1][1],e[7+b]=this._tmpPoints[2*c+1][2];return this._aroundVerticesTexture||(this._aroundVerticesTexture=new P(this._gl),this._aroundVerticesTextureSize=
S.create()),this._aroundVerticesTexture.setData(d,a,e),y.set(this._aroundVerticesTextureSize,d,a),!0},_initColourMap:function(){this._colourMapTexture||(this._colourMapTexture=this._gl.createTexture());var b=new Image;b.src=f.spriteImg;var a=this;return b.onload=function(){var d=a._gl.getParameter(a._gl.TEXTURE_BINDING_2D);a._gl.bindTexture(3553,a._colourMapTexture);a._gl.pixelStorei(37440,!0);a._gl.texParameteri(3553,10240,9728);a._gl.texParameteri(3553,10241,9728);a._gl.texParameteri(3553,10242,
33071);a._gl.texParameteri(3553,10243,33071);a._gl.texImage2D(3553,0,6408,6408,5121,b);a._gl.generateMipmap(3553);a._gl.bindTexture(3553,d)},0===this._gl.getError()},_loadShaders:function(){return this.inherited(arguments),this._material||(this._material=new Q({pushState:this._pushState.bind(this),restoreState:this._restoreState.bind(this),gl:this._gl,viewingMode:this._view.viewingMode,shaderSnippets:this._shaderSnippets})),this._material.loadShaders()},_initColorBar:function(){if(!this._colorBarDirty)return!0;
this._colorBarTexture||(this._colorBarTexture=this._gl.createTexture());var b=this._gl.getParameter(32873);this._gl.bindTexture(3553,this._colorBarTexture);this._gl.pixelStorei(37440,!0);this._gl.texParameteri(3553,10240,9728);this._gl.texParameteri(3553,10241,9728);this._gl.texParameteri(3553,10242,33071);this._gl.texParameteri(3553,10243,33071);var a=f._clampBlackColor(this.renderingInfo.colors);a=f.createColorBarTexture(32,1,a);return this._gl.texImage2D(3553,0,6408,6408,5121,a),this._gl.generateMipmap(3553),
this._gl.bindTexture(3553,b),0===this._gl.getError()},_localBinds:function(b,a){b.bind(this._material._program);this._vertexBufferLayout.enableVertexAttribArrays(this._gl,this._material._program);a&&a.bind()},_bindBuffer:function(b,a,d){b?(b._initialized||b.initialize(this._localBindsCallback,[a,d]),b.bind()):this._localBinds(a,d)},_unBindBuffer:function(b,a,d){b?b.unbind():(a.unbind(),this._vertexBufferLayout.disableVertexAttribArrays(this._gl,this._material._program),d&&d.unbind())},render:function(b,
a){this.inherited(arguments);this._layer.visible&&this.ready&&this._bindPramsReady()&&(this._hasSentReady||(this._layer.emit("fx3d-ready"),this._hasSentReady=!0),this._material.bind(x.mixin({},{ee:this._aroundVerticesTexture,sl:this._aroundVerticesTextureSize,lo:this._colourMapTexture,ss:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],po:this._vizFieldVerTextureSize,io:this.renderingInfo.animationInterval,pi:this.renderingInfo.radius,sp:this.renderingInfo.transparency,is:this._vizFieldMinMaxs[this._vizFieldDefault].min>
this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,ei:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,ps:this._colorBarTexture},b),a),this._material.bindBoolean("drawPath",!0),this._material.blend(!0,
a),this._bindBuffer(this._vao,this._vbo,this._ibo),this._gl.drawElements(1,this._ibo.getNum(),5125,0),this._unBindBuffer(this._vao,this._vbo,this._ibo),this._material.bindBoolean("drawPath",!1),this._material.blend(!1,a),this._bindBuffer(this._particleVAO,this._particleVBO,null),this._gl.drawArrays(0,0,this._particleVBO.getNum()),this._material.release(a),this._unBindBuffer(this._particleVAO,this._particleVBO,null))}})});