// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/_base/config dojo/cookie dojo/Deferred dojo/promise/all dojo/request/xhr ./utils ./privilegeUtils ./WidgetManager ./shared/utils ./tokenUtils ./portalUtils ./appConfigResourceUtils ./portalUrlUtils ./AppStateManager esri/identity/IdentityManager esri/core/urlUtils".split(" "),function(G,f,z,H,A,B,u,x,C,p,y,I,v,m,t,J,q,K,D,F){var w=null;var E=G(null,{urlParams:null,appConfig:null,rawAppConfig:null,configFile:null,_configLoaded:!1,
portalSelf:null,constructor:function(a,b){this._removeHash(a);this.urlParams=a||{};this.widgetManager=I.getInstance();f.mixin(this,b)},loadConfig:function(){console.time("Load Config");return this._tryLoadConfig().then(f.hitch(this,function(a){var b=this.checkConfig(a);if(b)throw b;this.rawAppConfig=f.clone(a);K.getInstance().setRawAppConfig(this.rawAppConfig);a=this._upgradeAppConfig(a);this._processAfterTryLoad(a);this.appConfig=a;if(this.urlParams.id)return this.loadWidgetsManifest(a).then(f.hitch(this,
function(){return this._upgradeAllWidgetsConfig(a)})).then(f.hitch(this,function(c){return this.insertAppIdtoResourceUrlofAppConfig(c,this.urlParams.id)})).then(f.hitch(this,function(){this._configLoaded=!0;a.title&&(document.title=window.isBuilder?p.stripHTML(a.title)+" - ArcGIS Web AppBuilder":p.stripHTML(a.title));this._readAndSetSharedTheme(a);return this.getAppConfig()}));m.setPortalUrl(a.portalUrl);return this._proesssWebTierAndSignin(a).then(f.hitch(this,function(){if(this.urlParams.appid){if(window.appInfo.isRunInPortal){var c=
q.getStandardPortalUrl(a.portalUrl),d=t.getPortal(c);return y.checkIsSelfOrigin(this.urlParams.appid,d,m.isInBuilderWindow()).then(f.hitch(this,function(e){if(!e)throw e=Error(window.jimuNls.orgUrlMessage),e.isSelfOrigin=!1,e;})).then(f.hitch(this,function(){return y.checkEssentialAppsLicense(this.urlParams.appid,d,m.isInBuilderWindow()).then(f.hitch(this,function(){return this._getAppConfigFromTemplateAppId(a.portalUrl,this.urlParams.appid).then(f.hitch(this,function(e){this._tryUpdateAppConfigByLocationUrl(e);
return this._processInPortalAppProtocol(e)}))}),f.hitch(this,function(e){console.error(e);if(e&&e.isBlockedByOrg)throw Error(window.jimuNls.blockedByAdminErrorForApp);throw Error(window.jimuNls.essentialAppsLicenseErrorForApp);}))}))}return this._processNotInPortalAppProtocol(a).then(f.hitch(this,function(e){return this._getAppDataAddTemplateDataFromTemplateAppId(e.portalUrl,this.urlParams.appid).then(f.hitch(this,function(h){h.appData.appConfig&&(e=h.appData.appConfig);e._appData=h.appData;e.templateConfig=
h.templateData;e.isTemplateApp=!0;return e}))}))}return this._processNotInPortalAppProtocol(a)})).then(f.hitch(this,function(c){this._processAfterTryLoad(c);this.appConfig=c;return c.map.itemId?c:t.getDefaultWebScene(c.portalUrl).then(function(d){c.map.itemId=d;return c})})).then(f.hitch(this,function(c){return this.loadWidgetsManifest(c)})).then(f.hitch(this,function(c){return c._appData?c._appData.values&&c._appData.values.webmap?t.getPortal(c.portalUrl).getItemById(c._appData.values.webmap).then(f.hitch(this,
function(d){return p.template.mergeTemplateAppConfigToAppConfig(c,c._appData,d)})):p.template.mergeTemplateAppConfigToAppConfig(c,c._appData):c})).then(f.hitch(this,function(c){return this._upgradeAllWidgetsConfig(c)})).then(f.hitch(this,function(c){return c._wabAppId?this.processResourceInAppConfigForConfigLoader(c,this.urlParams):c.appItemId&&-1<window.JSON.stringify(c).indexOf("${itemId}")?this.insertAppIdtoResourceUrlofAppConfig(c,c.appItemId):c})).then(f.hitch(this,function(c){this.appConfig=
c;this._configLoaded=!0;c.title&&(document.title=p.stripHTML(c.title));this._readAndSetSharedTheme(c);return this.getAppConfig()}))}),f.hitch(this,function(a){var b=new u;b.reject(a);return b}))},processResourceInAppConfigForConfigLoader:function(a,b){var c=a.portalUrl,d=a.appItemId,e=b.appid,h=new u,g=f.clone(a);this.insertAppIdtoResourceUrlofAppConfig(g,e).then(function(){if("config"===b.mode){var k=this.getResourceUrlsOfAppConfig(a).result;0!==k.length?t.getItemResources(c,e).then(function(n){if(0===
n.length)return k=k.map(function(l){return{resUrl:l}}),J.AddResourcesToItemForAppSave(c,k,d,e).then(function(){h.resolve(g)},function(l){console.warn("Add resource to template based app error:"+l.message||l);h.resolve(g)});h.resolve(g)},function(n){console.warn("Get resource of template based item error:"+n.message||n);h.resolve(g)}):h.resolve(g)}else h.resolve(g)}.bind(this),function(k){console.warn("Insert appId to resource url of appConfig error:"+k.message||k);h.resolve(g)});return h},getResourceUrlsOfAppConfig:function(a){var b=
{test:function(c){return/^https?:\/\/(.)+\/sharing\/rest\/content\/items/.test(c)},func:f.hitch(this,function(c){return c.value})};return p.processItemResourceOfAppConfig(a,b)},insertAppIdtoResourceUrlofAppConfig:function(a,b){function c(g){return/^https?:\/\/(.)+\/sharing\/rest\/content\/items/.test(g)}function d(g,k){var n=k.obj,l=k.key,r={obj:n,key:l};"number"===typeof k.i?(r.i=k.i,r.value=n[l][k.i]):r.value=n[l];k=r;g=h.processItemIdAndTokenOfResources(k.value,g);n=k.obj;l=k.key;"number"===typeof k.i?
n[l][k.i]=g:n[l]=g;return!0}var e=a.portalUrl,h=this;return t.getPortal(e).getItemById(b).then(f.hitch(this,function(g){g={test:c,func:f.hitch(this,d,{appId:b,isPublic:"public"===g.access,portalUrl:e})};return p.processItemResourceOfAppConfig(a,g).appConfig}))},processItemIdAndTokenOfResources:function(a,b){0<a.indexOf("${itemId}")&&(a=a.replace("${itemId}",b.appId));/(\?|&)token=.+/.test(a)&&(a=a.replace(/(\?|&)token=.+/,""));b.isPublic||(b=m.getPortalCredential(b.portalUrl))&&(a+="?token\x3d"+b.token);
return a},getAppConfig:function(){var a=f.clone(this.appConfig);a.getConfigElementById=function(b){return p.getConfigElementById(this,b)};a.getConfigElementsByName=function(b){return p.getConfigElementsByName(this,b)};a.visitElement=function(b){p.visitElement(this,b)};this._addAuthorizedCrossOriginDomains(this.portalSelf,a);return a},_addAuthorizedCrossOriginDomains:function(a,b){a&&a.authorizedCrossOriginDomains&&m.addAuthorizedCrossOriginDomains(a.authorizedCrossOriginDomains);b&&b.authorizedCrossOriginDomains&&
m.addAuthorizedCrossOriginDomains(b.authorizedCrossOriginDomains)},checkConfig:function(a){return(a=this._getRepeatedId(a))?"repeated id:"+a:null},processProxy:function(a){var b=p.getEsriConfigRequestObject();b.alwaysUseProxy=a.httpProxy&&a.httpProxy.useProxy&&a.httpProxy.alwaysUseProxy;b.proxyUrl="";b.proxyRules=[];a.httpProxy&&a.httpProxy.useProxy&&a.httpProxy.url&&(b.proxyUrl=a.httpProxy.url);a.httpProxy&&a.httpProxy.useProxy&&a.httpProxy.rules&&z.forEach(a.httpProxy.rules,function(c){F.addProxyRule(c)})},
addNeedValues:function(a){this._processNoUriWidgets(a);this._processEmptyGroups(a);this._addElementId(a);this._processWidgetJsons(a)},showError:function(a){H.create("div",{"class":"app-error",innerHTML:p.sanitizeHTML(a.message)},document.body)},_tryLoadConfig:function(){if(this.urlParams.config)return this.configFile=this.urlParams.config,C(this.configFile,{handleAs:"json",headers:{"X-Requested-With":null}}).then(f.hitch(this,function(d){m.setPortalUrl(d.portalUrl);d.portalUrl&&(window.portalUrl=
d.portalUrl);return this.urlParams.token?m.registerToken(this.urlParams.token).then(function(){return d}):d}));if(this.urlParams.id){window.appInfo.isRunInPortal=!0;var a=q.getPortalUrlFromLocation(),b=new u;m.setPortalUrl(a);window.portalUrl=a;if(this.urlParams.token)var c=m.registerToken(this.urlParams.token);else c=new u,c.resolve();c.then(f.hitch(this,function(){var d=t.getPortal(a);d.loadSelfInfo().then(f.hitch(this,function(e){this.portalSelf=e;e.allSSL&&"http:"===window.location.protocol?(window.location.href=
q.setHttpsProtocol(window.location.href),b.reject()):this._processSignIn(a).then(f.hitch(this,function(){this._getAppConfigFromAppId(a,this.urlParams.id).then(f.hitch(this,function(h){return y.checkIsSelfOrigin(this.urlParams.id,d,m.isInBuilderWindow()).then(f.hitch(this,function(g){if(g)return h;g=Error(window.jimuNls.orgUrlMessage);g.isSelfOrigin=!1;throw g;}))})).then(f.hitch(this,function(h){return y.checkEssentialAppsLicense(this.urlParams.id,d,m.isInBuilderWindow()).then(f.hitch(this,function(){this._tryUpdateAppConfigByLocationUrl(h);
return this._processInPortalAppProtocol(h)}),f.hitch(this,function(g){console.error(g);if(g&&g.isBlockedByOrg)throw Error(window.jimuNls.blockedByAdminErrorForApp);throw Error(window.jimuNls.essentialAppsLicenseErrorForApp);}))})).then(function(h){b.resolve(h)},function(h){b.reject(h)})}))}))}),f.hitch(this,function(d){this.showError(d)}));return b}this.configFile="config.json";return C(this.configFile,{handleAs:"json"}).then(f.hitch(this,function(d){m.setPortalUrl(d.portalUrl);d.portalUrl&&(window.portalUrl=
d.portalUrl);return this.urlParams.token?m.registerToken(this.urlParams.token).then(function(){return d}):d}))},_upgradeAppConfig:function(a){var b=window.wabVersion,c=a.wabVersion;if(b===c)return a;var d=this.versionManager.getVersionIndex(c),e=this.versionManager.getVersionIndex(b);if(d>e)throw Error("Bad version number, "+c);a=this.versionManager.upgrade(a,c,b);a.wabVersion=b;a.isUpgraded=!0;return a},_upgradeAllWidgetsConfig:function(a){var b=new u,c=[];if(!a.isUpgraded)return b.resolve(a),b;
delete a.isUpgraded;v.visitElement(a,f.hitch(this,function(d){d.uri&&(d.config?(d=this.widgetManager.tryLoadWidgetConfig(d),c.push(d)):d.version=d.manifest.version)}));x(c).then(f.hitch(this,function(){b.resolve(a)}),function(d){b.reject(d)});return b},_processAfterTryLoad:function(a){this._setPortalUrl(a);this._tryUpdateAppConfigByLocationUrl(a);this._processUrlParams(a);this.addNeedValues(a);this.processProxy(a);D.tokenValidity=10080;return a},_readAndSetSharedTheme:function(a){a.theme.sharedTheme||
(a.theme.sharedTheme={useHeader:!1,useLogo:!1},a.theme.sharedTheme.isPortalSupport=this.portalSelf.portalProperties&&this.portalSelf.portalProperties.sharedTheme?!0:!1);a.theme.sharedTheme.useHeader&&(a.theme.sharedTheme.isPortalSupport&&this.portalSelf.portalProperties?(a.theme.customStyles={mainBackgroundColor:this.portalSelf.portalProperties.sharedTheme.header.background},a.titleColor=this.portalSelf.portalProperties.sharedTheme.header.text):console.error("Portal does not support sharedTheme."));
a.theme.sharedTheme.useLogo&&(a.theme.sharedTheme.isPortalSupport&&this.portalSelf.portalProperties?(a.logo=this.portalSelf.portalProperties.sharedTheme.logo.small?this.portalSelf.portalProperties.sharedTheme.logo.small:"images/app-logo.png",!a.logoLink&&this.portalSelf.portalProperties.sharedTheme.logo.link&&(a.logoLink=this.portalSelf.portalProperties.sharedTheme.logo.link)):(console.error("Portal does not support sharedTheme, use default logo."),a.logo="images/app-logo.png"))},_tryUpdateAppConfigByLocationUrl:function(a){if(!(this.urlParams.config&&
-1<this.urlParams.config.indexOf("arcgis.com/sharing/rest/content/items/"))){var b=q.getPortalUrlFromLocation();b=q.getStandardPortalUrl(b);q.isOnline(b)&&(b=q.updateUrlProtocolByOtherUrl(b,a.portalUrl),a.map.portalUrl&&q.isSamePortalUrl(a.portalUrl,a.map.portalUrl)&&(a.map.portalUrl=b),a.portalUrl=b,a.httpProxy&&a.httpProxy.url&&(a.httpProxy.url=q.getPortalProxyUrl(b)))}},_processWidgetJsons:function(a){v.visitElement(a,function(b,c){c.isWidget&&b.uri&&p.processWidgetSetting(b)})},_processNoUriWidgets:function(a){var b=
0;v.visitElement(a,function(c,d){d.isWidget&&!c.uri&&(b++,c.placeholderIndex=b)})},_processEmptyGroups:function(a){var b=0;a.widgetOnScreen.groups&&z.forEach(a.widgetOnScreen.groups,function(c){if(!c.widgets||c.widgets&&0===c.widgets.length)b++,c.placeholderIndex=b})},_addElementId:function(a){var b=0,c;v.visitElement(a,function(d){if(d.id){d.id=d.id.replace(/\//g,"_");var e=d.id.lastIndexOf("_");-1<e&&(c=d.id.substr(e+1),b=Math.max(b,c))}});v.visitElement(a,function(d){d.id||(b++,d.id=d.uri?d.uri.replace(/\//g,
"_")+"_"+b:"_"+b)})},_setPortalUrl:function(a){if(a.portalUrl){var b=q.getPortalUrlFromLocation(),c=q.isOnline(b);q.isSamePortalUrl(a.portalUrl,b)||c||(window.appInfo.isRunInPortal=!1)}else window.isXT&&B("wab_portalurl")?a.portalUrl=B("wab_portalurl"):(window.appInfo.isRunInPortal=!0,a.portalUrl=q.getPortalUrlFromLocation())},_changePortalUrlProtocol:function(a,b){a.portalUrl=q.setProtocol(a.portalUrl,b);a.map.portalUrl&&(a.map.portalUrl=q.setProtocol(a.map.portalUrl,b));a.httpProxy&&(a.httpProxy.url=
q.setProtocol(a.httpProxy.url,b),a.httpProxy&&a.httpProxy.rules&&z.forEach(a.httpProxy.rules,f.hitch(this,function(c){c.proxyUrl=q.setProtocol(c.proxyUrl,b)})))},_processInPortalAppProtocol:function(a){var b=new u,c=t.getPortal(a.portalUrl),d=f.hitch(this,function(e){if("https:"===window.location.protocol)this._changePortalUrlProtocol(a,"https");else{if(e){window.location.href=q.setHttpsProtocol(window.location.href);b.reject();return}this._changePortalUrlProtocol(a,"http")}this._checkLocale();b.resolve(a)});
c.loadSelfInfo().then(f.hitch(this,function(e){this.portalSelf=e;"private"===e.access?(e=0===a.portalUrl.toLowerCase().indexOf("https://"),d(e)):d(e.allSSL)}),f.hitch(this,function(e){b.reject(e)}));return b},_processNotInPortalAppProtocol:function(a){var b=new u;a.portalUrl?t.getPortal(a.portalUrl).loadSelfInfo().then(f.hitch(this,function(c){this.portalSelf=c;var d="https:"===window.location.protocol;(c.allSSL||d)&&this._changePortalUrlProtocol(a,"https");0!==a.portalUrl.toLowerCase().indexOf("https://")||
d||m.isInConfigOrPreviewWindow()?b.resolve(a):(window.location.href=q.setHttpsProtocol(window.location.href),b.reject())}),f.hitch(this,function(c){b.reject(c)})):b.resolve(a);return b},_proesssWebTierAndSignin:function(a){var b=new u,c=!1,d=a.portalUrl;this._processWebTier(a).then(f.hitch(this,function(e){c=e;return t.getPortal(d).loadSelfInfo()})).then(f.hitch(this,function(e){this.portalSelf=e;return this._processSignIn(d,c)})).then(f.hitch(this,function(){b.resolve()}),function(e){b.reject(e)});
return b},_processWebTier:function(a){var b=new u,c=a.portalUrl;a.isWebTier?(m.addAuthorizedCrossOriginDomains([c]),m.isWebTierPortal(c).then(f.hitch(this,function(){var d=m.getPortalCredential(c);d&&d.ssl&&"http:"===window.location.protocol&&!m.isInConfigOrPreviewWindow()?window.location.href=q.setHttpsProtocol(window.location.href):b.resolve(a.isWebTier)}),f.hitch(this,function(d){b.reject(d)}))):b.resolve(!1);return b},_processSignIn:function(a,b){var c=new u,d=t.getPortal(a),e=q.getSharingUrl(a);
window.appInfo.isRunInPortal?(b=D.checkSignInStatus(e),b.catch(function(){}).then(f.hitch(this,function(){c.resolve()}))):(m.isInBuilderWindow()||m.isInConfigOrPreviewWindow()||!this.portalSelf.supportsOAuth||!this.rawAppConfig.appId||b||m.registerOAuthInfo(a,this.rawAppConfig.appId,this.portalSelf.currentVersion),b=D.checkSignInStatus(e),b.catch(function(){}).then(f.hitch(this,function(){m.xtGetCredentialFromCookie(a);d.loadSelfInfo().then(f.hitch(this,function(h){this.portalSelf=h;this._checkLocale();
c.resolve()}))})));return c},_checkLocale:function(){if(!m.isInConfigOrPreviewWindow()){var a=this.portalSelf.user&&this.portalSelf.user.culture||A.locale;a="hi"===a?"en":a.toLowerCase();!this.urlParams.locale&&p.isLocaleChanged(A.locale,a)&&(B("wab_app_locale",a),window.location.reload())}},_getAppConfigFromTemplateAppId:function(a,b){var c=t.getPortal(a);return this._getWabAppIdAndDataFromTemplateAppId(a,b).then(f.hitch(this,function(d){var e=d.appId,h=d.appData;return x([this._getAppConfigFromAppId(a,
e),c.getItemData(h.source)]).then(f.hitch(this,function(g){if(h.appConfig){var k=h.appConfig;delete h.appConfig}else k=g[0];k=this._upgradeAppConfig(k);g=g[1];k._appData=h;k._wabAppId=e;k.templateConfig=g;k.isTemplateApp=!0;return k}))}))},_getAppDataAddTemplateDataFromTemplateAppId:function(a,b){var c=t.getPortal(a);return c.getItemData(b).then(function(d){return c.getItemData(d.source).then(function(e){return{appData:d,templateData:e}})})},_getWabAppIdAndDataFromTemplateAppId:function(a,b){var c=
new u,d=t.getPortal(a);d.getItemData(b).then(f.hitch(this,function(e){d.getItemById(e.source).then(f.hitch(this,function(h){h=F.urlToObject(h.url);c.resolve({appId:h.query.id,appData:e})}))}),function(e){c.reject(e)});return c},_getAppConfigFromAppId:function(a,b){return t.getPortal(a).getItemData(b)},_removeHash:function(a){for(var b in a)a[b]&&(a[b]=a[b].replace("#",""))},loadWidgetsManifest:function(a){function b(h,g,k){function n(l){return h.loadWidgetManifest(l).then(function(r){return r},function(r){console.log("Widget failed to load, it is removed.",
l.name);r.stack?console.error(r.stack):console.log(r);c(a,l)})}return g.itemId?t.getPortal(k).getItemById(g.itemId).then(function(l){var r=p.isEsriDomain(l.url)?!0:m.getPortalCredential(a.portalUrl)?!0:!1;if(r)return g.uri=p.widgetJson.getUriFromItem(l),n(g);console.log("Widget is not useable, it is removed.",g.name);c(a,g)}):n(g)}function c(h,g){function k(n){h[n]&&h[n].widgets&&(h[n].widgets=h[n].widgets.filter(function(l){if(g)return l.id!==g.id;l.uri&&!l.manifest&&console.error("Widget is removed because it is not loaded successfully.",
l.uri);return l.manifest}));h[n]&&h[n].groups&&h[n].groups.forEach(function(l){l.widgets&&(l.widgets=l.widgets.filter(function(r){if(g)return r.id!==g.id;r.uri&&!r.manifest&&console.error("Widget is removed because it is not loaded successfully.",r.uri);return r.manifest}))})}k("widgetOnScreen");k("widgetPool")}var d=[],e=new u;a._buildInfo&&a._buildInfo.widgetManifestsMerged?this._loadMergedWidgetManifests().then(f.hitch(this,function(h){v.visitElement(a,f.hitch(this,function(g){g.widgets||!g.uri&&
!g.itemId||(g.uri&&h[g.uri]?(this._addNeedValuesForManifest(h[g.uri],g.uri),p.widgetJson.addManifest2WidgetJson(g,h[g.uri])):d.push(b(this.widgetManager,g,a.portalUrl)))}));x(d).then(function(){e.resolve(a)})})):(v.visitElement(a,f.hitch(this,function(h){h.widgets||!h.uri&&!h.itemId||d.push(b(this.widgetManager,h,a.portalUrl))})),x(d).then(function(){e.resolve(a)}));setTimeout(function(){e.isResolved()||(c(a),e.resolve(a))},6E4);return e},_addNeedValuesForManifest:function(a,b){f.mixin(a,p.getUriInfo(b));
p.addManifestProperies(a);p.processManifestLabel(a,A.locale)},_loadMergedWidgetManifests:function(){return C(window.appInfo.appPath+"widgets/widgets-manifest.json",{handleAs:"json"})},_getRepeatedId:function(a){var b=[],c;v.visitElement(a,function(d){if(0<b.indexOf(d.id))return c=d.id,!0;b.push(d.id)});return c},_processUrlParams:function(a){var b=this.urlParams.itemid||this.urlParams.webmap;b&&a.map.itemId!==b&&(a.map.mapOptions&&p.deleteMapOptions(a.map.mapOptions),a.map.itemId=b);this.urlParams.mode&&
(a.mode=this.urlParams.mode);a.map.mapOptions||(a.map.mapOptions={});this.urlParams.scale&&(a.map.mapOptions.scale=this.urlParams.scale);if(this.urlParams.level||this.urlParams.zoom)a.map.mapOptions.zoom=this.urlParams.level||this.urlParams.zoom}});E.getInstance=function(a,b){null===w?w=new E(a,b):(w.urlParams=a,w.options=b);return w};return E});