// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/topic dojo/Deferred dojo/on ./utils ./WidgetManager ./shared/AppVersionManager ./ConfigLoader ./tokenUtils ./portalUrlUtils ./portalUtils esri/config".split(" "),function(w,f,l,m,g,x,r,h,y,z,A,B,u,C,D){function v(a,c){var b=f.clone(a),d=h.widgetProperties;"undefined"===typeof c&&(c=!1);delete b.mode;h.visitElement(b,function(e,k){e.widgets?(delete e.isOnScreen,delete e.gid,"jimu.js/images/group_icon.png"===e.icon&&delete e.icon,
delete e.openType,k.isOnScreen&&e.panel&&h.isEqual(e.panel,b.widgetOnScreen.panel)&&delete e.panel):(e.icon&&e.icon===e.folderUrl+"images/icon.png?wab_dv\x3d"+window.deployVersion&&delete e.icon,delete e.panel,delete e.folderUrl,delete e.amdFolder,delete e.thumbnail,delete e.configFile,delete e.gid,delete e.isOnScreen,d.forEach(function(n){delete e[n]}),c?("undefined"===typeof e.openAtStart&&(e.openAtStart=!1),e.config||delete e.config):(e.visible&&delete e.visible,e.manifest&&e.label===e.manifest.label&&
delete e.label,e.isDefaultConfig&&(delete e.config,delete e.isDefaultConfig)),delete e.manifest)});delete b.rawAppConfig;delete b._ssl;delete b.getConfigElementById;delete b.getConfigElementsByName;delete b.getConfigElementByLabel;delete b.processNoUriWidgets;delete b.addElementId;delete b.getCleanConfig;delete b.visitElement;delete b.agolConfig;delete b._itemData;delete b.oldWabVersion;return b}var q=null;var t=w(null,{urlParams:null,appConfig:null,configFile:null,_configLoaded:!1,portalSelf:null,
constructor:function(a){this.urlParams=a||{};this.listenBuilderEvents();this.versionManager=new z;this.widgetManager=y.getInstance();this.configLoader=A.getInstance(this.urlParams,{versionManager:this.versionManager});"config"===this.urlParams.mode&&window.parent.setConfigViewerTopic&&f.isFunction(window.parent.setConfigViewerTopic)&&window.parent.setConfigViewerTopic(g);"preview"===this.urlParams.mode&&window.parent.setPreviewViewerTopic&&f.isFunction(window.parent.setPreviewViewerTopic)&&window.parent.setPreviewViewerTopic(g);
r(window,"resize",f.hitch(this,this._onWindowResize))},listenBuilderEvents:function(){g.subscribe("builder/widgetChanged",f.hitch(this,this._onWidgetChanged));g.subscribe("builder/groupChanged",f.hitch(this,this._onGroupChanged));g.subscribe("builder/widgetPoolChanged",f.hitch(this,this._onWidgetPoolChanged));g.subscribe("builder/openAtStartChange",f.hitch(this,this._onOpenAtStartChanged));g.subscribe("builder/onScreenOrderChanged",f.hitch(this,this._onScreenOrderChanged));g.subscribe("builder/layoutDefinitionChanged",
f.hitch(this,this._onLayoutDefinitionChanged));g.subscribe("builder/sceneViewChanged",f.hitch(this,this._onSceneViewChanged));g.subscribe("builder/mapOptionsChanged",f.hitch(this,this._onMapOptionsChanged));g.subscribe("builder/appAttributeChanged",f.hitch(this,this._onAppAttributeChanged));g.subscribe("builder/setAppConfig",f.hitch(this,this._onAppConfigSet));g.subscribe("builder/themeChanged",f.hitch(this,this._onThemeChanged));g.subscribe("builder/layoutChanged",f.hitch(this,this._onLayoutChanged));
g.subscribe("builder/styleChanged",f.hitch(this,this._onStyleChanged));g.subscribe("builder/syncExtent",f.hitch(this,this._onSyncExtent));g.subscribe("builder/loadingPageChanged",f.hitch(this,this._onLoadingPageChanged));g.subscribe("builder/templateConfigChanged",f.hitch(this,this._onTemplateConfigChanged));g.subscribe("builder/sharedThemeChanged",f.hitch(this,this._onSharedThemeChanged))},loadConfig:function(){if("preview"!==this.urlParams.mode&&"config"!==this.urlParams.mode)return this.configLoader.loadConfig().then(f.hitch(this,
function(a){this.portalSelf=this.configLoader.portalSelf;this.appConfig=this._addDefaultValues(a);window.appInfo.isRunInMobile=this._isRunInMobile();console.timeEnd("Load Config");a=this.getAppConfig();g.publish("appConfigLoaded",a);return a}),f.hitch(this,function(a){console.error(a);a&&a.message&&"string"===typeof a.message&&this._showErrorMessage(a)}))},_showErrorMessage:function(a){if(!1===a.isSelfOrigin){m.create("div",{"class":"app-error",innerHTML:h.sanitizeHTML(a.message||a)},document.body);
a=m.create("div",{"class":"app-error",innerHTML:h.sanitizeHTML(window.jimuNls.common.close)},document.body);m.setStyle(a,{"margin-top":"80px","padding-top":0,background:"none",cursor:"pointer"});r(a,"click",f.hitch(this,function(){window.close()}));m.setStyle(a,"display","none");a=m.create("div",{"class":"app-error"},document.body);m.setStyle(a,{"margin-top":"90px","padding-top":0,background:"none"});a=m.create("div",{"class":"app-error-advanced-button",innerHTML:h.sanitizeHTML(window.jimuNls.advancedOptions)},
a);m.setStyle(a,{margin:"0 auto 0 auto",padding:"8px 12px 8px 12px",color:"#666",background:"none",border:"1px solid #ccc",display:"inline-block","border-radius":"4px",cursor:"pointer"});r(a,"click",f.hitch(this,function(){m.setStyle(b,"display","block")}));a=window.location.href;var c=u.getStandardPortalUrl(window.location.origin);c=u.getArcgisOnlineUrl(c);a=a.replace(window.location.origin,c);a=window.jimuNls.proceedTo.replace("${value}","\x3ca href\x3d"+a+"\x3e"+a+"\x3c/a\x3e");var b=m.create("div",
{"class":"app-error",innerHTML:h.sanitizeHTML(a)},document.body);m.setStyle(b,{"margin-top":"140px",display:"none","padding-top":0,background:"none"});m.setStyle(jimuConfig.loadingId,"display","none")}else m.create("div",{"class":"app-error",innerHTML:h.sanitizeHTML("Unable to create map: "+(a.message||a))},document.body)},getAppConfig:function(){if(window.appInfo.isRunInMobile){var a=f.clone(this._getMobileConfig(this.appConfig));a._originConfig=f.clone(this.appConfig)}else a=f.clone(this.appConfig);
a.getConfigElementById=function(c){return h.getConfigElementById(this,c)};a.getConfigElementByLabel=function(c){return h.getConfigElementByLabel(this,c)};a.getConfigElementsByName=function(c){return h.getConfigElementsByName(this,c)};a.getCleanConfig=function(c){return this._originConfig?v(this._originConfig,c):v(this,c)};a.visitElement=function(c){h.visitElement(this,c)};return a},_onWindowResize:function(){var a=this._isRunInMobile();window.appInfo.isRunInMobile!==a&&(window.appInfo.isRunInMobile=
a,this.appConfig&&g.publish("appConfigChanged",this.getAppConfig(),"layoutChange"))},_isRunInMobile:function(){var a=m.getMarginBox(window.jimuConfig.layoutId);if(a.w<=window.jimuConfig.breakPoints[0]||a.h<=window.jimuConfig.breakPoints[0])return m.addClass(window.jimuConfig.layoutId,"jimu-ismobile"),!0;m.removeClass(window.jimuConfig.layoutId,"jimu-ismobile");return!1},_getMobileConfig:function(a){return h.mixinAppConfigPosition(a,a.mobileLayout)},_onWidgetChanged:function(a){var c=h.reCreateObject(a);
a=h.getConfigElementById(this.appConfig,a.id);!1!==c.inPanel||a.uri||(c.closeable=!0);for(var b in c)a[b]=c[b];delete a.isDefaultConfig;this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);g.publish("appConfigChanged",this.getAppConfig(),"widgetChange",c)},_onGroupChanged:function(a){var c=h.reCreateObject(a);a=h.getConfigElementById(this.appConfig,a.id);for(var b in c)a[b]=c[b];this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);
g.publish("appConfigChanged",this.getAppConfig(),"groupChange",c)},_onWidgetPoolChanged:function(a){a=h.reCreateObject(a);if(1===this.widgetManager.getControllerWidgets().length)this.appConfig.widgetPool.widgets=a.widgets,this.appConfig.widgetPool.groups=a.groups;else{var c=h.getConfigElementById(this.appConfig,a.controllerId);l.forEach(c.controlledWidgets,function(b){this._removeWidgetOrGroupFromPoolById(this.appConfig,b)},this);l.forEach(c.controlledGroups,function(b){this._removeWidgetOrGroupFromPoolById(this.appConfig,
b)},this);this.appConfig.widgetPool.widgets="undefined"===typeof this.appConfig.widgetPool.widgets?a.widgets:this.appConfig.widgetPool.widgets.concat(a.widgets);this.appConfig.widgetPool.groups="undefined"===typeof this.appConfig.widgetPool.groups?a.groups:this.appConfig.widgetPool.groups.concat(a.groups);this.configLoader.addNeedValues(this.appConfig);c.controlledWidgets=l.map(a.widgets,function(b){return b.id});c.controlledGroups=l.map(a.groups,function(b){return b.id})}this.configLoader.addNeedValues(this.appConfig);
this._addDefaultValues(this.appConfig);g.publish("appConfigChanged",this.getAppConfig(),"widgetPoolChange",a)},_removeWidgetOrGroupFromPoolById:function(a,c){l.some(a.widgetPool.widgets,function(b,d){if(b.id===c)return a.widgetPool.widgets.splice(d,1),!0});l.some(a.widgetPool.groups,function(b,d){if(b.id===c)return a.widgetPool.groups.splice(d,1),!0})},_onOpenAtStartChanged:function(a){var c=h.reCreateObject(a),b=this.appConfig;a.isOnScreen?(b=b.widgetOnScreen&&b.widgetOnScreen.widgets)&&0<b.length&&
l.forEach(b,f.hitch(this,function(d){d.id===a.id?d.openAtStart=!d.openAtStart:delete d.openAtStart})):((b=b.widgetPool)&&b.groups&&0<b.groups.length&&l.forEach(b.groups,f.hitch(this,function(d){d.id===a.id?d.openAtStart=!d.openAtStart:delete d.openAtStart})),b&&b.widgets&&0<b.widgets.length&&l.forEach(b.widgets,f.hitch(this,function(d){d.id===a.id?d.openAtStart=!d.openAtStart:delete d.openAtStart})));g.publish("appConfigChanged",this.getAppConfig(),"openAtStartChange",c)},_onScreenOrderChanged:function(a){var c=
h.reCreateObject(a);l.forEach(this.appConfig.widgetOnScreen.widgets,function(b){b.isController||(!1!==b.inPanel||!0!==b.closeable)&&!0!==b.inPanel&&b.uri||l.some(c,function(d){if(b.id===d.id)return b.position=d.position,!0})},this);g.publish("appConfigChanged",this.getAppConfig(),"onScreenOrderChange",c)},_onAppAttributeChanged:function(a){a=h.reCreateObject(a);f.mixin(this.appConfig,a);this.configLoader.processProxy(this.appConfig);this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);
g.publish("appConfigChanged",this.getAppConfig(),"attributeChange",a)},_onLoadingPageChanged:function(a){a=h.reCreateObject(a);if("backgroundColor"in a)this.appConfig.loadingPage.backgroundColor=a.backgroundColor;else if("backgroundImage"in a){var c=this.appConfig.loadingPage.backgroundImage||{};this.appConfig.loadingPage.backgroundImage=f.mixin(c,a.backgroundImage)}else"loadingGif"in a&&(c=this.appConfig.loadingPage.loadingGif||{},this.appConfig.loadingPage.loadingGif=f.mixin(c,a.loadingGif));this.configLoader.addNeedValues(this.appConfig);
this._addDefaultValues(this.appConfig);g.publish("appConfigChanged",this.getAppConfig(),"loadingPageChange",a)},_onTemplateConfigChanged:function(a){a=h.reCreateObject(a);this.appConfig.templateConfig=a;this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);g.publish("appConfigChanged",this.getAppConfig(),"templateConfigChange",a)},_onLayoutDefinitionChanged:function(a){a=h.reCreateObject(a);h.isEqual(this.appConfig.layoutDefinition,a.layoutDefinition)||(this.appConfig.layoutDefinition=
a.layoutDefinition,this.appConfig.widgetOnScreen.groups=h.handleGridLayoutOnScreenGroupChange(this.appConfig.widgetOnScreen.groups,a.groupIds),this.configLoader.addNeedValues(this.appConfig),this._addDefaultValues(this.appConfig),g.publish("appConfigChanged",this.getAppConfig(),"layoutDefinitionChange",a.layoutDefinition))},_onSceneViewChanged:function(a){a=h.reCreateObject(a);a.itemId&&a.itemId!==this.appConfig.map.itemId&&this.appConfig.map.mapOptions&&h.deleteMapOptions(this.appConfig.map.mapOptions);
f.mixin(this.appConfig.map,a);this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);g.publish("appConfigChanged",this.getAppConfig(),"mapChange",a)},_onMapOptionsChanged:function(a){a=h.reCreateObject(a);this.appConfig.map.mapOptions||(this.appConfig.map.mapOptions={});f.mixin(this.appConfig.map.mapOptions,a);g.publish("appConfigChanged",this.getAppConfig(),"mapOptionsChange",a)},_onThemeChanged:function(a){this._getAppConfigFromTheme(a).then(f.hitch(this,function(c){this.appConfig=
c;g.publish("appConfigChanged",this.getAppConfig(),"themeChange",a.getName())}))},_onLayoutChanged:function(a){this.appConfig=h.mixinAppConfigPosition(this.appConfig,a.layoutConfig);this.appConfig.layoutDefinition=a.layoutConfig.layoutDefinition;this.configLoader.addNeedValues(this.appConfig);this._addDefaultValues(this.appConfig);this._addDefaultPanelAndPosition(this.appConfig);g.publish("appConfigChanged",this.getAppConfig(),"layoutChange",a.name)},_onStyleChanged:function(a){this.appConfig.theme.styles=
this._genStyles(this.appConfig.theme.styles,a.name);a.isCustom?this.appConfig.theme.customStyles={mainBackgroundColor:a.styleColor}:(delete this.appConfig.theme.customStyles,delete this.appConfig.titleColor,this.appConfig.theme.sharedTheme={isPortalSupport:this.appConfig.theme.sharedTheme.isPortalSupport,useHeader:!1,useLogo:!1});g.publish("appConfigChanged",this.getAppConfig(),"styleChange",a.name)},_onSharedThemeChanged:function(a){var c=this.appConfig.theme.sharedTheme;a=h.reCreateObject(a);a.useHeader&&
!c.useHeader&&(this.portalSelf.portalProperties&&this.portalSelf.portalProperties.sharedTheme?(this.appConfig.theme.customStyles={mainBackgroundColor:this.portalSelf.portalProperties.sharedTheme.header.background},this.appConfig.titleColor=this.portalSelf.portalProperties.sharedTheme.header.text,this._onAppAttributeChanged({titleColor:this.appConfig.titleColor})):console.error("Portal does not support sharedTheme."));!a.useHeader&&c.useHeader&&(delete this.appConfig.titleColor,this._onAppAttributeChanged({titleColor:this.appConfig.titleColor}));
a.useLogo&&!c.useLogo&&(this.portalSelf.portalProperties&&this.portalSelf.portalProperties.sharedTheme?(this.appConfig.logo=this.portalSelf.portalProperties.sharedTheme.logo&&this.portalSelf.portalProperties.sharedTheme.logo.small?this.portalSelf.portalProperties.sharedTheme.logo.small:"images/app-logo.png",this.appConfig.logoLink=this.portalSelf.portalProperties.sharedTheme.logo.link,this._onAppAttributeChanged({logo:this.appConfig.logo,logoLink:this.appConfig.logoLink})):console.error("Portal does not support sharedTheme."));
!a.useLogo&&c.useLogo&&this._onAppAttributeChanged({logo:this.appConfig.logo});f.mixin(c,a);g.publish("appConfigChanged",this.getAppConfig(),"sharedThemeChange",a)},_onSyncExtent:function(a){g.publish("syncExtent",a)},_genStyles:function(a,c){var b=[];b.push(c);l.forEach(a,function(d){0>b.indexOf(d)&&b.push(d)});return b},_getAppConfigFromTheme:function(a){var c=new x,b=[],d=this.getAppConfig().getCleanConfig();d.mode=this.urlParams.mode;l.forEach(d.widgetPool.groups,function(n){delete n.panel},this);
if(a.appConfig){var e=f.clone(a.appConfig);e.map=d.map;e.map.position=a.appConfig.map.position;this._copyPoolToThemePool(d,e);e.links=d.links;e.title=d.title;e.subtitle=d.subtitle;e.logo=d.logo}else{var k=a.getCurrentLayout();b=a.getCurrentStyle();e=f.clone(d);k=f.clone(k.layoutConfig);e.widgetOnScreen=k.widgetOnScreen;k.widgetPool&&(l.forEach(k.widgetPool.widgets,function(n){n.isPreconfiguredInTheme=!0}),l.forEach(k.widgetPool.groups,function(n){n.isPreconfiguredInTheme=!0}));this._copyPoolToThemePool(d,
k);e.widgetPool=k.widgetPool;k.map&&k.map.position&&(e.map.position=k.map.position);e.mobileLayout=k.mobileLayout;e.layoutDefinition=k.layoutDefinition;b=this._genStyles(l.map(a.getStyles(),function(n){return n.name}),b.name);e.theme={name:a.getName(),styles:b,version:a.getVersion()};this.portalSelf.portalProperties&&this.portalSelf.portalProperties.sharedTheme?(e.theme.sharedTheme={useHeader:!0,useLogo:!0,isPortalSupport:!0},e.theme.customStyles={mainBackgroundColor:this.portalSelf.portalProperties.sharedTheme.header.background}):
(e.theme.sharedTheme={useHeader:!1,useLogo:!1,isPortalSupport:!1},e.theme.customStyles={mainBackgroundColor:""});e.titleColor=d.titleColor;e.logoLink=d.logoLink}this.configLoader.addNeedValues(e);this.configLoader.loadWidgetsManifest(e).then(f.hitch(this,function(){this._addDefaultValues(e);c.resolve(e)}));return c},_copyPoolToThemePool:function(a,c){var b=a.widgetPool;c.widgetPool||(c.widgetPool={});a=c.widgetPool;var d=l.filter(a.widgets,function(p){if(p.isPreconfiguredInTheme||!l.some(b.widgets,
function(E){return E.name===p.name}))return!0}),e=l.filter(a.groups,function(p){return p.isPreconfiguredInTheme}),k=l.filter(b.widgets,function(p){return!p.isPreconfiguredInTheme}),n=l.filter(b.groups,function(p){return!p.isPreconfiguredInTheme});k=this._getPoolWidgetsWithoutDuplicated(k,c.widgetOnScreen.widgets||[]);a.widgets=k.concat(d);a.groups=n.concat(e)},_getPoolWidgetsWithoutDuplicated:function(a,c){for(var b=f.clone(a),d=this.getAppConfig(),e=a.length-1;0<=e;e--)for(var k=c.length-1;0<=k;k--)if(c[k].uri){var n=
c[k].name;n||(n=h.getWidgetNameFromUri(c[k].uri));var p=d.getConfigElementById(a[e].id);a[e]&&a[e].name===n&&!1===p.supportMultiInstance&&(console.log("Widget",a[e].name,"is not copied to new theme because this widget exists in new theme."),b.splice(e,1))}return b},_onAppConfigSet:function(a){a=h.reCreateObject(a);window.appInfo.isRunInMobile=this._isRunInMobile();this.configLoader.processProxy(a);this.configLoader.addNeedValues(a);this._addDefaultValues(a);B.setPortalUrl(a.portalUrl);window.portalUrl=
a.portalUrl;this.appConfig?(a.map.itemId&&a.map.itemId!==this.appConfig.map.itemId&&h.deleteMapOptions(a.map.mapOptions),this.appConfig=a,g.publish("appConfigChanged",this.getAppConfig(),"resetConfig",a)):(this.appConfig=a,C.getPortal(a.portalUrl).loadSelfInfo().then(f.hitch(this,function(c){this.portalSelf=c;g.publish("appConfigLoaded",this.getAppConfig())})))},_addDefaultValues:function(a){this._addDefaultPortalUrl(a);this._addDefaultGeometryService(a);this._addDefaultStyle(a);this._addDefaultMap(a);
this._addDefaultVisible(a);this._addDefaultSharedTheme(a);"undefined"===typeof a.widgetOnScreen&&(a.widgetOnScreen={});"undefined"===typeof a.widgetPool&&(a.widgetPool={});this._addDefaultPanelAndPosition(a);this._addDefaultOfWidgetGroup(a);(a.widgetPool.widgets&&0<a.widgetPool.widgets.length&&void 0===a.widgetPool.widgets[0].index||a.widgetPool.groups&&0<a.widgetPool.groups.length&&void 0===a.widgetPool.groups[0].index)&&this._addIndexForWidgetPool(a);return a},_addDefaultPortalUrl:function(a){"undefined"===
typeof a.portalUrl&&(a.portalUrl="http://www.arcgis.com/");a.portalUrl&&"/"!==a.portalUrl.substr(a.portalUrl.length-1)&&(a.portalUrl+="/")},_addDefaultGeometryService:function(a){var c=a&&a.geometryService;c=c&&"string"===typeof c&&f.trim(c)?f.trim(c):this.portalSelf.helperServices.geometry.url;a.geometryService=c;D.geometryServiceUrl=c;h.setGlobalGeometryService(a.geometryService)},_addDefaultStyle:function(a){!a.theme||a.theme.styles&&0!==a.theme.styles.length||(a.theme.styles=["default"])},_addDefaultMap:function(a){a.map.id=
"map";"undefined"===typeof a.map["3D"]&&"undefined"===typeof a.map["2D"]&&(a.map["2D"]=!0);"undefined"===typeof a.map.position&&(a.map.position={left:0,right:0,top:0,bottom:0});"undefined"===typeof a.map.portalUrl&&(a.map.portalUrl=a.portalUrl)},_addDefaultVisible:function(a){h.visitElement(a,function(c){void 0===c.visible&&(c.visible=!0)})},_addDefaultSharedTheme:function(a){a.theme.sharedTheme?("undefined"===typeof a.theme.sharedTheme.useHeader&&(a.theme.sharedTheme.useHeader=!1),"undefined"===
typeof a.theme.sharedTheme.useLogo&&(a.theme.sharedTheme.useLogo=!1)):a.theme.sharedTheme={useHeader:!1,useLogo:!1}},_addDefaultPanelAndPosition:function(a){this._addOnScreenDefaultPanelAndPosition(a);this._addPoolDefaultPanelAndPosition(a)},_addOnScreenDefaultPanelAndPosition:function(a){var c;if(a=a.widgetOnScreen){var b=a.panel&&a.panel.positionRelativeTo?a.panel.positionRelativeTo:"map";"undefined"===typeof a.panel||"undefined"===typeof a.panel.uri?a.panel={uri:"jimu/OnScreenWidgetPanel",position:{relativeTo:b}}:
"undefined"===typeof a.panel.position?a.panel.position={relativeTo:b}:"undefined"===typeof a.panel.position.relativeTo&&(a.panel.position.relativeTo=b);if(a.widgets)for(b=0;b<a.widgets.length;b++)a.widgets[b].position||(a.widgets[b].position={}),a.widgets[b].position.relativeTo||(a.widgets[b].position.relativeTo=a.widgets[b]&&a.widgets[b].positionRelativeTo?a.widgets[b].positionRelativeTo:"map"),!0!==a.widgets[b].inPanel||a.widgets[b].panel||(a.widgets[b].panel=f.clone(a.panel),a.widgets[b].panel.position=
a.widgets[b].position,a.widgets[b].panel.position.relativeTo=a.widgets[b].position.relativeTo);if(a.groups)for(b=0;b<a.groups.length;b++)for(a.groups[b].panel||(a.groups[b].panel=a.panel),a.groups[b].panel&&!a.groups[b].panel.position&&(a.groups[b].panel.position={}),a.groups[b].panel.position.relativeTo||(a.groups[b].panel.position.relativeTo=a.groups[b].panel.positionRelativeTo?a.groups[b].panel.positionRelativeTo:"map"),a.groups[b].widgets||(a.groups[b].widgets=[]),c=0;c<a.groups[b].widgets.length;c++)a.groups[b].widgets[c].panel=
a.groups[b].panel}},_addPoolDefaultPanelAndPosition:function(a){var c,b=a.widgetPool;if(b){var d=b.panel&&b.panel.positionRelativeTo?b.panel.positionRelativeTo:"map";"undefined"===typeof b.panel||"undefined"===typeof b.panel.uri?b.panel={uri:"jimu/OnScreenWidgetPanel",position:{relativeTo:d}}:"undefined"===typeof b.panel.position?b.panel.position={relativeTo:d}:"undefined"===typeof b.panel.position.relativeTo&&(b.panel.position.relativeTo=d);if(b.groups)for(d=0;d<b.groups.length;d++)for(b.groups[d].panel?
b.groups[d].panel.position.relativeTo||(b.groups[d].panel.position.relativeTo=b.groups[d].panel.positionRelativeTo?b.groups[d].panel.positionRelativeTo:"map"):b.groups[d].panel=b.panel,b.groups[d].widgets||(b.groups[d].widgets=[]),c=0;c<b.groups[d].widgets.length;c++)b.groups[d].widgets[c].panel=b.groups[d].panel;if(b.widgets)for(d=0;d<b.widgets.length;d++)!1===b.widgets[d].inPanel?(c=b.widgets[d].positionRelativeTo?b.widgets[d].positionRelativeTo:"map",b.widgets[d].position)?b.widgets[d].position.relativeTo||
(b.widgets[d].position.relativeTo=c):b.widgets[d].position={relativeTo:c}:b.widgets[d].panel||(b.widgets[d].panel=a.widgetPool.panel)}},_addDefaultOfWidgetGroup:function(a){h.visitElement(a,f.hitch(this,function(c,b){c.isOnScreen=b.isOnScreen;c.widgets?(c.gid=c.id,1===c.widgets.length?(c.label||(c.label=c.widgets[0].label?c.widgets[0].label:"Group"),c.icon||(c.icon=c.widgets[0].uri?this._getDefaultIconFromUri(c.widgets[0].uri):"jimu.js/images/group_icon.png")):(c.icon=c.icon?c.icon:"jimu.js/images/group_icon.png",
c.label=c.label?c.label:window.jimuNls.common.group+"_"+b.index)):(c.gid=b.groupId,c.uri&&h.processWidgetSetting(c))}))},_getDefaultIconFromUri:function(a){a=a.split("/");a.pop();return a.join("/")+"/images/icon.png"},_addIndexForWidgetPool:function(a){var c=0,b,d;if(a.widgetPool.widgets)for(b=0;b<a.widgetPool.widgets.length;b++)a.widgetPool.widgets[b].index=c,c++;if(a.widgetPool.groups)for(b=0;b<a.widgetPool.groups.length;b++)for(a.widgetPool.groups[b].index=c,c++,d=0;d<a.widgetPool.groups[b].widgets.length;d++)a.widgetPool.groups[b].widgets[d].index=
d}});t.getInstance=function(a){null===q?q=new t(a):a&&(q.urlParams=a);window.getAppConfig=f.hitch(q,q.getAppConfig);return q};return t});