// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/rest/query esri/rest/support/Query".split(" "),function(g,w,p,u,t,r,q,x,y){g.exportCSV=function(c,d,b){return g._createCSVStr(d,b).then(function(a){return g._download(c+".csv",a)})};g.exportCSVFromFeatureLayer=function(c,d,b){b=b||{};return g._getExportData(d,{datas:b.datas,fromClient:b.fromClient,outFields:b.outFields,filterExpression:b.filterExpression}).then(function(a){return g._formattedData(d,
a,{formatNumber:b.formatNumber,formatDate:b.formatDate,formatCodedValue:b.formatCodedValue}).then(function(f){return g.exportCSV(c,f.datas,f.columns)})})};g.exportCSVByAttributes=function(c,d,b,a){a=w.mixin({},a);a.datas=b;return g.exportCSVFromFeatureLayer(c,d,a)};g.exportCSVByGraphics=function(c,d,b,a){b=p.map(b,function(f){return f.attributes});return g.exportCSVByAttributes(c,d,b,a)};g._createCSVStr=function(c,d){var b=new r,a="",f=0,e=0,h="",k="";try{p.forEach(d,function(m){a=a+h+m;h=","});a+=
"\r\n";f=c.length;e=d.length;for(var n=0;n<f;n++){h="";for(var l=0;l<e;l++)(k=c[n][d[l]])||"number"===typeof k||(k=""),k&&/[",\r\n]/g.test(k)&&(k='"'+k.replace(/(")/g,'""')+'"'),a=a+h+k,h=",";a+="\r\n"}b.resolve(a)}catch(m){console.error(m),b.resolve("")}return b};g._isIE11=function(){return 11===q.has("ie")};g._isEdge=function(){return q.has("edge")};g._getDownloadUrl=function(c){return window.Blob&&window.URL&&window.URL.createObjectURL?(c=new Blob(["\ufeff"+c],{type:"text/csv"}),URL.createObjectURL(c)):
"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(c)};g._download=function(c,d){var b=new r;try{if(t("ie")&&10>t("ie")){var a=window.top.open("about:blank","_blank");a.document.write("sep\x3d,\r\n"+d);a.document.close();a.document.execCommand("SaveAs",!0,c);a.close()}else if(10===t("ie")||g._isIE11()||g._isEdge()){var f=new Blob(["\ufeff"+d],{type:"text/csv"});navigator.msSaveBlob(f,c)}else{var e=u.create("a",{href:g._getDownloadUrl(d),target:"_blank",download:c},document.body);if(t("safari")){var h=
document.createEvent("MouseEvents");h.initEvent("click",!0,!0);e.dispatchEvent(h)}else e.click();u.destroy(e)}b.resolve()}catch(k){b.reject(k)}return b};g._getExportData=function(c,d){var b=new r,a=null,f=d.datas;a=d.outFields;a&&a.length||(a=c.fields);f&&0<f.length?b.resolve({data:f||[],outFields:a}):d.fromClient?(f=p.map(c.graphics,function(e){return e.attributes}),b.resolve({data:f||[],outFields:a})):g._getExportDataFromServer(c,a,d).then(function(e){b.resolve({data:e||[],outFields:a})});return b};
g._getExportDataFromServer=function(c,d,b){var a=new r;if("esri.layers.FeatureLayer"!==c.declaredClass)return a.resolve([]),a;var f=new y;f.where=b.filterExpression||c.getDefinitionExpression&&c.getDefinitionExpression()||"1\x3d1";0<d.length?(d=p.map(d,function(e){return e.name}),f.outFields=d):f.outFields=["*"];f.returnGeometry=!1;x.executeQueryJSON(c.url,f).then(function(e){e=p.map(e.features,function(h){return h.attributes});a.resolve(e)},function(e){console.error(e);a.resolve([])});return a};
g._formattedData=function(c,d,b){var a=new r,f=[],e=d.data;d=d.outFields;for(var h=0,k=e.length;h<k;h++){for(var n={},l=0;l<d.length;l++){var m=d[l];n[m.alias||m.name]=g._getExportValue(e[h][m.name],m,c.objectIdField,c.typeIdField,e[h][c.typeIdField],c.types,b)}f.push(n)}c=p.map(d,function(v){return v.alias||v.name});a.resolve({datas:f,columns:c});return a};g._getExportValue=function(c,d,b,a,f,e,h){var k=!!d.domain&&h.formatCodedValue;h="esriFieldTypeDate"===d.type&&h.formatDate;var n=b&&d.name===
b;a=a&&d.name===a;return h?q.fieldFormatter.getFormattedDate(c):a?q.fieldFormatter.getTypeName(c,e):k?q.fieldFormatter.getCodedValue(d.domain,c):k||h||n||a?c:(k=null,b&&e&&0<e.length&&(b=(b=p.filter(e,function(l){return l.id===f}))&&b[0])&&b.domains&&b.domains[d.name]&&b.domains[d.name].codedValues&&(k=q.fieldFormatter.getFormattedCodedValue(b.domains[d.name],c)),null!==k?k:c)}});