// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/json dojo/Deferred esri/rest/support/Query esri/rest/query ./jsonConverters".split(" "),function(n,f,p,u,m,v,w,z){function x(a,b){var c="",d=b.length,k=a.length,h="",g="";try{p.forEach(a,function(l){c="string"===typeof l?c+h+l:c+h+(l.alias||l.name);h=","});c+="\r\n";for(var q=0;q<d;q++){h="";var A=b[q];for(var r=0;r<k;r++){var t=a[r];(g=A["string"===typeof t?t:t.name])||"number"===typeof g||(g="");g&&/[",\r\n]/g.test(g)&&(g='"'+g.replace(/(")/g,
'""')+'"');c=c+h+g;h=","}c+="\r\n"}return c}catch(l){return""}}var e={createDataSource:function(a){return a.type===e.TYPE_TABLE?new B(a):a.type===e.TYPE_FEATURESET?new C(a):null},TYPE_TABLE:"table",TYPE_FEATURESET:"FeatureSet",FORMAT_CSV:"CSV",FORMAT_FEATURESET:"FeatureSet",FORMAT_GEOJSON:"GeoJSON"},y=n(null,{filename:void 0,suffix:".txt",format:void 0,nls:void 0,constructor:function(){this.nls=window.jimuNls.exportTo},getExportString:function(){},getSupportExportFormats:function(){},setFormat:function(a){this.format=
a},download:function(){this.getExportString().then(f.hitch(this,function(a){var b=this.filename+this.suffix;try{var c=!!new Blob}catch(d){c=!1}c?(a=new Blob([a],{type:"text/plain;charset\x3dutf-8"}),saveAs(a,b)):saveTextAs(a,b,"utf-8")}))},exportToPortal:function(a,b){}}),C=n(y,{featureSet:null,constructor:function(a){this.inherited(arguments);this.featureSet=a.data;this.url=a.url;this.filename=a.filename},getExportString:function(){if(this.format===e.FORMAT_CSV)return this.suffix=".csv",this._getAsCSVString();
if(this.format===e.FORMAT_FEATURESET)return this.suffix=".json",this._getAsFeatureSetString();if(this.format===e.FORMAT_GEOJSON)return this.suffix=".geojson",this._getAsGeoJsonString();var a=new m;a.resolve("");return a},getSupportExportFormats:function(){return[{value:e.FORMAT_CSV,label:this.nls.toCSV},{value:e.FORMAT_FEATURESET,label:this.nls.toFeatureCollection},{value:e.FORMAT_GEOJSON,label:this.nls.toGeoJSON}]},_getFeatureSet:function(){var a=new m;if(this.featureSet)a.resolve(this.featureSet);
else if(this.url){var b=new v;b.returnGeometry=!0;b.outFields=["*"];w.executeQueryJSON(this.url,b).then(f.hitch(this,function(c){a.resolve(c)}),f.hitch(this,function(){a.resolve(null)}))}else a.resolve(null);return a},_getAsFeatureSetString:function(){return this._getFeatureSet().then(f.hitch(this,function(a){var b="";a&&(a=a.toJson())&&(b=u.stringify(a));return b}))},_getAsGeoJsonString:function(){return this._getFeatureSet().then(f.hitch(this,function(a){var b="";a&&(a=(new z.esriConverter).toGeoJson(a))&&
(b=u.stringify(a));return b}))},_getAsCSVString:function(){return this._getFeatureSet().then(f.hitch(this,function(a){var b="";a&&(b=this._createCSVFromFeatureSet(a));return b}))},_createCSVFromFeatureSet:function(a){var b=a.features,c=[],d;if(a.fieldAliases)for(d in a.fieldAliases)a.fieldAliases.hasOwnProperty(d)&&c.push({name:d,alias:a.fieldAliases[d]});else for(d in b=b[0].attributes,b)b.hasOwnProperty(d)&&c.push({name:d});a=p.map(a.features,function(k){return k.attributes});return x(c,a)}}),B=
n(y,{table:null,constructor:function(a){this.inherited(arguments);this.table=a.data;this.url=a.url;this.filename=a.filename},getExportString:function(){if(this.format===e.FORMAT_CSV)return this.suffix=".csv",this._getAsCSVString();var a=new m;a.resolve("");return a},getSupportExportFormats:function(){return[{value:e.FORMAT_CSV,label:this.nls.toCSV}]},_getTableData:function(){var a=new m;if(this.table)a.resolve(this.table);else if(this.url){var b=new v;b.outFields=["*"];w.executeQueryJSON(this.url,
b).then(f.hitch(this,function(c){var d={};d.fields=c.fields;d.datas=p.map(c.features,function(k){return k.attributes});a.resolve(d)}),f.hitch(this,function(){a.resolve(null)}))}else a.resolve(null);return a},_getAsCSVString:function(){return this._getTableData().then(f.hitch(this,function(a){var b="";a&&(b="\ufeff"+x(a.fields,a.datas));return b}))}});return e});