// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/topic dojo/on dojo/keys esri/geometry/Extent esri/geometry/Point ./utils ./dijit/LoadingShelter ./AppStateManager ./WebSceneLoader esri/Viewpoint".split(" "),function(r,e,h,n,f,p,t,u,v,q,w,x,y,k){var l=null,m=r(null,{appConfig:null,mapDivId:"",map:null,previousInfoWindow:null,mobileInfoWindow:null,isMobileInfoWindow:!1,layerInfosObj:null,constructor:function(a,c){this.appConfig=a.appConfig;this.urlParams=a.urlParams;
this.id=this.mapDivId=c;this.appStateManager=x.getInstance(this.urlParams);f.subscribe("appConfigChanged",e.hitch(this,this.onAppConfigChanged));f.subscribe("changeMapPosition",e.hitch(this,this.onChangeMapPosition));f.subscribe("syncViewpoint",e.hitch(this,this.onSyncViewpoint));p(window,"resize",e.hitch(this,this.onWindowResize));p(window,"beforeunload",e.hitch(this,this.onBeforeUnload))},showMap:function(){this._showMap(this.appConfig)},_showMap:function(a){console.time("Load Map");this.loading=
new w;this.loading.placeAt(this.mapDivId);this.loading.startup();a.map["3D"]?a.map.itemId?this._show3DWebScene(a):console.log("No webscene found. Please set map.itemId in config.json."):a.map.itemId?this._show2DWebMap(a):console.log("No webmap found. Please set map.itemId in config.json.")},onBeforeUnload:function(){this.appStateManager.saveWabAppState(this.map,this.layerInfosObj)},onWindowResize:function(){this.map&&this.map.resize&&(this.map.resize(),this.resetInfoWindow(!1))},getMapInfoWindow:function(){return{mobile:this._mapMobileInfoWindow,
bigScreen:this._mapInfoWindow}},resetInfoWindow:function(a){a&&(this._mapInfoWindow=this.map.infoWindow,this._mapMobileInfoWindow&&this._mapMobileInfoWindow.destroy(),this.isMobileInfoWindow=!1);window.appInfo.isRunInMobile&&!this.isMobileInfoWindow?this.isMobileInfoWindow=!0:!window.appInfo.isRunInMobile&&this.isMobileInfoWindow&&(this.isMobileInfoWindow=!1)},onChangeMapPosition:function(a){var c=e.clone(this.mapPosition);e.mixin(c,a);this.setMapPosition(c)},setMapPosition:function(a){this.mapPosition=
a;a=q.getPositionStyle(a);n.setStyle(this.mapDivId,a);this.map&&this.map.resize&&this.map.resize()},getMapPosition:function(){return this.mapPosition},onSyncViewpoint:function(a){this.sceneView&&(this.sceneView.viewpoint=a.clone())},_visitConfigMapLayers:function(a,c){h.forEach(a.map.basemaps,function(d,b){d.isOperationalLayer=!1;c(d,b)},this);h.forEach(a.map.operationallayers,function(d,b){d.isOperationalLayer=!0;c(d,b)},this)},_destroySceneView:function(){if(this.sceneView)try{this.sceneView.destroy()}catch(a){console.error(a)}this.sceneView=
null;window._sceneView=null},_show3DWebScene:function(a){var c=a.map.portalUrl,d=a.map.itemId;this._destroySceneView();y.createMap(this.mapDivId,c,d).then(e.hitch(this,function(b){this._publishSceneViewEvent(b);if(a.map.mapOptions)if((b=a.map.mapOptions.initialState)&&b.viewpoint)try{var g=k.fromJSON(b.viewpoint);g&&(this.sceneView.map.initialViewProperties.viewpoint=g,this.sceneView.viewpoint=g.clone())}catch(z){console.error(z)}else this.sceneView.map.initialViewProperties.viewpoint=this.sceneView.viewpoint}),
e.hitch(this,function(){this.loading&&this.loading.destroy();f.publish("mapCreatedFailed")}))},_publishSceneViewEvent:function(a){window._sceneView=a;console.timeEnd("Load Map");this.loading&&this.loading.destroy();this.sceneView?(this.sceneView=a,console.log("sceneView changed"),f.publish("sceneViewChanged",this.sceneView)):(this.sceneView=a,console.log("sceneView loaded"),f.publish("sceneViewLoaded",this.sceneView))},_show2DWebMap:function(a){a.map.mapOptions||(a.map.mapOptions={});var c=this._processMapOptions(a.map.mapOptions)||
{};c.isZoomSlider=!1;q.createWebMap(a.map.portalUrl,a.map.itemId,this.mapDivId,{mapOptions:c,bingMapsKey:a.bingMapsKey,usePopupManager:!0}).then(e.hitch(this,function(d){var b=d.map;b.hideZoomSlider();b.infoWindow.resize(270,316);b.itemId=a.map.itemId;b.itemInfo=d.itemInfo;b.webMapResponse=d;b.enableSnapping({snapKey:t.copyKey});n.setStyle(b.root,"zIndex",0);b._initialExtent=b.extent;h.forEach("extent center marker find query scale level".split(" "),function(g){},this);this._publishMapEvent(b)}),
e.hitch(this,function(){this.loading&&this.loading.destroy();f.publish("mapCreatedFailed")}))},_processMapOptions:function(a){if(a)return a.lods||delete a.lods,a.lods&&0===a.lods.length&&delete a.lods,a=e.clone(a),a.extent&&(a.extent=new u(a.extent)),a.center&&!e.isArrayLike(a.center)&&(a.center=new v(a.center)),a},onAppConfigChanged:function(a,c,d){this.appConfig=a;"mapChange"===c?this._recreateMap(a):"mapOptionsChange"===c&&d.initialState&&(a=d.initialState.viewpoint)&&(this.sceneView.map.initialViewProperties.viewpoint=
k.fromJSON(a),this.sceneView.animateTo(k.fromJSON(a)))},_recreateMap:function(a){this.sceneView&&(f.publish("beforeSceneViewDestory",this.sceneView),this._destroySceneView());this._showMap(a)},disableWebMapPopup:function(){},enableWebMapPopup:function(){}});m.getInstance=function(a,c){null===l&&(l=new m(a,c));return l};return m});