// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dijit/_WidgetBase ./utils".split(" "),function(k,b,l,d,f,m,n){return k(m,{"class":"jimu-widget-onscreen-icon",postCreate:function(){this.inherited(arguments);this.iconNode=d.create("img",{src:this.widgetConfig.icon},this.domNode);window.isRTL&&this.widgetConfig.mirrorIconForRTL&&d.addClass(this.iconNode,"jimu-flipx");d.setAttr(this.domNode,"title",this.widgetConfig.label);this.own(f(this.domNode,"click",b.hitch(this,
function(){this.onClick()})));this.position=b.clone(this.widgetConfig.position);"map"===this.widgetConfig.position.relativeTo&&this.own(f(this.sceneView,"resize",b.hitch(this,function(){var a=b.clone(this.position);delete a.width;delete a.height;this.panel&&this.panel.setPosition(a)})));this.state="closed"},startup:function(){this.inherited(arguments)},onClick:function(){"closed"===this.state?this.switchToOpen():this.switchToClose()},moveTo:function(a){var c={left:"auto",right:"auto",bottom:"auto",
top:"auto",width:"auto",height:"auto"};c=b.mixin(c,n.getPositionStyle(a));delete c.width;delete c.height;d.setStyle(this.domNode,c);this.position=b.clone(a);this.widgetConfig&&this.widgetConfig.panel&&(this.widgetConfig.panel.position=b.clone(a),this.widgetConfig.position=b.clone(a));this.panel&&this.panel.setPosition(b.clone(a));this.widget&&this.widget.setPosition(this.getOffPanelWidgetPosition(this.widget))},destroy:function(){this.panel?this.panelManager.destroyPanel(this.panel):this.widget&&
this.widgetManager.destroyWidget(this.widget);this.inherited(arguments)},switchToOpen:function(){this.state="opened";this.panelManager.closeAllPanelsInGroup(this.widgetConfig.gid);l.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){a.closeable&&this.widgetManager.closeWidget(a)},this);d.addClass(this.domNode,"jimu-state-selected");this._showLoading();!1===this.widgetConfig.inPanel?this.widgetManager.loadWidget(this.widgetConfig).then(b.hitch(this,function(a){this.widget=a;a.setPosition(this.getOffPanelWidgetPosition(a));
this.widgetManager.openWidget(a);this.own(f(a,"close",b.hitch(this,function(){this.switchToClose()})));this._hideLoading()})):this.panelManager.showPanel(b.clone(this.widgetConfig)).then(b.hitch(this,function(a){this.panel=a;this.own(f(a,"close",b.hitch(this,function(){this.switchToClose()})));this._hideLoading()}))},switchToClose:function(){this.state="closed";d.removeClass(this.domNode,"jimu-state-selected");!1===this.widgetConfig.inPanel?this.widgetManager.closeWidget(this.widget):this.panelManager.closePanel(this.panel)},
getOffPanelWidgetPosition:function(a){var c={relativeTo:a.position.relativeTo},e=d.getMarginBox(this.domNode);a=this.widgetManager.getWidgetMarginBox(a);var g=d.getMarginBox("map"===c.relativeTo?this.sceneView.map.id:jimuConfig.layoutId),h=e.t+e.h+1;h+a.h>g.h?c.bottom=g.h-e.t+1:c.top=h;window.isRTL?c.right=0>e.l+e.w-a.w?0:e.l+e.w-a.w:e.l+a.w>g.w?c.right=0:c.left=e.l;return c},_showLoading:function(){d.setAttr(this.iconNode,"src",require.toUrl("jimu")+"/images/loading_circle.gif")},_hideLoading:function(){d.setAttr(this.iconNode,
"src",this.widgetConfig.icon)}})});