// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/config dojo/Deferred dojo/topic dojo/json esri/request ./utils ./portalUrlUtils ./tokenUtils".split(" "),function(u,e,r,v,l,B,C,m,y,k,q){var E=u([],{declaredClass:"jimu.Portal",selfUrl:null,user:null,selfInfo:null,portalUrl:null,credential:null,constructor:function(a){this.portalUrl=k.getStandardPortalUrl(a);this.selfUrl=k.getPortalSelfInfoUrl(a)},loadSelfInfo:function(){var a=new l,c={query:{f:"json"},responseType:"json",callbackParamName:"callback",
cacheBust:!0};this.isValidCredential()&&(c.query.token=this.credential.token);m(this.selfUrl,c).then(e.hitch(this,function(b){b=b.data;var d=b.user;delete b.user;e.mixin(this,b);b.user=d;a.resolve(b)}),e.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_checkCredential:function(){var a=q.isValidCredential(this.credential);a||this.clearCredentialAndUser();return a},isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||
(this.credential=q.getPortalCredential(this.portalUrl))},signIn:function(){var a=new l;this.updateCredential();this.isValidCredential()?setTimeout(e.hitch(this,function(){a.resolve(this.credential)}),0):a=q.signInPortal(this.portalUrl);return a},haveSignIn:function(){return q.userHaveSignInPortal(this.portalUrl)},clearCredentialAndUser:function(){this.user=this.credential=null},getSigninSettingsOfSelfInfo:function(){this.updateCredential();var a=new l,c=this.selfUrl+"/signinSettings";this.isValidCredential()?
m(c,{handleAs:"json",query:{f:"json",token:this.credential.token},callbackParamName:"callback"}).then(e.hitch(this,function(b){a.resolve(b.data)}),e.hitch(this,function(b){a.reject(b)})):a.resolve({});return a},getUser:function(){this.updateCredential();var a=new l;this.user&&"jimu.PortalUser"===this.user.declaredClass?setTimeout(e.hitch(this,function(){this.user.updateCredential();a.resolve(this.user)}),0):this.isValidCredential()?this.credential.userId?this._getUser(this.credential.userId).then(e.hitch(this,
function(c){this.user=c;a.resolve(this.user)}),e.hitch(this,function(c){console.error(c);a.reject(c)})):q.getUserIdByToken(this.credential.token,this.portalUrl).then(e.hitch(this,function(c){this.credential.userId=c;this._getUser(this.credential.userId).then(e.hitch(this,function(b){this.user=b;a.resolve(this.user)}),e.hitch(this,function(b){console.error(b);a.reject(b)}))}),e.hitch(this,function(c){console.error(c);a.reject(c)})):setTimeout(e.hitch(this,function(){a.reject("credential is null.")}),
0);return a},queryItems:function(a){this.updateCredential();var c=new l,b=k.getBaseSearchUrl(this.portalUrl),d={f:"json"};a&&(d=e.mixin(d,a));this.isValidCredential()&&(d.token=this.credential.token);d.sortField||d.sortOrder||(d.sortField="title",d.sortOrder="asc");m(b,{responseType:"json",query:d,callbackParamName:"callback"}).then(e.hitch(this,function(f){f=f.data;f.results=r.map(f.results,e.hitch(this,function(g){g.portalUrl=this.portalUrl;g.credential=this.credential;g.portal=this;return new w(g)}));
c.resolve(f)}),e.hitch(this,function(f){console.error(f);c.reject(f)}));return c},getItemData:function(a){this.updateCredential();a=k.getItemDataUrl(this.portalUrl,a);var c={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential()&&(c.query.token=this.credential.token);var b=new l;m(a,c).then(e.hitch(this,function(d){b.resolve(d.data)}),e.hitch(this,function(d){b.reject(d)}));return b},getItemById:function(a){var c=new l;this.updateCredential();a=k.getItemUrl(this.portalUrl,
a);var b={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential()&&(b.query.token=this.credential.token);m(a,b).then(e.hitch(this,function(d){d=d.data;d.portalUrl=this.portalUrl;d.credential=this.credential;d.portal=this;d=new w(d);c.resolve(d)}),e.hitch(this,function(d){console.error(d);c.reject(d)}));return c},getAppById:function(a){var c=new l;this.updateCredential();this.isValidCredential()?(a=k.getAppIdUrl(this.portalUrl,a),m(a,{responseType:"json",query:{f:"json",
token:this.credential.token}}).then(e.hitch(this,function(b){c.resolve(b.data)}),e.hitch(this,function(b){c.reject(b)}))):setTimeout(e.hitch(this,function(){c.reject("token is null.")}),0);return c},queryGroups:function(a){this.updateCredential();var c=new l,b=k.getBaseGroupUrl(this.portalUrl),d={f:"json"};a&&(d=e.mixin(d,a));this.isValidCredential()&&(d.token=this.credential.token);m(b,{responseType:"json",query:d,callbackParamName:"callback"}).then(e.hitch(this,function(f){f=f.data;f.results=r.map(f.results,
e.hitch(this,function(g){g.portalUrl=this.portalUrl;g.credential=this.credential;g.portal=this;return new x(g)}));c.resolve(f)}),e.hitch(this,function(f){console.error(f);c.reject(f)}));return c},registerApp:function(a,c,b){var d=new l;this.updateCredential();if(this.isValidCredential()){var f=this.credential&&this.credential.token,g=k.getOAuth2Url(this.portalUrl);m(g+"/registerApp",{query:{itemId:a,appType:c,redirect_uris:C.stringify(b),token:f,f:"json"},responseType:"json",method:"post"}).then(e.hitch(this,
function(h){d.resolve(h.data)}),e.hitch(this,function(h){d.reject(h)}))}else setTimeout(e.hitch(this,function(){d.reject("token is null.")}),0);return d},createAndRegisterApp:function(a){var c=new l;this.updateCredential();this.isValidCredential()?this.getUser().then(e.hitch(this,function(b){b.addItem({title:"ArcGIS Web AppBuilder",type:"Web Mapping Application",text:"",snippet:"",tags:"Registered App for OAuth"},"").then(e.hitch(this,function(d){d.success?this.registerApp(d.id,"browser",a).then(e.hitch(this,
function(f){c.resolve(f)}),e.hitch(this,function(f){console.error(f);c.reject(f)})):c.reject("create app failed")}),e.hitch(this,function(d){console.error(d);c.reject(d)}))}),e.hitch(this,function(b){console.error(b);c.reject(b)})):setTimeout(e.hitch(this,function(){c.reject("token is null.")}),0);return c},_getUser:function(a){this.updateCredential();var c=new l;a=k.getUserUrl(this.portalUrl,a);var b={query:{f:"json"},responseType:"json",callbackParamName:"callback"};this.isValidCredential()&&(b.query.token=
this.credential&&this.credential.token);m(a,b).then(e.hitch(this,function(d){d=d.data;d.portalUrl=this.portalUrl;d.credential=this.credential;d.portal=this;this.user=new D(d);c.resolve(this.user)}),e.hitch(this,function(d){console.error(d);c.reject(d)}));return c},getItemResources:function(a,c,b){b||(b=100);a=k.getStandardPortalUrl(a);a=k.getItemResourceUrl(a,c);return m({url:a,content:{f:"json",num:b}}).then(function(d){if(d&&d.resources)return d.resources})},addResource:function(a,c,b,d,f){a=k.getStandardPortalUrl(a);
var g=this.getPortal(a),h=new FormData;h.append("file",b,d);h.append("fileName",d);h.append("f","json");var n="";f?(h.append("resourcesPrefix",f),n=f+"/"+d):n=d;return g.getItemById(c,!0).then(function(t){t=k.getUserContentItemUrl(a,t.owner,c);return m({url:t+"/addResources",form:h}).then(function(p){var z="";p&&p.success&&(z=k.getItemResourceUrl(a,"${itemId}",n));return z},function(p){console.error(p.message||p);return p})})},removeResources:function(a,c,b,d){var f={resource:d?d+"/"+b:b,f:"json"};
a=k.getStandardPortalUrl(a);return this.getPortal(a).getItemById(c,!0).then(function(g){g=k.getUserContentItemUrl(a,g.owner,c);return m({url:g+"/removeResources",content:f},{usePost:!0}).then(function(h){return h},function(h){console.error(h.message||h);return h})})}}),D=u([],{declaredClass:"jimu.PortalUser",portalUrl:null,credential:null,portal:null,constructor:function(a){a&&e.mixin(this,a)},_checkCredential:function(){var a=q.isValidCredential(this.credential);a||(this.credential=null);return a},
isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||(this.portal.updateCredential(),this.credential=this.portal.credential)},getGroups:function(){var a=[];this.groups&&(a=r.map(this.groups,e.hitch(this,function(c){c.portalUrl=this.portalUrl;c.credential=this.credential;c.portal=this.portal;return new x(c)})));return a},getItemsByKeywords:function(a,c){return this.portal.queryItems({start:c||1,num:100,q:"owner:"+
this.username+' AND typekeywords:"'+a+'"'})},getContent:function(){this.updateCredential();var a=k.getUserContentUrl(this.portalUrl,this.username),c={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential&&(c.query.token=this.credential.token);var b=new l;m(a,c).then(e.hitch(this,function(d){b.resolve(d.data)}),e.hitch(this,function(d){b.reject(d)}));return b},getTags:function(){this.updateCredential();var a=k.getUserTagsUrl(this.portalUrl,this.username),c={responseType:"json",
query:{f:"json"},callbackParamName:"callback"};this.isValidCredential()&&(c.query.token=this.credential.token);var b=new l;m(a,c).then(e.hitch(this,function(d){b.resolve(d.data)}),e.hitch(this,function(d){b.reject(d)}));return b},addItem:function(a,c){this.updateCredential();var b=new l;if(this.isValidCredential()){var d={f:"json",token:this.credential.token};a&&(d=e.mixin(d,a));a=k.getAddItemUrl(this.portalUrl,this.username,c);m(a,{responseType:"json",callbackParamName:"callback",query:d,method:"post"}).then(e.hitch(this,
function(f){b.resolve(f.data)}),e.hitch(this,function(f){console.error(f);b.reject(f)}))}else setTimeout(e.hitch(this,function(){b.reject("token is null.")}),0);return b},deleteItem:function(a){this.updateCredential();var c=new l;this.isValidCredential()?(a=k.getDeleteItemUrl(this.portalUrl,this.username,a),m(a,{query:{token:this.credential.token,f:"json"},responseType:"json",method:"post"}).then(e.hitch(this,function(b){c.resolve(b.data)}),e.hitch(this,function(b){c.reject(b)}))):setTimeout(e.hitch(this,
function(){c.reject("token is null.")}),0);return c},getItemById:function(a,c){this.updateCredential();var b=new l;c=k.getUserItemsUrl(this.portalUrl,this.username,c);var d={responseType:"json",query:{f:"json"},callbackParamName:"callback"};this.isValidCredential()&&(d.query.token=this.credential.token);m(c+"/"+a,d).then(e.hitch(this,function(f){f=f.data;f.portalUrl=this.portalUrl;f.credential=this.credential;f.portal=this;f=new w(f);b.resolve(f)}),e.hitch(this,function(f){console.error(f);b.reject(f)}));
return b},shareItem:function(a,c,b){this.updateCredential();var d=new l;this.isValidCredential()?(c=k.shareItemUrl(this.portalUrl,this.username,c,b),b={responseType:"json",callbackParamName:"callback",query:{f:"json",token:this.credential.token},method:"post"},a&&(a.content&&!a.query&&(a.query=a.content),b.query=e.mixin(b.query,a)),m(c,b).then(e.hitch(this,function(f){d.resolve(f.data)}),e.hitch(this,function(f){console.error(f);d.reject(f)}))):setTimeout(e.hitch(this,function(){d.reject("token is null.")}),
0);return d},updateItem:function(a,c){this.updateCredential();var b=new l;this.isValidCredential()?this.portal.getItemById(a).then(e.hitch(this,function(d){var f={f:"json",token:this.credential.token};c&&(f=e.mixin(f,c));d=k.getUpdateItemUrl(this.portalUrl,this.username,a,d.ownerFolder);m(d,{responseType:"json",callbackParamName:"callback",timeout:1E5,query:f,method:"post"}).then(e.hitch(this,function(g){b.resolve(g.data)}),e.hitch(this,function(g){console.error(g);b.reject(g)}))}),e.hitch(this,function(d){console.error(d);
b.reject(d)})):setTimeout(e.hitch(this,function(){b.reject("token is null.")}),0);return b},isAdminRole:function(){return"org_admin"===this.role||"account_admin"===this.role},isPublisherRole:function(){return"org_publisher"===this.role||"account_publisher"===this.role},isUserRole:function(){return"org_user"===this.role||"account_user"===this.role}}),x=u([],{declaredClass:"jimu.PortalGroup",portalUrl:null,credential:null,portal:null,constructor:function(a){a&&e.mixin(this,a)},_checkCredential:function(){var a=
q.isValidCredential(this.credential);a||(this.credential=null);return a},isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||(this.portal.updateCredential(),this.credential=this.portal.credential)},queryItems:function(a){a.q="group:"+this.id+" AND "+a.q;return this.portal.queryItems(a)}}),w=u([],{declaredClass:"jimu.PortalItem",itemUrl:null,detailsPageUrl:null,ownerPageUrl:null,portalUrl:null,credential:null,portal:null,
token:null,constructor:function(a){a&&e.mixin(this,a);this.itemUrl=k.getItemUrl(this.portalUrl,this.id);!this.thumbnailUrl&&this.thumbnail&&this.itemUrl&&(this.thumbnailUrl=this.itemUrl+"/info/"+this.thumbnail);this.token=this.credential&&this.credential.token;this.thumbnailUrl&&this.token&&(this.thumbnailUrl+="?token\x3d"+this.token);this.portalUrl&&this.id&&(this.detailsPageUrl=k.getItemDetailsPageUrl(this.portalUrl,this.id));this.portalUrl&&this.owner&&(this.ownerPageUrl=k.getUserProfilePageUrl(this.portalUrl,
this.owner))},_checkCredential:function(){var a=q.isValidCredential(this.credential);a||(this.credential=null);return a},isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||(this.portal.updateCredential(),this.credential=this.portal.credential)},getItemData:function(){return this.portal.getItemData(this.id)}}),A={portals:[],webMapQueryStr:" "+y.getItemQueryStringByTypes(["Web Map"])+" ",webSceneQueryStr:" "+y.getItemQueryStringByTypes(["Web Scene"])+
" ",_findPortal:function(a){for(var c=0;c<this.portals.length;c++){var b=this.portals[c];if(k.isSamePortalUrl(a,b.portalUrl))return b.updateCredential(),b}return null},getPortal:function(a){if(!a||"string"!==typeof a||!e.trim(a))return null;a=k.getStandardPortalUrl(a);var c=this._findPortal(a);c||(c=new E(a),c.credential=q.getPortalCredential(c.portalUrl),c.updateCredential(),this.portals.push(c));return c},getPortalSelfInfo:function(a){return this.getPortal(a).loadSelfInfo()},getBasemapGalleryGroup:function(a){return this._getPortalSelfGroup(a,
"basemapGalleryGroupQuery")},getTemplatesGroup:function(a){return this._getPortalSelfGroup(a,"templatesGroupQuery")},getUnits:function(a){var c="english",b="",d=new l;this.getPortal(a).getUser().then(e.hitch(this,function(f){f&&f.units?c=f.units:(b=v.locale,c=b.startWith("en")?"english":"metric");d.resolve(c)}),e.hitch(this,function(f){console.warn(f);this.getPortalSelfInfo(a).then(e.hitch(this,function(g){var h=null;g&&g.units?h=g.units:(b=g&&g.culture||v.locale,h=b.startWith("en")?"english":"metric");
d.resolve(h)}),e.hitch(this,function(g){console.warn(g);b=v.locale;c=b.startWith("en")?"english":"metric";d.resolve(c)}))}));return d.promise},_getPortalSelfGroup:function(a,c){var b=new l,d=this.getPortal(a);d||setTimeout(e.hitch(this,function(){b.reject()}),0);this.getPortalSelfInfo(a).then(e.hitch(this,function(f){d.queryGroups({f:"json",q:f[c]}).then(e.hitch(this,function(g){0<g.results.length?(g=g.results[0],g.portalUrl=d.portalUrl,g.credential=d.credential,g.portal=d,g=new x(g),b.resolve(g)):
b.reject("Can't find portal self group.")}),e.hitch(this,function(g){console.error(g);b.reject(g)}))}),e.hitch(this,function(f){console.error(f);b.reject(f)}));return b},getWebMapsFromBasemapGalleryGroup:function(a){var c=new l;this.getBasemapGalleryGroup(a).then(e.hitch(this,function(b){b?b.queryItems({start:1,num:100,f:"json",q:this.webMapQueryStr}).then(e.hitch(this,function(d){c.resolve(d)}),e.hitch(this,function(d){console.error(d);c.reject(d)})):c.reject()}),e.hitch(this,function(b){console.error(b);
c.reject(b)}));return c},getDefaultWebScene:function(a){var c=new l,b=this.getPortal(a);b.getUser().then(e.hitch(this,function(d){b.queryItems({start:1,num:1,f:"json",q:this.webSceneQueryStr+' AND owner:"'+d.username+'" ',sortField:"numViews",sortOrder:"desc"}).then(e.hitch(this,function(f){f=f.results;f=r.filter(f,e.hitch(this,function(g){return g.type&&"web scene"===g.type.toLowerCase()}));0<f.length?c.resolve(f[0].id):c.resolve(null)}),e.hitch(this,function(f){c.reject(f)}))}),e.hitch(this,function(){c.reject("not sign in")}));
return c},getDefaultWebMap:function(a){var c=new l;this.getPortalSelfInfo(a).then(e.hitch(this,function(b){var d=b.defaultBasemap&&b.defaultBasemap.id;d?c.resolve(d):this._getDefaultWebMapByBasemapGallery(a,b).then(e.hitch(this,function(f){f?c.resolve(f):this._getMostNumViewsWebMap(a).then(e.hitch(this,function(g){g?c.resolve(g):c.reject()}),e.hitch(this,function(g){console.error(g);c.reject(g)}))}),e.hitch(this,function(f){console.error(f);c.reject(f)}))}),e.hitch(this,function(b){console.error(b);
c.reject(b)}));return c},_getDefaultWebMapByBasemapGallery:function(a,c){var b=new l,d=this.getPortal(a),f=c.defaultBasemap&&c.defaultBasemap.title;d.queryGroups({f:"json",q:c.basemapGalleryGroupQuery}).then(e.hitch(this,function(g){g=g.results;0<g.length?d.queryItems({start:1,num:1,f:"json",q:this.webMapQueryStr+" AND group:"+g[0].id+" AND title:"+f}).then(e.hitch(this,function(h){h=h.results;h=r.filter(h,e.hitch(this,function(n){return n.type&&"web map"===n.type.toLowerCase()}));0<h.length?b.resolve(h[0].id):
(console.log("Can't find web map under basemapGalleryGroupQuery."),d.queryItems({start:1,num:1,f:"json",q:this.webMapQueryStr+" AND title:"+f}).then(e.hitch(this,function(n){n=n.results;n=r.filter(n,e.hitch(this,function(p){return p.type&&"web map"===p.type.toLowerCase()}));if(0<n.length){var t=n[0];d.getItemData(t.id).then(e.hitch(this,function(p){p&&(p.operationalLayers||p.baseMap||p.version)?b.resolve(t.id):b.resolve(null)}),e.hitch(this,function(){b.resolve(null)}))}else console.log("Can't find web map by defaultBasemap.title."),
b.resolve(null)}),e.hitch(this,function(n){console.error(n);b.reject(n)})))}),e.hitch(this,function(h){console.error(h);b.reject(h)})):(console.log("Can't find group by basemapGalleryGroupQuery."),b.resolve(null))}),e.hitch(this,function(g){console.error(g);b.reject(g)}));return b},_getMostNumViewsWebMap:function(a){var c=new l;this.getPortal(a).queryItems({start:1,num:1,f:"json",q:this.webMapQueryStr+" AND access:public AND owner:esri_en",sortField:"numViews",sortOrder:"desc"}).then(e.hitch(this,
function(b){b=b.results;b=r.filter(b,e.hitch(this,function(d){return d.type&&"web map"===d.type.toLowerCase()}));0<b.length?c.resolve(b[0].id):c.reject("Can't find most-num-views web map.")}),e.hitch(this,function(b){console.error(b);c.reject(b)}));return c}};B.subscribe("userSignOut",function(a){(a=A._findPortal(a))&&a.clearCredentialAndUser()});return A});