// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang esri/request dojo/promise/all jimu/shared/basePortalUrlUtils dojo/Deferred jimu/portalUtils jimu/utils esri/core/urlUtils".split(" "),function(g,l,t,m,h,q,k,r){var n={getBaseHrefUrl:function(b){var a="";window.isXT?a=window.location.protocol+"//"+window.location.host+window.appInfo.appPath:(a=k.urlToObject(window.location.href).query||{},a=a.appid?b+"apps/webappviewer3d/index.html?appid\x3d"+a.appid:a.id?b+"apps/webappviewer3d/index.html?id\x3d"+a.id:k.getAppHref());return a},
addQueryParamToUrl:function(b,a,d,c){b=r.urlToObject(b);b.query||(b.query={});b.query[a]=d;a=b.path;for(var e in b.query)d=b.query[e],!0===c&&(d=encodeURIComponent(d)),a=a===b.path?a+"?"+e+"\x3d"+d:a+"\x26"+e+"\x3d"+d;return a},removeQueryParamFromUrl:function(b,a,d){b=r.urlToObject(b);b.query&&delete b.query[a];a=b.path;for(var c in b.query){var e=b.query[c];!0===d&&(e=encodeURIComponent(e));a=a===b.path?a+"?"+c+"\x3d"+e:a+"\x26"+c+"\x3d"+e}return a},getShareUrlContent:function(b){return"\x3cdiv class\x3d'marker-feature-action-popup'\x3e\x3cdiv class\x3d'item'\x3e\x3cspan class\x3d'sub-title jimu-float-leading'\x3e"+
window.jimuNls.common.url+"\x3c/span\x3e\x3cinput type\x3d'text' class\x3d'jimu-float-leading' readonly\x3d'readonly' value\x3d"+b+"\x3e\x3c/input\x3e\x3c/div\x3e\x3c/div\x3e"},getShareUrl:function(b,a,d){var c=n.getBaseHrefUrl(window.portalUrl),e="";if(a)if(a.longitude&&a.latitude){var f=a.longitude;var p=a.latitude;e=a.longitude+","+a.latitude+","}else if(a.x&&a.y&&a.spatialReference&&a.spatialReference.wkid){var u=a.x;var v=a.y;var w=a.spatialReference.wkid;e=a.x+","+a.y+","+a.spatialReference.wkid}c=
n.addQueryParamToUrl(c,"marker",e,!0);c=n.addQueryParamToUrl(c+",,,","markertemplate",encodeURIComponent(JSON.stringify({title:a.title,x:u,y:v,wkid:w,longitude:f,latitude:p,isIncludeShareUrl:d})));a=b.getLevel();return c="number"===typeof a&&-1!==a?n.addQueryParamToUrl(c,"level",b.getLevel(),!0):n.addQueryParamToUrl(c,"scale",b.getScale(),!0)},getXyContent:function(b){var a="\x3cdiv class\x3d'marker-feature-action-popup'\x3e";b.longitude&&b.latitude?a+="\x3cdiv class\x3d'item clearFix'\x3e\x3cspan class\x3d'sub-title'\x3e"+
window.jimuNls.common.longitude+"\x3c/span\x3e\x3cspan class\x3d'val'\x3e"+k.localizeNumber(parseFloat(b.longitude).toFixed(4))+"\x3c/span\x3e\x3c/div\x3e\x3cdiv class\x3d'item clearFix'\x3e\x3cspan class\x3d'sub-title'\x3e"+window.jimuNls.common.latitude+"\x3c/span\x3e\x3cspan class\x3d'val'\x3e"+k.localizeNumber(parseFloat(b.latitude).toFixed(4))+"\x3c/span\x3e\x3c/div\x3e":b.x&&b.y&&(a+="\x3cdiv class\x3d'item clearFix'\x3e\x3cspan class\x3d'sub-title'\x3ex\x3c/span\x3e\x3cspan class\x3d'val'\x3e"+
k.localizeNumber(parseFloat(b.x).toFixed(4))+"\x3c/span\x3e\x3c/div\x3e\x3cdiv class\x3d'item'\x3e\x3cspan class\x3d'sub-title'\x3ey\x3c/span\x3e\x3cspan class\x3d'val'\x3e"+k.localizeNumber(parseFloat(b.y).toFixed(4))+"\x3c/span\x3e\x3c/div\x3e");return a+"\x3c/div\x3e"},_isUserOwnTheApp:function(b){return b&&b.username&&b.username===window.appInfo.appOwner?!0:!1},getItemByUserAndItemId:function(b,a,d,c){var e=new h;c=m.getStandardPortalUrl(c);c=c+"/sharing/rest/content/users/"+(a?a.username?a.username:
a.email:d.email);if(void 0!==b.folderId&&null!==b.folderId&&"/"!==b.folderId||void 0!==b.ownerFolder&&null!==b.ownerFolder&&"/"!==b.ownerFolder)c+="/"+(b.folderId||b.ownerFolder);c+="/items/"+b.id;l({url:c,handleAs:"json",content:{f:"json"},callbackParamName:"callback"}).then(g.hitch(this,function(f){e.resolve(f)}),g.hitch(this,function(f){console.error(f);e.reject(f)}));return e},_getProfile:function(b,a){var d=new h;b=m.getUserUrl(a,b.owner);l({url:b,handleAs:"json",content:{f:"json"},callbackParamName:"callback"}).then(g.hitch(this,
function(c){d.resolve(c)}),g.hitch(this,function(c){console.error(c);d.reject(c)}));return d},_unshareItemById:function(b,a,d){var c=new h;d=m.getStandardPortalUrl(d);d+="/sharing/rest/content/items/"+a+"/unshare";a={f:"json"};a=g.mixin(a,b);l({url:d,handleAs:"json",content:a,callbackParamName:"callback"},{usePost:!0}).then(g.hitch(this,function(e){c.resolve(e)}),g.hitch(this,function(e){console.error(e);c.reject(e)}));return c},canSharePublic:function(b){return!b.selfUrl||!0!==b.canSharePublic&&
!1!==b.canSharePublic?!0:b.canSharePublic},unshareItemsByUser:function(b,a,d){var c=new h;d=m.getStandardPortalUrl(d);d+="/sharing/rest/content/users/"+b+"/unshareItems";b={f:"json"};b=g.mixin(b,a);l({url:d,handleAs:"json",content:b,callbackParamName:"callback"},{usePost:!0}).then(g.hitch(this,function(e){c.resolve(e)}),g.hitch(this,function(e){console.error(e);c.reject(e)}));return c},unshareItems:function(b,a,d){var c=new h;d=m.getStandardPortalUrl(d);d+="/sharing/rest/content/users/"+(a.owner||
b.email)+"/unshareItems";b={f:"json"};b=g.mixin(b,a);l({url:d,handleAs:"json",content:b,callbackParamName:"callback"},{usePost:!0}).then(g.hitch(this,function(e){c.resolve(e)}),g.hitch(this,function(e){console.error(e);c.reject(e)}));return c},shareItemsByUser:function(b,a,d){var c=new h;d=m.getStandardPortalUrl(d);d+="/sharing/rest/content/users/"+b+"/shareItems";b={f:"json"};b=g.mixin(b,a);l({url:d,handleAs:"json",content:b,callbackParamName:"callback"},{usePost:!0}).then(g.hitch(this,function(e){c.resolve(e)}),
g.hitch(this,function(e){console.error(e);c.reject(e)}));return c},shareItems:function(b,a,d){var c=new h;d=m.getStandardPortalUrl(d);d+="/sharing/rest/content/users/"+(a.owner||b.email)+"/shareItems";b={f:"json"};b=g.mixin(b,a);l({url:d,handleAs:"json",content:b,callbackParamName:"callback"},{usePost:!0}).then(g.hitch(this,function(e){c.resolve(e)}),g.hitch(this,function(e){console.error(e);c.reject(e)}));return c},getItemsGroups:function(b,a){var d=new h;a=m.getStandardPortalUrl(a);a+="/sharing/rest/content/items/"+
b.id+"/groups";l({url:a,handleAs:"json",content:{f:"json"},callbackParamName:"callback"},{usePost:!0}).then(g.hitch(this,function(c){d.resolve(c)}),g.hitch(this,function(c){console.error(c);d.reject(c)}));return d},isSharedToPublic:function(b){return window.isXT?!1:null===b?!0:"undefined"!==typeof b&&"undefined"!==typeof b.item&&"undefined"!==typeof b.item.access&&"public"===b.item.access?!0:!1},isShowSocialMediaLinks:function(b){return window.isXT?!0:null===b?!0:"undefined"!==typeof b&&"undefined"!==
typeof b.item&&"undefined"!==typeof b.item.access&&"private"===b.item.access?!1:!0},getItemShareInfo:function(b){var a=new h,d="";if(window.isXT)return a.resolve(null);d=k.urlToObject(k.getAppHref()).query||{};d=d.id||d.appid;if("undefined"===typeof d||""===d)return a.resolve(null);q.getPortal(b).getItemById(d).then(g.hitch(this,function(c){var e={};e.item=c;e.item&&"undefined"===typeof e.item.sharing&&e.item.access&&(e.item.sharing={access:e.item.access});a.resolve(e)}),g.hitch(this,function(c){console.log(c);
a.resolve(null)}));return a},getShareInfo:function(b){var a=q.getPortal(b),d=new h,c="";if(window.isXT)return d.resolve(null);c=k.urlToObject(k.getAppHref()).query||{};c=c.id||c.appid;if("undefined"===typeof c||""===c)return d.resolve(null);t({getUser:a.getUser(),loadSelfInfo:a.loadSelfInfo(),getItem:a.getItemById(c)}).then(g.hitch(this,function(e){var f={};f.item=e.getItem;f.item&&f.item.ownerFolder&&f.item.ownerFolder.length&&"/"!==f.item.ownerFolder&&(f.item.folderId=f.item.ownerFolder);"undefined"===
typeof f.item.sharing&&f.item.access&&(f.item.sharing={access:f.item.access});f.user=e.getUser;n._setUserRole(e.loadSelfInfo,f);f.currentUser=f.user;f.isAdmin=!1;f.userRole&&(f.userRole.isAdmin()||f.userRole.isCustom()&&f.userRole.canUpdateOrgItems())?(f.isAdmin=!0,f.item.owner!==f.currentUser.name?n._getProfile(f.item,b).then(g.hitch(this,function(p){f.itemUser=p;f.itemUser.orgId!==f.currentUser.orgId&&(f.isAdmin=!1);d.resolve(f)})):(f.itemUser=f.currentUser,d.resolve(f))):(f.currentUser&&(f.itemUser=
f.currentUser),d.resolve(f))}),g.hitch(this,function(e){console.log(e);d.resolve(null)}));return d},_setUserRole:function(b,a){a.userPortalUrl=b.urlKey?b.urlKey+"."+b.customBaseUrl:this.portalUrl;!b||b.code||b.message||(a.organization=b);if(b&&b.user)a.userRole=new Role({id:b.user.roleId?b.user.roleId:b.user.role,role:b.user.role}),a._isCustomRole=a.userRole.isCustom(),a._roleCanShareToGroup=a._isCustomRole&&a.userRole.canShareItemToGroup(),a._roleCanShareToOrg=a._isCustomRole&&a.userRole.canShareItemToOrg(),
a._roleCanSharePublic=a._isCustomRole&&a.userRole.canShareItemToPublic(),a._roleCanShare=a._roleCanShareToGroup||a._roleCanShareToOrg||a._roleCanShareToPublic,a._roleCanUpdateItems=a._isCustomRole&&a.userRole.canUpdateOrgItems(),a._roleCanShareOthersItemsToGroup=a._isCustomRole&&a.userRole.canShareOthersItemsToGroup(),a._roleCanShareOthersItemsToOrg=a._isCustomRole&&a.userRole.canShareOthersItemsToOrg(),a._roleCanShareOthersItemsToPublic=a._isCustomRole&&a.userRole.canShareOthersItemsToPublic(),a._roleCanShareOthersItems=
a._isCustomRole&&(a.userRole.canShareOthersItemsToGroup()||a.userRole.canShareOthersItemsToOrg()||a._roleCanShareOthersItemsToPublic),a._orgUserCanSharePublicOrOverride=a.organization&&(!0===a.organization.canSharePublic&&(!a._isCustomRole||a._roleCanSharePublic||a._roleCanShareOthersItemsToPublic)||a.userRole.isAdmin());else return!1},getItemById:function(b,a){var d=new h;a=m.getStandardPortalUrl(a);a+="/sharing/rest/content/items/"+b.id;l({url:a,handleAs:"json",content:{f:"json"},callbackParamName:"callback"}).then(g.hitch(this,
function(c){d.resolve(c)}),g.hitch(this,function(c){console.error(c);d.reject(c)}));return d},disableWebMapPopup:function(b){b&&b.setInfoWindowOnClick&&b.setInfoWindowOnClick(!1)},enableWebMapPopup:function(b){b&&b.setInfoWindowOnClick&&b.setInfoWindowOnClick(!0)}};return n});