// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("require dojo/_base/lang dojo/_base/array dojo/aspect dojo/Deferred dojo/cookie dojo/json dojo/topic dojo/request/script esri/kernel esri/request esri/core/urlUtils esri/identity/IdentityManager esri/identity/OAuthInfo jimu/portalUrlUtils jimu/utils".split(" "),function(G,e,l,A,t,q,B,w,x,h,C,D,H,I,g,n){"function"!==typeof q.getAll&&(q.getAll=function(a){var b=[];(a=q(a))&&b.push(a);return b});var F={portalUrl:null,cookiePath:"/",_started:!1,webTierPortalUrls:[],isInBuilderWindow:function(){return!!window.isBuilder},
isInConfigOrPreviewWindow:function(){return n.isInConfigOrPreviewWindow()},isStringStartWith:function(a,b){return a.substr(0,b.length)===b},getCookiePath:function(){return this.cookiePath},setPortalUrl:function(a){(a=g.getStandardPortalUrl(a))&&(a+="/");this.portalUrl=a},getPortalUrl:function(){return this.portalUrl},isWebTierPortal:function(a){var b=new t,c=g.getStandardPortalUrl(a);a=c+"/sharing";var d=g.setHttpsProtocol(c+"/sharing/generateToken?f\x3djson"),k=g.setHttpsProtocol(a);x.get(d,{jsonp:"callback"}).then(e.hitch(this,
function(f){f.token?(this.webTierPortalUrls.push(c),this.removeWabAuthInfo(),h.id.getCredential(k).then(e.hitch(this,function(m){function u(p){var y=p.creationTime||(new Date).getTime(),z=p.expires;0<y&&0<z&&z>y&&setTimeout(function(){x.get(d,{jsonp:"callback"}).then(function(r){r.token&&(p.token=r.token,p.expires=r.expires,p.creationTime=(new Date).getTime(),p.refreshServerTokens(),u(p))},function(r){console.error(r)})},.8*(z-y))}m.token||(m.token=f.token);m.expires||(m.expires=f.expires);var v=
n.getEsriConfigRequestObject(),E=D.isTrustedServer(m.server,!0);-1<E&&v.corsEnabledServers&&v.corsEnabledServers.splice(E,1);this._pushCorsEnabledServerInfo({host:g.getServerByUrl(c),withCredentials:!0});b.resolve(!0);u(m)}),e.hitch(this,function(){b.resolve(!0)}))):b.resolve(!1)}),e.hitch(this,function(f){console.error(f);b.reject(f)}));return b},addAuthorizedCrossOriginDomains:function(a){if(a&&0<a.length)for(var b=0;b<a.length;b++)this.addWithCredentialDomain(a[b])},addWithCredentialDomain:function(a){if(a&&
"string"===typeof a){var b=n.getEsriConfigRequestObject().corsEnabledServers||[],c=g.getServerByUrl(a);(a=g.getServerWithProtocol(a))||(a="http://"+c);a=D.isTrustedServer(a,!0);-1<a&&b.splice(a,1);this._pushCorsEnabledServerInfo({host:c,withCredentials:!0})}},_pushCorsEnabledServerInfo:function(a){if(a){var b=n.getEsriConfigRequestObject(),c=b.corsEnabledServers||[],d="charAt charCodeAt concat endsWith indexOf lastIndexOf localeCompare match replace search slice split startsWith substr substring toLocaleLowerCase toLocaleUpperCase toLowerCase toString toUpperCase trim trimLeft trimRight valueOf".split(" ");
if("object"===typeof a&&"string"===typeof a.host){for(var k in a.host)a[k]="function"===typeof a.host[k]?function(){return a.host[k].apply(a.host,arguments)}:a.host[k];a.length=a.host.length;l.forEach(d,function(f){"function"===typeof a.host[f]&&(a[f]=function(){return a.host[f].apply(a.host,arguments)})});a.withCredentials&&b.webTierAuthServers&&0>b.webTierAuthServers.indexOf(a.host)&&b.webTierAuthServers.push(a.host)}c.push(a)}},tryRegisterCredential:function(a){return this.isValidCredential(a)?
l.some(h.id.credentials,e.hitch(this,function(b){return a.token===b.token}))?!1:(h.id.credentials.push(a),!0):!1},registerToken:function(a){var b=g.getSharingUrl(this.portalUrl);h.id.findCredential(b)&&l.some(h.id.credentials,e.hitch(this,function(c,d){if(this.isValidPortalCredentialOfPortalUrl(this.portalUrl,c))return h.id.credentials.splice(d,1),!0}));return this._getTokenInfo(a).then(function(c){h.id.registerToken(c)})},_getTokenInfo:function(a){var b=g.getPortalSelfInfoUrl(this.portalUrl);return x.get(b+
("?f\x3djson\x26token\x3d"+a),{jsonp:"callback"}).then(e.hitch(this,function(c){if(c.user)return{server:g.getSharingUrl(this.portalUrl),ssl:c.allSSL,token:a,userId:c.user.username};throw Error(window.jimuNls.urlParams.invalidToken);}),function(c){console.error(c);throw Error(window.jimuNls.urlParams.validateTokenError);})},_isInvalidPortalUrl:function(a){return a&&"string"===typeof a&&e.trim(a)},signInPortal:function(a){var b=new t;if(this._isInvalidPortalUrl(a)){a=g.getStandardPortalUrl(a);var c=
g.getSharingUrl(a),d=this.getPortalCredential(a);d?setTimeout(e.hitch(this,function(){b.resolve(d)}),0):b=h.id.getCredential(c)}else setTimeout(e.hitch(this,function(){b.reject("Invalid portalurl.")}),0);return b},_loadPortalSelfInfo:function(a){a=g.getPortalSelfInfoUrl(a);var b=new t;C(a,{responseType:"json",query:{f:"json"},callbackParamName:"callback"}).then(e.hitch(this,function(c){b.resolve(c.data)}),e.hitch(this,function(c){b.reject(c)}));return b},registerOAuthInfo:function(a,b,c){if(!a||"string"!==
typeof a||!b||"string"!==typeof b)return null;c||(c=0);c=h.id.findOAuthInfo(a);c||(c=window.location.protocol+"//"+window.location.host+G.toUrl("jimu")+"/oauth-callback.html",c=new I({appId:b,expiration:20160,portalUrl:a,authNamespace:"/",popup:!0,flowType:"auto",popupCallbackUrl:c}),h.id.registerOAuthInfos([c]));c.appId=b;return c},signOutAll:function(a){var b=g.getStandardPortalUrl(this.portalUrl)+"/sharing/rest",c=g.getPortalSignInUrlFromLocation();c=c+"?returnUrl\x3d"+encodeURIComponent(window.location.href);
var d=n.getLocationUrlWithoutHashAndQueryParams();d=n.url.addQueryParamToUrl(d,"action","setportalurl");window.appInfo.isRunInPortal?(this.removeEsriAuthCookieStorage(),window.location.href=b+"/oauth2/signout?client_id\x3darcgisonline\x26redirect_uri\x3d"+c):(this.removeWabAuthInfo(),a&&a.supportsOAuth?(a=b+"/oauth2/signout?client_id\x3d"+a.appId+"\x26redirect_uri\x3d"+d,window.location.href=a):window.location.href=d)},userHaveSignInPortal:function(a){return!!this.getPortalCredential(e.trim(a||""))},
isValidCredential:function(a){var b=!1;if(a){b=a.token;var c=a.server,d=a.scope;b=b&&"string"===typeof b&&e.trim(b);c=c&&"string"===typeof c&&e.trim(c);d="portal"===d||"server"===d;var k=!0;a.expires&&(a=parseInt(a.expires,10),k=(new Date).getTime(),k=a>k);b=b&&c&&d&&k}return b},isValidPortalCredentialOfPortalUrl:function(a,b){var c=!1;this.isValidCredential(b)&&(c="portal"===b.scope,a=g.isSameServer(a,b.server),c=c&&a);return c},getPortalCredential:function(a){var b=null;a=e.trim(a||"");if(!a)return null;
a=g.getStandardPortalUrl(a);return b=this._filterPortalCredential(a,h.id.credentials)},saveAndRegisterCookieToCredential:function(a){a=e.clone(a);a.referer=window.location.host;a.scope="portal";a.isAdmin=!!a.isAdmin;this.saveWabAuthInfo(a);var b=a.server+"/sharing/rest";a.server=b;h.id.registerToken(a);return h.id.findCredential(b,a.userId)},registerAuth2Hash:function(a){a=e.clone(a);var b=1E3*parseInt(a.expires_in,10);b=(new Date).getTime()+b;var c=g.getStandardPortalUrl(a.state.portalUrl);return this.saveAndRegisterCookieToCredential({referer:window.location.host,
server:c,token:a.access_token,expires:b,userId:a.username,scope:"portal",isAdmin:!!a.isAdmin})},readWabAuthInfo:function(){var a=null,b=localStorage.getItem("wab_token");try{var c=q("wab_auth");c&&(a=B.parse(c),a.token=b)}catch(d){console.error(d)}return a},saveWabAuthInfo:function(a){a=e.clone(a);this.removeWabAuthInfo();localStorage.setItem("wab_token",a.token);delete a.token;q("wab_auth",B.stringify(a),{expires:new Date(a.expires),path:"/"})},removeWabAuthInfo:function(){this.removeCookie("wab_auth");
localStorage.removeItem("wab_token")},removeEsriAuthCookieStorage:function(){window.localStorage&&window.localStorage.removeItem("esriJSAPIOAuth");window.sessionStorage&&window.sessionStorage.removeItem("esriJSAPIOAuth")},_filterPortalCredential:function(a,b){var c=null;b&&0<b.length&&(b=l.filter(b,e.hitch(this,function(d){return this.isValidPortalCredentialOfPortalUrl(a,d)})),0<b.length&&(c=b[b.length-1]));return c},_removePortalCredential:function(a){var b=e.trim(a||"");if(b){b=g.getStandardPortalUrl(b);
for(a=l.filter(h.id.credentials,e.hitch(this,function(c){return this.isValidPortalCredentialOfPortalUrl(b,c)}));0<a.length;)a[0].destroy(),a.splice(0,1);h.id.credentials=l.filter(h.id.credentials,e.hitch(this,function(c){return!this.isValidPortalCredentialOfPortalUrl(b,c)}))}},getUserIdByToken:function(a,b){var c=new t;if(a&&"string"===typeof a&&b&&"string"===typeof b){var d=g.getStandardPortalUrl(b);b=l.filter(h.id.credentials,e.hitch(this,function(f){var m=f.token===a&&f.userId;f=g.isSameServer(d,
f.server);return m&&f}));if(0<b.length){var k=b[0];setTimeout(e.hitch(this,function(){c.resolve(k.userId)}),0);return c}b=g.getCommunitySelfUrl(d);C(b,{responseType:"json",query:{f:"json"},callbackParamName:"callback"}).then(e.hitch(this,function(f){f=f&&f.data;c.resolve(f&&f.username||"")}),e.hitch(this,function(f){console.error(f);c.reject("fail to get userId by token")}))}else setTimeout(e.hitch(this,function(){c.reject("invalid parameters")}),0);return c},xtGetCredentialFromCookie:function(a){var b=
this.readWabAuthInfo();if(!b||"object"!==typeof b||!g.isSameServer(a,b.server)||window.location.host!==b.referer)return null;b.expires=parseInt(b.expires,10);var c=(new Date).getTime();if(!(b.expires>c))return this.removeCookie("wab_auth"),null;a+="/sharing/rest";b.server=a;(c=h.id.findCredential(a))||h.id.registerToken(b);return c=h.id.findCredential(a)},removeCookie:function(a){var b=this.getCookiePath();n.removeCookie(a,b)},_getDomainsByServerName:function(a){var b=a.split("."),c=b.length;return l.map(b,
e.hitch(this,function(d,k){d=b.slice(k,c);var f="",m=d.length-1;l.forEach(d,e.hitch(this,function(u,v){f+=u;v!==m&&(f+=".")}));return f}))},_publishCurrentPortalUserSignIn:function(a){if(this.isValidCredential(a))try{w.publish("userSignIn",a)}catch(b){console.error(b)}},_publishAnyUserSignIn:function(a){if(this.isValidCredential(a))try{w.publish("anyUserSignIn",a)}catch(b){console.error(b)}},_publishCurrentPortalUserSignOut:function(a){try{w.publish("userSignOut",a)}catch(b){console.error(b)}},_signInSuccess:function(a){try{this.isValidPortalCredentialOfPortalUrl(this.portalUrl,
a)&&this._publishCurrentPortalUserSignIn(a),this._publishAnyUserSignIn(a)}catch(b){console.error(b)}},_bindEvents:function(){A.after(h.id,"signIn",e.hitch(this,function(a,b){console.log(b[1]);A.after(a,"callback",e.hitch(this,function(c,d){this._signInSuccess(d[0],!1)}));return a}))},isStart:function(){return this._started},startup:function(){if(!this._started){if(this.isInConfigOrPreviewWindow()){var a=window.parent;if(a){var b=a.esri&&a.esri.id;if(b){H.initialize(b.toJson());var c=n.getEsriConfigRequestObject();
a=a.esriConfig.defaults.io;c.trustedServers||(c.trustedServers=[]);l.forEach(a.corsEnabledServers||[],e.hitch(this,function(d){d&&d.host&&d.withCredentials&&c.trustedServers.push(d.host)}))}}}this._bindEvents();this._started=!0}}};F.startup();return F});