// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/html dojo/_base/sniff dojo/_base/config dojo/io-query dojo/query dojo/NodeList-traverse dojo/Deferred dojo/promise/all dojo/on dojo/json dojo/cookie dojo/number dojo/date/locale dojo/i18n!dojo/cldr/nls/number dojox/encoding/base64 esri/kernel esri/config esri/geometry/SpatialReference esri/geometry/Extent esri/geometry/Multipoint esri/geometry/Polyline esri/geometry/Polygon esri/geometry/support/webMercatorUtils esri/rest/geometryService esri/rest/support/ProjectParameters esri/core/urlUtils esri/request ./shared/utils".split(" "),
function(n,p,r,E,F,O,x,sa,w,ea,G,B,H,P,fa,ha,Q,ia,v,ja,ka,la,ma,R,na,oa,pa,y,I,S){function T(a,b){var c=a.match(/url\([^)]+\)/gi),d;if(null===c||""===b)return a;for(d=0;d<c.length;d++){var e=c[d].match(/(url\(["|']?)(.*)((?:['|"]?)\))/i);if(4<=e.length){var f=e[2];/^data:image\/.*;/.test(f)||(b.endWith("/")||(b+="/"),a=a.replace(e[1]+f+e[3],e[1]+b+f+e[3]))}}return a}function J(a,b){var c=Array.isArray(b),d=c&&[]||{};c?(a=a||[],d=d.concat(a),b.forEach(function(e,f){"undefined"===typeof a[f]?d[f]=e:
"object"===typeof e?d[f]=J(a[f],e):-1===a.indexOf(e)&&d.push(e)})):(a&&"object"===typeof a&&Object.keys(a).forEach(function(e){d[e]=a[e]}),Object.keys(b).forEach(function(e){d[e]="object"===typeof b[e]&&b[e]?a[e]?J(a[e],b[e]):b[e]:b[e]}));return d}function U(a){var b={};var c=a.indexOf("/");a.substring(0,c);c=a.substring(0,a.lastIndexOf("/")+1);b.folderUrl=require(g.getRequireConfig()).toUrl(c);b.amdFolder=c;b.url=b.folderUrl;if(/^http(s)?:\/\//.test(a)||/^\/\//.test(a))b.isRemote=!0;return b}function qa(a){a.panels.forEach(function(b){b.uri=
"panels/"+b.name+"/Panel.js"});a.styles.forEach(function(b){b.uri="styles/"+b.name+"/style.css"});a.layouts.forEach(function(b){b.uri="layouts/"+b.name+"/config.json";b.icon="layouts/"+b.name+"/icon.png";b.RTLIcon="layouts/"+b.name+"/icon_rtl.png"})}function V(a,b){var c=a.map(function(f){return f.id});p.forEach(b,function(f){0>c.indexOf(f)&&a.push({id:f,widgets:[]})},this);var d=[];a=p.filter(a,function(f){return 0>b.indexOf(f.id)?(d.push(f),!1):!0},this);if(0===a.length)return[];var e=a[a.length-
1];p.forEach(d,function(f){e.widgets=e.widgets.concat(f.widgets)},this);return a=a.sort(function(f,h){return b.indexOf(f.id)-b.indexOf(h.id)})}function K(a,b,c){function d(f,h){return n.isArray(f[h.key])?f[h.key][h.index]:f[h.key]}b=function(f){var h=[];f.split("_").forEach(function(k){var l=!1;"--"===k.slice(k.length-2)&&(l=!0,k=k.slice(0,k.length-2));var m=k.search(/\[[0-9]+\]/);-1===m&&(m=k.length);h.push({key:k.slice(0,m),index:Number(k.slice(m+1,-1)),deleteFlag:l})});return h}(b);for(var e=1;e<
b.length-1;e++)if(a=d(a,b[e]),!a)return;if(b[b.length-1].deleteFlag)!0===c&&(n.isArray(a[b[b.length-1].key])?delete a[b[b.length-1].key][b[b.length-1].index]:delete a[b[b.length-1].key]);else if(n.isArray(a[b[b.length-1].key])){if(void 0===c)return a[b[b.length-1].key][b[b.length-1].index];a[b[b.length-1].key][b[b.length-1].index]=c}else{if(void 0===c)return a[b[b.length-1].key];a[b[b.length-1].key]=c}}function W(a,b,c){function d(k){k=g.template.getSearchRange(b,k,"]");var l=b.slice(k.firstPos,k.lastPos);
return-1!==k.firstPos?(l=b.slice(k.firstPos+l.indexOf("[")+1,k.lastPos-1),k=b.slice(k.lastPos+1),(l=g.getConfigElementById(a,l))?{object:l,key:"section_"+k,state:"isSection"}:{state:"deleted"}):{state:"isNotSection"}}var e=a,f=b=b.replace(/\//g,"_"),h=d("groups\\[.+\\]");if("deleted"!==h.state&&("isSection"===h.state&&(e=h.object,f=h.key),h=d("widgets\\[.+\\]"),"delete"!==h.state))return"isSection"===h.state&&(e=h.object,f=h.key),K(e,f,c)}var g={},ra={geometryService:"http://utility.arcgisonline.com/arcgis/rest/services/Geometry/GeometryServer"};
n.mixin(g,S);window.atob||(window.atob=function(a){a=Q.decode(a);for(var b="",c=0,d=a.length;c<d;c++)b+=String.fromCharCode(a[c]);return b});window.btob||(window.btob=function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(String.charCodeAt(a[c]));return Q.encode(b)});var X=[];require.on("error",function(a){p.forEach(X,function(b){a.info[0]&&-1<a.info[0].indexOf(b.resKey)&&b.def.reject(a);for(var c in a.info)-1<c.indexOf(b.resKey)&&b.def.reject(a)})});g.checkError=function(a,b){X.push({resKey:a,def:b})};
g.replacePlaceHolder=function(a,b){var c=B.stringify(a),d=c.match(/\$\{(\w)+\}/g);if(null===d)return a;for(a=0;a<d.length;a++){var e=d[a].match(/(\w)+/g)[0];b[e]&&(c=c.replace(d[a],b[e]))}return B.parse(c)};g.changeUnit=function(a){var b=Math.abs(a);a=Math.floor(b);var c=Math.floor(60*(b-a));b=(60*(60*(b-a)-c)).toFixed(2);return a+"\u00b0"+(10>c?"0"+c:c)+"'"+(10>b?"0"+b:b)+'"'};g.formatTime=function(a){var b=a/1E3;a=Math.floor(b/60);b=Number(b-60*a).toFixed(1);return(10>a?"0"+a:a)+":"+(10>b?"0"+b:
b)};g.parseTime=function(a){var b=/(\d{2,}):(\d{2})\.(\d{1})/;if(!b.test(a))return console.log("wrong time format."),-1;a=a.match(b);return 1E3*(60*parseInt(a[1],10)+parseInt(a[2],10)+parseInt(a[3],10)/10)};g.preloadImg=function(a,b){var c=[];c="string"===typeof a?[a]:a;p.forEach(c,function(d){(new Image).src=b?b+d:d})};g.setWABLogoDefaultAlt=function(a){if(a){a=x("img",a);for(var b=["img_1412759111499","img_1545621838463","img_1560482577021"],c=0,d=a.length;c<d;c++){var e=a[c];-1<b.indexOf(r.getAttr(e,
"id"))&&!r.getAttr(e,"alt")&&r.setAttr(e,"alt","ArcGIS Web AppBuilder.png")}}};var z=null;g.getImagesSize=function(a){var b=new w;if(!a||0!==a.indexOf("http"))return b.reject(),b;null===z&&(z=r.create("img",{id:"__test-image-size",style:{position:"absolute",left:"-9999px",top:"-9999px"}},document.body));var c=G(z,"load",function(){clearTimeout(d);d=null;c.remove();var e=r.getContentBox(z);1===e.w&&1===e.h||0===e.w||0===e.h?b.reject():b.resolve([e.w,e.h])},{}),d=setTimeout(function(){clearTimeout(d);
d=null;b.reject()},5E3);r.setAttr(z,"src",a);return b};g.getPositionStyle=function(a){var b={};if(!a)return b;a=n.clone(a);if(window.isRTL){if("undefined"!==typeof a.left&&"undefined"!==typeof a.right){var c=a.left;a.left=a.right;a.right=c}else"undefined"!==typeof a.left?(a.right=a.left,delete a.left):"undefined"!==typeof a.right&&(a.left=a.right,delete a.right);"undefined"!==typeof a.paddingLeft&&"undefined"!==typeof a.paddingRight?(c=a.paddingLeft,a.paddingLeft=a.paddingRight,a.paddingRight=c):
"undefined"!==typeof a.paddingLeft?(a.paddingRight=a.paddingLeft,delete a.paddingLeft):"undefined"!==typeof a.paddingRight&&(a.paddingLeft=a.paddingRight,delete a.paddingRight);"undefined"!==typeof a.marginLeft&&"undefined"!==typeof a.marginRight?(c=a.marginLeft,a.marginLeft=a.marginRight,a.marginRight=c):"undefined"!==typeof a.marginLeft?(a.marginRight=a.marginLeft,delete a.marginLeft):"undefined"!==typeof a.marginRight&&(a.marginLeft=a.marginRight,delete a.marginRight)}c="left top right bottom width height padding paddingLeft paddingRight paddingTop paddingBottom margin marginLeft marginRight marginTop marginBottom".split(" ");
for(var d=0;d<c.length;d++){var e=c[d];"number"===typeof a[e]?b[e]=a[e]+"px":"undefined"!==typeof a[e]?b[e]=a[e]:"padding"===e.substr(0,7)||"margin"===e.substr(0,7)?b[e]=0:b[e]="auto"}b.zIndex="undefined"===typeof a.zIndex?"auto":a.zIndex;return b};g.isEqual=function(a,b){function c(f,h){var k;if(null===f&&null===h||"undefined"===typeof f&&"undefined"===typeof h)return!0;if(null===f&&null!==h||null===h&&null!==f||"undefined"===typeof f&&"undefined"!==typeof h||"undefined"===typeof h&&"undefined"!==
typeof f)return!1;if(isNaN(f)&&isNaN(h)&&"number"===typeof f&&"number"===typeof h||f===h)return!0;if("function"===typeof f&&"function"===typeof h||f instanceof Date&&h instanceof Date||f instanceof RegExp&&h instanceof RegExp||f instanceof String&&h instanceof String||f instanceof Number&&h instanceof Number)return f.toString()===h.toString();if(-1<d.indexOf(f)||-1<e.indexOf(h))return!1;if(null!==h){for(k in h)if(h.hasOwnProperty(k)!==f.hasOwnProperty(k)||typeof h[k]!==typeof f[k])return!1;for(k in f){if(h.hasOwnProperty(k)!==
f.hasOwnProperty(k)||typeof h[k]!==typeof f[k])return!1;switch(typeof f[k]){case "object":case "function":d.push(f);e.push(h);if(!c(f[k],h[k]))return!1;d.pop();e.pop();break;default:if(f[k]!==h[k])return!1}}}return!0}var d=[];var e=[];return c(a,b)?!0:!1};g.getUriInfo=U;g.file={loadFileAPI:function(){var a=new w;a.resolve();return a},supportHTML5:function(){return window.File&&window.FileReader&&window.FileList&&window.Blob?!0:!1},supportFileAPI:function(){return E("safari")&&6>E("safari")?!1:window.FileAPI&&
window.FileAPI.readAsDataURL?!0:!1},isEnabledFlash:function(){var a=null;if(document.all)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(b){a=null}else navigator.plugins&&0<navigator.plugins.length&&(a=navigator.plugins["Shockwave Flash"]);return!!a},containSeparator:function(a){return 0<=a.indexOf("/")?!0:0<=a.indexOf("\\")?!0:!1},getNameFromPath:function(a){var b="";b=0<=a.indexOf("/")?"/":"\\";a=a.split(b);return 0<a.length?a[a.length-1]:null},getFolderFromPath:function(a){return a.substr(0,
a.length-g.file.getNameFromPath(a).length)},readFile:function(a,b,c,d){if(this.supportHTML5()){var e=a.target.files[0];e&&(e.type.match(b)?e.size>=c?d({errCode:"exceed"}):(a=new FileReader,a.onload=function(h){d(null,e.name,h.target.result)},a.readAsDataURL(e)):d({errCode:"invalidType"}))}else if(this.supportFileAPI()){var f=window.FileAPI.getFiles(a);f[0].type.match(b)?f[0].size>=c?d({errCode:"exceed"}):window.FileAPI.readAsDataURL(f[0],function(h){h&&h.result?d(null,f[0].name,h.result):d({errCode:"readError"})}):
d({errCode:"invalidType"})}}};g.processWidgetSetting=function(a){if(!a.uri)return a;n.mixin(a,U(a.uri));a.icon||(a.icon=a.amdFolder+"images/icon.png");a.thumbnail||(a.thumbnail=a.amdFolder+"images/thumbnail.png");return a};g.getRequireConfig=function(){if(jimuConfig){var a=[];jimuConfig.widgetsPackage&&(a=a.concat(jimuConfig.widgetsPackage));jimuConfig.themesPackage&&(a=a.concat(jimuConfig.themesPackage));jimuConfig.configsPackage&&(a=a.concat(jimuConfig.configsPackage));return{packages:a}}return{}};
g.getTypeByGeometryType=function(a){var b="",c="esriGeometryLine esriGeometryCircularArc esriGeometryEllipticArc esriGeometryBezier3Curve esriGeometryPath esriGeometryPolyline".split(" "),d=["esriGeometryRing","esriGeometryPolygon","esriGeometryEnvelope"];0<=["esriGeometryPoint","esriGeometryMultipoint"].indexOf(a)?b="point":0<=c.indexOf(a)?b="polyline":0<=d.indexOf(a)&&(b="polygon");return b};g.getSymbolTypeByGeometryType=function(a){var b=null;a=g.getTypeByGeometryType(a);"point"===a?b="marker":
"polyline"===a?b="line":"polygon"===a&&(b="fill");return b};g.getServices=function(){return ra};g.restoreToDefaultWebMapExtent=function(a,b,c){var d=new w;if(!a||"esri.Map"!==a.declaredClass)return setTimeout(function(){d.reject("Invalid map.")},0),d;b=b&&b.itemInfo;if(!b)return setTimeout(function(){d.reject("Invalid itemInfo")},0),d;b=b.item&&b.item.extent;if(!b)return setTimeout(function(){d.reject("Invalid itemInfo.item.extent")}),d;var e=new ja({wkid:4326});e=new ka(b[0][0],b[0][1],b[1][0],b[1][1],
e);if(4326===parseInt(a.spatialReference.wkid,10))return a.setExtent(e);if(a.spatialReference.isWebMercator)return e=na.geographicToWebMercator(e),a.setExtent(e);b=new pa;b.geometries=[e];b.outSR=a.spatialReference;e=null;if(e=v&&v.defaults&&v.defaults.geometryServiceUrl&&"string"===typeof v.defaults.geometryServiceUrl&&n.trim(v.defaults.geometryServiceUrl)?v.defaults.geometryServiceUrl:c&&"string"===typeof c&&n.trim(c)?c:g.getServices()&&g.getServices().geometryService)return e=n.trim(e),oa.project(e,
b).then(function(f){if(f=f&&f[0])return a.setExtent(f);d.reject("Invalid projected geometry.");return d},function(f){console.error(f);d.reject(f);return d}),d};g.getAncestorWindow=function(){for(var a=window;a&&a.parent&&a!==a.parent;)a=a.parent;return a};g.getAncestorDom=function(a,b,c){if(a&&1===a.nodeType&&b&&"function"===typeof b){var d=100,e=document.body;c&&("number"===typeof c?(c=parseInt(c,10),0<c&&(d=c)):1===c.nodeType&&(e=c));for(c=0;a.parentNode&&c<d&&r.isDescendant(a.parentNode,e);){if(b(a.parentNode))return a.parentNode;
a=a.parentNode;c++}}return null};g.bindClickAndDblclickEvents=function(a,b,c,d){var e=null;if(a&&1===a.nodeType&&b&&"function"===typeof b&&c&&"function"===typeof c){var f=200;d&&"number"===typeof d&&(d=parseInt(d,10),0<d&&(f=d));var h=0;e=G(a,"click",function(k){h++;1===h?setTimeout(function(){1===h&&(h=0,b(k))},f):2===h&&(h=0,c(k))})}return e};g.isScrollToBottom=function(a){var b=r.getContentBox(a);return 1>a.scrollHeight-(a.scrollTop+b.h)};g.getAllItemTypes=function(){var a=[];a=a.concat(["Web Map",
"Web Scene","CityEngine Web Scene"]).concat("Feature Service;Map Service;Image Service;KML;WMS;Feature Collection;Feature Collection Template;Geodata Service;Globe Service".split(";")).concat(["Geometry Service","Geocoding Service","Network Analysis Service","Geoprocessing Service"]).concat(["Web Mapping Application","Mobile Application","Code Attachment","Operations Dashboard Add In","Operation View"]).concat("Symbol Set;Color Set;Shapefile;CSV;Service Definition;Document Link;Microsoft Word;Microsoft PowerPoint;Microsoft Excel;PDF;Image;Visio Document".split(";"));
return a=a.concat("Map Document;Map Package;Tile Package;ArcPad Package;Explorer Map;Globe Document;Scene Document;Published Map;Map Template;Windows Mobile Package".split(";")).concat(["Layer","Layer Package","Explorer Layer"]).concat(["Geoprocessing Package","Geoprocessing Sample","Locator Package","Rule Package"]).concat("Workflow Manager Package;Desktop Application;Desktop Application Template;Code Sample;Desktop Add In;Explorer Add In".split(";"))};g.getItemQueryStringByTypes=function(a){var b=
"",c=g.getAllItemTypes();if(a&&0<a.length&&0<a.length){var d="";p.forEach(a,function(e,f){d+=' type:"'+e+'" ';f!==a.length-1&&(d+=" OR ")});b=" ( "+d+" ) ";c=a.concat(c);c=p.filter(c,function(e){return p.every(a,function(f){return 0>f.toLowerCase().indexOf(e.toLowerCase())})});p.forEach(c,function(e){b+=' -type:"'+e+'" '})}return b};g.getItemQueryStringByTypeKeywords=function(a){var b="";a&&0<a.length&&(b=' typekeywords:"'+a.join(",")+'" ');return b};g.isNotEmptyString=function(a,b){var c=a&&"string"===
typeof a;return c?b?c&&n.trim(a):!0:!1};g.isValidNumber=function(a){return"number"===typeof a&&!isNaN(a)};g.isObject=function(a){return a&&"object"===typeof a};g.getRandomString=function(){var a=Math.random().toString();return a=a.slice(2,a.length)};g._getDomainsByServerName=function(a){var b=a.split("."),c=b.length;return p.map(b,n.hitch(this,function(d,e){d=b.slice(e,c);var f="",h=d.length-1;p.forEach(d,n.hitch(this,function(k,l){f+=k;l!==h&&(f+=".")}));return f}))};g.removeCookie=function(a,b){var c=
this._getDomainsByServerName(window.location.hostname);p.forEach(c,n.hitch(this,function(d){H(a,null,{expires:-1,path:b});H(a,null,{expires:-1,path:b,domain:d});H(a,null,{expires:-1,path:b,domain:"."+d})}))};g.isLocaleChanged=function(a,b){return!a.startWith(b)};g.hashToObject=function(a){a=a.replace("#","");a=O.queryToObject(a);for(var b in a)if(a.hasOwnProperty(b))try{a[b]=B.parse(a[b])}catch(c){}return a};g.reCreateObject=function(a){function b(d){var e=[];d.forEach(function(f){Array.isArray(f)?
e.push(b(f)):"object"===typeof f?e.push(c(f)):e.push(f)});return e}function c(d){var e={},f;for(f in d)d.hasOwnProperty(f)&&(null===d[f]?e[f]=null:Array.isArray(d[f])?e[f]=b(d[f]):e[f]="object"===typeof d[f]?c(d[f]):d[f]);return e}return Array.isArray(a)?b(a):c(a)};g.setVerticalCenter=function(a){setTimeout(function(){var b=x(".jimu-vcenter-text",a),c,d;p.forEach(b,function(e){c=r.getContentBox(e).h;r.setStyle(e,{lineHeight:c+"px"})},this);b=x(".jimu-vcenter",a);p.forEach(b,function(e){c=r.getContentBox(e).h;
d=r.getContentBox(x(e).parent()[0]).h;r.setStyle(e,{marginTop:(d-c)/2+"px"})},this)},10)};g.merge=J;g.loadStyleLink=function(a,b,c){var d=new w,e=require(g.getRequireConfig()).toUrl(b);if(require.cache["url:"+e]){var f=require.cache["url:"+e];var h=e.split("/").pop();e=e.substr(0,e.length-h.length);f=T(f,e);a=c?r.create("style",{id:a,type:"text/css"},r.byId(c),"before"):r.create("style",{id:a,type:"text/css"},document.getElementsByTagName("head")[0]);a.styleSheet&&!a.sheet?a.styleSheet.cssText=f:
a.appendChild(r.toDom(f));d.resolve("load");return d}f=c?r.create("link",{id:a,rel:"stylesheet",type:"text/css",href:e},r.byId(c),"before"):r.create("link",{id:a,rel:"stylesheet",type:"text/css",href:e},document.getElementsByTagName("head")[0]);G(f,"load",function(){d.resolve("load")});var k=setInterval(function(){var l;if(p.some(document.styleSheets,function(m){if(m.href&&m.href.substr(m.href.indexOf(b),m.href.length)===b)return l=m,!0}))try{!d.isFulfilled()&&(l.cssRules&&l.cssRules.length||l.rules&&
l.rules.length)&&d.resolve("load"),clearInterval(k)}catch(m){}},50);return d};g.changeLocation=function(a){window.history.pushState&&window.history.pushState({path:a},"",a)};g.urlToObject=function(a){var b=null;-1===a.indexOf("#")?(b=y.urlToObject(a),b.hash=null):(a=a.split("#"),b=y.urlToObject(a[0]),b.hash=a[1]?-1<a[1].indexOf("\x3d")?O.queryToObject(a[1]):a[1]:null);return b};g.addManifestProperies=function(a){a.icon=a.url+"images/icon.png";"theme"===a.category?qa(a):("undefined"!==typeof a["2D"]&&
(a.support2D=a["2D"]),"undefined"!==typeof a["3D"]&&(a.support3D=a["3D"]),"undefined"===typeof a["2D"]&&"undefined"===typeof a["3D"]&&(a.support2D=!0),delete a["2D"],delete a["3D"],"undefined"===typeof a.properties&&(a.properties={}),S.processWidgetProperties(a))};g.getUniqueValues=function(a,b){var c=new w;a=a.replace(/\/*$/g,"")+"/generateRenderer";b=B.stringify({type:"uniqueValueDef",uniqueValueFields:[b]});I(a,{query:{classificationDef:b,f:"json"},responseType:"json",callbackParamName:"callback"}).then(n.hitch(this,
function(d){var e=d.data;d=[];(e=e&&e.uniqueValueInfos)&&0<e.length&&(d=p.map(e,n.hitch(this,function(f){return f.value})));c.resolve(d)}),n.hitch(this,function(d){c.reject(d)}));return c};g.combineRadioCheckBoxWithLabel=function(a,b){var c=!1;if(a&&1===a.nodeType&&"input"===a.tagName.toLowerCase()){var d=a.getAttribute("type")||"";d=d.toLowerCase();if("radio"===d||"checkbox"===d)c=!0}d=!1;b&&1===b.nodeType&&"label"===b.tagName.toLowerCase()&&(d=!0);c&&d&&(c=a.getAttribute("id"),c||(c="input_"+g.getRandomString(),
a.setAttribute("id",c)),b.setAttribute("for",c),r.setStyle(b,"cursor","pointer"))};g.convertExtentToPolygon=function(a){var b=a.xmin,c=a.xmax,d=a.ymin,e=a.ymax;return new R({rings:[[[b,e],[c,e],[c,d],[b,d],[b,e]]],spatialReference:a.toJson()})};g.combineGeometries=function(a){function b(t){var q={points:[],spatialReference:t[0].spatialReference.toJson()};p.forEach(t,function(u){q.points=q.points.concat(u.points)});return new la(q)}function c(t){var q={paths:[],spatialReference:t[0].spatialReference.toJson()};
p.forEach(t,function(u){q.paths=q.paths.concat(u.paths)});return new ma(q)}function d(t){var q={rings:[],spatialReference:t[0].spatialReference.toJson()};p.forEach(t,function(u){"polygon"===u.type?q.rings=q.rings.concat(u.rings):"extent"===u.type&&(u=g.convertExtentToPolygon(u),q.rings=q.rings.concat(u.rings))});return new R(q)}var e=null;if(a&&0<a.length)if(1===a.length)e=a[0];else{for(var f=null,h=null,k=null,l=null,m=0;m<a.length;m++){f=a[m];switch(f.type){case "point":case "multipoint":l="point";
break;case "polyline":l="polyline";break;case "polygon":case "extent":l="polygon";break;default:return null}if(0===m)k=l;else if(k!==l)return null;if(m!==a.length-1&&(h=a[m+1],!f.spatialReference.equals(h.spatialReference)))return null}"point"===l?e=b(a):"polyline"===l?e=c(a):"polygon"===l&&(e=d(a))}return e};g.isFeaturelayerUrlSupportQuery=function(a,b){var c=!1,d=/\/featureserver\//gi.test(a);a=/\/mapserver\//gi.test(a);b=(b||"").toLowerCase();d?c=0<=b.indexOf("query"):a&&(c=0<=b.indexOf("data"));
return c};g.isImageServiceSupportQuery=function(a){return 0<=(a||"").toLowerCase().indexOf("catalog")};g.isStringEndWith=function(a,b){return a.lastIndexOf(b)+b.length===a.length};g.processManifestLabel=function(a,b){var c=b.split("-")[0];a.label=a.i18nLabels&&(a.i18nLabels[b]||a.i18nLabels[c]||a.i18nLabels.defaultLabel)||a.label||a.name;a.layouts&&p.forEach(a.layouts,function(d){var e="i18nLabels_layout_"+d.name;d.label=a[e]&&(a[e][b]||a[e].defaultLabel)||d.label||d.name});a.styles&&p.forEach(a.styles,
function(d){var e="i18nLabels_style_"+d.name;d.label=a[e]&&(a[e][b]||a[e].defaultLabel)||d.label||d.name})};g.addManifest2WidgetJson=function(a,b){n.mixin(a,b.properties);a.name=b.name;a.label||(a.label=b.label);a.manifest=b};g.widgetJson=function(){var a={addManifest2WidgetJson:function(b,c){n.mixin(b,c.properties);b.name=c.name;b.label||(b.label=c.label);b.manifest=c;b.isRemote=c.isRemote;b.isRemote&&(b.itemId=c.itemId);c.featureActions&&(b.featureActions=c.featureActions);b.icon||(b.icon=c.icon);
b.thumbnail||(b.thumbnail=c.thumbnail);b.folderUrl=c.folderUrl;b.amdFolder=c.amdFolder},removeManifestFromWidgetJson:function(b){if(b.manifest){for(var c in b.manifest.properties)b[c]=void 0;b.name=void 0;b.label=void 0;b.featureActions=void 0;b.manifest=void 0}},getUriFromItem:function(b){return b.url?a.getFolderUrlFromItem(b)+"Widget":null},getFolderUrlFromItem:function(b){if(!b.url)return null;b=/manifest\.json$/.test(b.url)?b.url.substring(0,b.url.length-13):/\/$/.test(b.url)?b.url:b.url+"/";
"https:"===window.location.protocol&&(b=b.replace(/^http:\/\//,"https://"));return b}};return a}();g.addI18NLabel=function(a){var b=new w;if(a.i18nLabels)return b.resolve(a),b;a.i18nLabels={};if(a.properties&&!1===a.properties.hasLocale)return b.resolve(a),b;var c="widget"===a.category?"_widgetLabel":"_themeLabel";require(g.getRequireConfig(),["dojo/i18n!"+a.amdFolder+"nls/strings"],function(d){a.i18nLabels[dojoConfig.locale]=d[c];"theme"===a.category&&(a.layouts&&a.layouts.forEach(function(e){a["i18nLabels_layout_"+
e.name]={};a["i18nLabels_layout_"+e.name][dojoConfig.locale]=d["_layout_"+e.name]}),a.styles&&a.styles.forEach(function(e){a["i18nLabels_style_"+e.name]={};a["i18nLabels_style_"+e.name][dojoConfig.locale]=d["_style_"+e.name]}));b.resolve(a)});return b};g.localizeNumber=function(a,b){var c=(a.toString().split(".")[1]||"").length,d="";d=b&&isFinite(b.places)&&b.places;d=0<d||0<c?"#,###,###,##0.0"+Array.prototype.join.call({length:0<d?d+1:c},"0"):"#,###,###,##0";c={locale:F.locale,pattern:d};n.mixin(c,
b||{});try{return P.format(a,c)}catch(e){return console.error(e),a.toLocaleString()}};g.parseNumber=function(a,b){var c={locale:F.locale};n.mixin(c,b||{});try{return P.parse(a,c)}catch(d){return console.error(d),a}};g.localizeDate=function(a,b){var c={locale:F.locale,fullYear:!0};n.mixin(c,b||{});try{return fa.format(a,c)}catch(d){return console.error(d),"date"===c.selector?a.toLocaleDateString():"time"===c.selector?a.toLocaleTimeString():a.toLocaleString()}};g.localizeNumberByFieldInfo=function(a,
b){var c=null;c=n.exists("format.places",b)&&b.format.places;c=g.localizeNumber(a,{places:c});return n.exists("format.digitSeparator",b)&&!b.format.digitSeparator?c.toString().replace(new RegExp("\\"+ha.group,"g"),""):c};g.fieldFormatter={getFormattedUrl:function(a){if(a&&"string"===typeof a){var b=a.indexOf("http:");-1===b&&(b=a.indexOf("https:"));if(-1<b&&-1===a.indexOf("href\x3d")){var c=a.indexOf(" ",b);-1===c&&(c=a.length);var d=a.substring(b,c);a=a.substring(0,b)+'\x3cA href\x3d"'+d+'" target\x3d"_blank"\x3e'+
d+"\x3c/A\x3e"+a.substring(c,a.length)}}return a||""},getFormattedNumber:function(a,b){if("number"===typeof a){var c=(a.toString().split(".")[1]||"").length;a=g.localizeNumberByFieldInfo(a,{format:{places:b&&"number"===typeof b.places?parseInt(b.places,10):c,digitSeparator:b&&b.digitSeparator}});return'\x3cspan class\x3d"jimu-numeric-value"\x3e'+(a||"")+"\x3c/span\x3e"}return a},getFormattedDate:function(a){a&&(a=g.localizeDate(new Date(a),{fullYear:!0}));return a||""},getCodedValue:function(a,b){if(a&&
a.codedValues){for(var c=0,d=a.codedValues.length;c<d;c++){var e=a.codedValues[c];if(g.isDefined(b)&&n.exists("code",e)&&b.toString()===e.code.toString())return e.name}return b}return b||null},getTypeName:function(a,b){for(var c=b.length,d=0;d<c;d++)if(a===b[d].id)return b[d].name;return a}};g.addRelativePathInCss=T;g.url={isAbsolute:function(a){return a?a.startWith("http")||a.startWith("/"):!1},removeQueryParamFromUrl:function(a,b){a=y.urlToObject(a);a.query&&delete a.query[b];b=a.path;for(var c in a.query)b=
b===a.path?b+"?"+c+"\x3d"+a.query[c]:b+"\x26"+c+"\x3d"+a.query[c];return b},addQueryParamToUrl:function(a,b,c){a=y.urlToObject(a);a.query||(a.query={});a.query[b]=c;b=a.path;for(var d in a.query)b=b===a.path?b+"?"+d+"\x3d"+a.query[d]:b+"\x26"+d+"\x3d"+a.query[d];return b}};g.processUrlInWidgetConfig=function(a,b){if(a)return a.startWith("data:")||a.startWith("http")||a.startWith("/")?a:a.startWith("${appPath}")?a.replace("${appPath}",window.appInfo.appPath):b+a};g.processUrlInAppConfig=function(a){if(a)return a.startWith("data:")||
a.startWith("http")||a.startWith("/")?a:window.appInfo.appPath+a};g.getLocationUrlWithoutHashAndQueryParams=function(){var a=window.location,b=a.protocol+"//"+a.host+a.pathname;a=y.urlToObject(a.href);a.query&&a.query.apiurl&&(b=g.url.addQueryParamToUrl(b,"apiurl",a.query.apiurl));return b};g.getDefaultWebMapThumbnail=function(){return require.toUrl("jimu/images/webmap.png")};g.invertColor=function(a){a=a.substring(1);3===a.length&&(a=a.slice(0,1)+a.slice(0,1)+a.slice(1,1)+a.slice(1,1)+a.slice(2,
1)+a.slice(2,1));a=parseInt(a,16);return 7829367<a?"#000000":"#ffffff"};g.mixinAppConfigPosition=function(a,b){var c=n.clone(a);if(!b)return c;b=n.clone(b);var d=c.widgetOnScreen,e=b.widgetOnScreen;e&&e.widgets&&("[object Object]"===Object.prototype.toString.call(e.widgets)?p.forEach(d.widgets,function(f,h){h=f.uri?f.uri:"ph_"+h;e.widgets[h]&&e.widgets[h].position&&(e.widgets[h].position.relativeTo||(e.widgets[h].position.relativeTo="map"),f.position=e.widgets[h].position)},this):p.forEach(e.widgets,
function(f,h){f.position&&!f.position.relativeTo&&(f.position.relativeTo="map");d.widgets[h]&&f.position&&(d.widgets[h].position=f.position)}));e&&e.groups&&("[object Object]"===Object.prototype.toString.call(e.groups)?p.forEach(d.groups,function(f,h){h=f.label?f.label:"g_"+h;e.groups[h]&&e.groups[h].panel&&e.groups[h].panel.position&&(e.groups[h].panel.position.relativeTo||(e.groups[h].panel.position.relativeTo="map"),f.panel.position=e.groups[h].panel.position)},this):(a=a.layoutDefinition?a.layoutDefinition.manager:
"jimu/layoutManagers/AbsolutePositionLayoutManager","jimu/layoutManagers/AbsolutePositionLayoutManager"===a?p.forEach(e.groups,function(f,h){f.panel&&f.panel.position&&!f.panel.position.relativeTo&&(f.panel.position.relativeTo="map");d.groups[h]&&f.panel&&f.panel.position&&(d.groups[h].panel.position=f.panel.position)}):"jimu/layoutManagers/GridLayoutManager"===a&&(d.groups=V(d.groups,e.groups.map(function(f){return f.id})))));b.map&&b.map.position&&(c.map?c.map.position=b.map.position:c.map={position:b.map.position});
b.widgetPool&&b.widgetPool.panel&&(b.widgetPool.panel.position&&!b.widgetPool.panel.position.relativeTo&&(b.widgetPool.panel.position.relativeTo="map"),c.widgetPool.panel.position=b.widgetPool.panel.position);b.mobileLayout&&(c.mobileLayout=b.mobileLayout);return c};g.handleGridLayoutOnScreenGroupChange=V;g.template={groupIdentification:"groups\\[.+\\]",widgetIdentification:"widgets\\[.+\\]",getSearchRange:function(a,b,c){var d=-1;b=a.search(new RegExp(b));0<=b&&(a=a.slice(b,a.length),a=a.indexOf(c),
d=b+a+c.length);return{firstPos:b,lastPos:d}},setConfigValue:function(a,b,c){K(a,b,c)},getConfigValue:function(a,b){return K(a,b)},setConfigValueWithId:function(a,b,c){W(a,b,c)},getConfigValueWithId:function(a,b){return W(a,b)},getKeyInfo:function(a){var b=this.getWidgetIdByKey(a);if(null!==b)return{type:"widget",id:b};a=this.getGroupIdByKey(a);return null!==a?{type:"group",id:a}:{type:"unknow",id:null}},getWidgetIdByKey:function(a){var b=g.template.getSearchRange(a,g.template.widgetIdentification,
"]");if(-1===b.firstPos)a=null;else{var c=a.slice(b.firstPos,b.lastPos);a=a.slice(b.firstPos+c.indexOf("[")+1,b.lastPos-1)}return a},getGroupIdByKey:function(a){var b=g.template.getSearchRange(a,g.template.groupIdentification,"]");if(-1===b.firstPos)a=null;else{var c=a.slice(b.firstPos,b.lastPos);a=a.slice(b.firstPos+c.indexOf("[")+1,b.lastPos-1)}return a},getConfigedWidgetsByTemplateConfig:function(a){var b=[],c=g.template.widgetIdentification+"_config",d;p.forEach(a.configurationSettings,function(e){p.forEach(e.fields,
function(f){f.fieldName&&(d=g.template.getSearchRange(f.fieldName,c,"]"),0<=d.firstPos&&(f=g.template.getWidgetIdByKey(f.fieldName),-1===b.indexOf(f)&&b.push(f)))},this)},this);return b},mergeTemplateAppConfigToAppConfig:function(a,b,c){function d(k){var l=[];p.forEach(k,function(m){m&&l.push(m)},this);return l}var e=a.widgetOnScreen,f=a.portalUrl;b.values.webmap&&(a.map.itemId=b.values.webmap);c&&(a.map.mapOptions&&g.deleteMapOptions(a.map.mapOptions),a.map.portalUrl=f,b.values.app_title||(b.values.app_title=
c.title),b.values.app_subtitle||(b.values.app_subtitle=c.snippet));for(var h in b.values)"webmap"!==h&&g.template.setConfigValueWithId(a,h,b.values[h]);a.widgetPool.widgets=d(a.widgetPool.widgets);e.widgets=d(e.widgets);if(a.widgetPool.groups)for(b=0;b<a.widgetPool.groups.length;b++)a.widgetPool.groups[b].widgets=d(a.widgetPool.groups[b].widgets);if(e.groups)for(b=0;b<e.groups.length;b++)e.groups[b].widgets=d(e.groups[b].widgets);return a}};g.deleteMapOptions=function(a){a&&(delete a.extent,delete a.lods,
delete a.center,delete a.scale,delete a.zoom,delete a.maxScale,delete a.maxZoom,delete a.minScale,delete a.minZoom,delete a.initialState)};g.localeIsSame=function(a,b){return a.split("-")[0]===b.split("-")[0]};g.graphicsExtent=function(){return null};g.sanitizeHTML=function(a){return html_sanitize(a,function(b){return b},function(b){return b})};g.stripHTML=function(a){return a?-1<a.indexOf("\x3c")&&-1<a.indexOf("\x3e")?a.replace(/<(?:.|\s)*?>/g,""):a:a};g.removeSuffixSlashes=function(a){return a.replace(/\/*$/g,
"")};g.getBestDisplayAttributes=function(a,b){var c={},d=null,e;for(e in a)d=g.getBestDisplayValue(e,a,b),c[e]=d;return c};g.getBestDisplayValue=function(a,b,c){var d="",e=null;n.isArrayLike(c)?e=g.getFieldInfoByFieldName(c,a):"object"===typeof c&&c.name===a&&(e=c);e&&(d=b[a],"esriFieldTypeDate"===e.type?d&&(a=new Date(parseInt(d,10)),d=g._tryLocaleDate(a)):"number"===typeof d&&(e.domain&&"codedValue"===e.domain.type?p.some(e.domain.codedValues,function(f){if(f.code===d)return d=f.name,!0}):d=g._tryLocaleNumber(d)));
if(null===d||void 0===d)d="";return d};g._tryLocaleNumber=function(a){var b=g.localizeNumber(a);if(null===b||void 0===b)b=a;return b};g._tryLocaleDate=function(a){var b=g.localizeDate(a);b||(b=a.toLocaleDateString());return b};g.getFieldInfoByFieldName=function(a,b){var c=null;a&&0<a.length&&p.some(a,n.hitch(this,function(d){return d.name===b?(c=d,!0):!1}));return c};g.containsNonLatinCharacter=function(a){for(var b=0;b<a.length;b++)if(255<a.charCodeAt(b))return!0;return!1};g.isVersion4API=function(){return 0===
ia.version.indexOf("4")};g.getEsriConfig=function(){return v};g.getEsriConfigRequestObject=function(){var a=null;return a=g.isVersion4API()?v.request:v.defaults.io};g.setGlobalGeometryService=function(a){g.isVersion4API()?v.geometryServiceUrl=a:v.defaults.geometryServiceUrl=a;return a};g.getQueryableFeatureLayersFromMap=function(a){var b=[];a.layers&&(b=a.layers.filter(function(c){return"esri.layers.FeatureLayer"===c.declaredClass&&c.url&&c.supportedQueryFormats&&0<=c.supportedQueryFormats.toUpperCase().indexOf("JSON")}));
return b};g.has=function(a){var b=E(a);if(b)return b;if("ie"===a.toLowerCase()){a=0;var c=/MSIE (\d+\.\d+);/.test(navigator.userAgent),d=!!navigator.userAgent.match(/Trident\/7.0/),e=navigator.userAgent.indexOf("rv:11.0");c&&(a=Number(RegExp.$1));-1!==navigator.appVersion.indexOf("MSIE 10")&&(a=10);d&&-1!==e&&(a=11);return 11===a&&11||b}if("edge"===a.toLowerCase())return navigator.userAgent.split("Edge/")[1]||b};g.detectUserAgent=function(){var a={},b={},c=navigator.userAgent,d=navigator.platform,
e=c.match(/Web[kK]it[\/]{0,1}([\d.]+)/),f=c.match(/(Android);?[\s\/]+([\d.]+)?/),h=!!c.match(/\(Macintosh; Intel /),k=c.match(/(iPad).*OS\s([\d_]+)/),l=c.match(/(iPod)(.*OS\s([\d_]+))?/),m=!k&&c.match(/(iPhone\sOS)\s([\d_]+)/),t=c.match(/(webOS|hpwOS)[\s\/]([\d.]+)/);d=/Win\d{2}|Windows/.test(d);var q=c.match(/Windows Phone ([\d.]+)/),u=t&&c.match(/TouchPad/),Y=c.match(/Kindle\/([\d.]+)/),L=c.match(/Silk\/([\d._]+)/),M=c.match(/(BlackBerry).*Version\/([\d.]+)/),N=c.match(/(BB10).*Version\/([\d.]+)/),
Z=c.match(/(RIM\sTablet\sOS)\s([\d.]+)/),aa=c.match(/PlayBook/),A=c.match(/Chrome\/([\d.]+)/)||c.match(/CriOS\/([\d.]+)/),C=c.match(/Firefox\/([\d.]+)/),ba=c.match(/\((?:Mobile|Tablet); rv:([\d.]+)\).*Firefox\/[\d.]+/),D=c.match(/MSIE\s([\d.]+)/)||c.match(/Trident\/[\d](?=[^\?]+).*rv:([0-9.].)/),ca=!A&&c.match(/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/),da=ca||c.match(/Version\/([\d.]+)([^S](Safari)|[^M]*(Mobile)[^S]*(Safari))/);b.webkit=!!e;b.webkit&&(b.version=e[1]);f&&(a.android=!0,a.version=
f[2]);m&&!l&&(a.ios=a.iphone=!0,a.version=m[2].replace(/_/g,"."));k&&(a.ios=a.ipad=!0,a.version=k[2].replace(/_/g,"."));l&&(a.ios=a.ipod=!0,a.version=l[3]?l[3].replace(/_/g,"."):null);q&&(a.wp=!0,a.version=q[1]);t&&(a.webos=!0,a.version=t[2]);u&&(a.touchpad=!0);M&&(a.blackberry=!0,a.version=M[2]);N&&(a.bb10=!0,a.version=N[2]);Z&&(a.rimtabletos=!0,a.version=Z[2]);aa&&(b.playbook=!0);Y&&(a.kindle=!0,a.version=Y[1]);L&&(b.silk=!0,b.version=L[1]);!L&&a.android&&c.match(/Kindle Fire/)&&(b.silk=!0);A&&
(b.chrome=!0,b.version=A[1]);C&&(b.firefox=!0,b.version=C[1]);ba&&(a.firefoxos=!0,a.version=ba[1]);D&&(b.ie=!0,b.version=D[1]);da&&(h||a.ios||d)&&(b.safari=!0,a.ios||(b.version=da[1]));ca&&(b.webview=!0);a.tablet=!!(k||aa||f&&!c.match(/Mobile/)||C&&c.match(/Tablet/)||D&&!c.match(/Phone/)&&c.match(/Touch/));a.phone=!(a.tablet||a.ipod||!(f||m||t||M||N||A&&c.match(/Android/)||A&&c.match(/CriOS\/([\d.]+)/)||C&&c.match(/Mobile/)||D&&c.match(/Touch/)));return{os:a,browser:b}};g.isMobileUa=function(){var a=
g.detectUserAgent();return!0===a.os.phone||!0===a.os.tablet?!0:!1};g.isNeedHttpsButNot=function(){var a=navigator.geolocation,b=window.hasOwnProperty("isSecureContext");return(b&&window.isSecureContext||!b&&"https:"===window.location.protocol)&&a?!1:!0};g.isInConfigOrPreviewWindow=function(){var a=!1;try{a=!window.isBuilder&&window.parent&&window.parent!==window&&window.parent.isBuilder}catch(b){a=!1}return!!a};g.getAppHref=function(){var a="";return a=g.isInConfigOrPreviewWindow()?window.parent.location.href:
window.location.href};g.getAppIdFromUrl=function(){var a=!0,b=g.getAppHref();if(-1!==b.indexOf("id\x3d")||-1!==b.indexOf("appid\x3d")||-1!==b.indexOf("apps"))a=!1;if(!0===a)return b;a=this.urlToObject(window.location.href);if(a.query&&(a.query.id||a.query.appid))return a.query.id||a.query.appid;if(window.appInfo){if(window.appInfo.id)return window.appInfo.id;if(window.appInfo.appPath){if(a=window.appInfo.appPath.split("/"),a.length&&2<a.length)return a[a.length-2]}else console.error("CAN NOT getAppIdFromUrl")}};
g.getEditorContentHeight=function(a,b,c){var d=new w;this._content=a;this._dom=b;this._domParam=c;var e=setTimeout(n.hitch(this,function(){clearTimeout(e);e=null;var f=0,h=this._domParam.contentWidth;try{var k=document.createElement("div");k.setAttribute("id","fakeContent");r.setStyle(k,"background-size","contain");k.innerHTML=this._content;this._dom.appendChild(k);if(k){var l=x("img",k);if(l&&l.length)for(var m=0,t=l.length;m<t;m++)r.setStyle(l[m],"maxWidth",h-20+"px");r.setStyle(k,"position","absolute");
r.setStyle(k,"width",h+"px");r.setStyle(k,"left","-99999px");r.setStyle(k,"top","-99999px");r.setStyle(k,"visibility","hidden");var q=r.getContentBox(k);q.h&&(f=q.h,f+=this._domParam.contentMarginTop+this._domParam.footerHeight+8)}}catch(u){console.error("can't getEditorContentHeight"+u),f=200}d.resolve(f)}),1500);return d};g.getEditorTextColor=function(a,b){return{name:"dijit.editor.plugins.EditorTextColor",custom:{recordUID:g.getColorRecordName(a),forceAttr:b}}};g.getEditorBackgroundColor=function(a){return{name:"dijit.editor.plugins.EditorBackgroundColor",
custom:{recordUID:g.getColorRecordName(a)}}};g.getColorRecordName=function(a){return"wab_cr_"+(a||"")};g.isEsriDomain=function(a){return/^https?:\/\/(?:[\w\-_]+\.)+(?:esri|arcgis)\.com/.test(a)};g.b64toBlob=function(a,b,c){b=b||"";c=c||512;a=window.atob(a.replace(/^data:image\/(png|jpg|jpeg|gif);base64,/,""));for(var d=[],e=0;e<a.length;e+=c){for(var f=a.slice(e,e+c),h=Array(f.length),k=0;k<f.length;k++)h[k]=f.charCodeAt(k);f=new Uint8Array(h);d.push(f)}return new Blob(d,{type:b})};g.subtractionArray=
function(a,b){for(var c=a.length-1;0<=c;c--)for(var d=a[c],e=b.length-1;0<=e;e--)if(d===b[e]){a.splice(c,1);b.splice(e,1);break}return a};g.resourcesUrlToBlob=function(a){return I({url:a,handleAs:"blob"})};g.processItemResourceOfAppConfig=function(a,b){function c(l){var m=l.obj,t=l.key,q={obj:m,key:t};"number"===typeof l.i?(q.i=l.i,q.value=m[t][l.i]):q.value=m[t];return q}function d(l){for(var m in l)if("object"===typeof l[m])if(Array.isArray(l[m]))for(var t=l,q=m,u=0;u<t[q].length;u++)"string"===
typeof t[q][u]?e(t,q,u):"object"===typeof t[q][u]&&d(t[q][u]);else d(l[m]);else"string"===typeof l[m]&&e(l,m)}function e(l,m,t){"number"===typeof t?b.test(l[m][t])&&(k=b.func(c({obj:l,key:m,i:t})),"function"===typeof k.then?h.push(k):f.push(k)):b.test(l[m])&&(k=b.func(c({obj:l,key:m})),"function"===typeof k.then?h.push(k):f.push(k))}var f=[],h=[],k;d(a);return 0<h.length?ea(h).then(function(l){0<f.length&&(l=l.concat(f));return{appConfig:a,result:l}}):{appConfig:a,result:f}};g.isDefined=function(a){return void 0!==
a&&null!==a};g.getDefaultPopupInfo=function(a,b,c){var d=null;a&&a.fields&&(d={title:b,fieldInfos:[],description:null,showAttachments:!0,mediaInfos:[]},p.forEach(a.fields,function(e){var f=!1;c?p.some(c,n.hitch(this,function(h){return h&&e.name.toLowerCase()===h.toLowerCase()}))&&(f=!0):f=!0;f&&(f=this.getDefaultPortalFieldInfo(e),f.visible=!0,f.isEditable=e.editable,d.fieldInfos.push(f))},this));return d};g.getDefaultPortalFieldInfo=function(a){var b=a.name;b={fieldName:b,label:a.alias||b,tooltip:"",
visible:!1,format:null,stringFieldOption:"textbox"};switch(a.type){case "esriFieldTypeSmallInteger":case "esriFieldTypeInteger":b.format={places:0,digitSeparator:!0};break;case "esriFieldTypeSingle":case "esriFieldTypeDouble":b.format={places:2,digitSeparator:!0};break;case "esriFieldTypeDate":b.format={dateFormat:"longMonthDayYear"}}return b};g.getStyleColorInTheme=function(a){var b=new w;if(window&&window.isBuilder){var c="./stemapp3d/themes/";var d=window.appConfig}else c="./themes/",d=window.getAppConfig();
if(d&&d.theme.customStyles&&d.theme.customStyles.mainBackgroundColor)return b.resolve(d.theme.customStyles.mainBackgroundColor),b.promise;var e=d.theme.name,f=d.theme.styles[0];a&&(f=a);I(c+e+"/manifest.json",{responseType:"json"}).then(n.hitch(this,function(h){if(h&&h.data){h=h.data.styles;for(var k=0;k<h.length;k++){var l=h[k];l.name===f&&b.resolve(l.styleColor)}}}),n.hitch(this,function(h){console.error(h);b.reject(null)}));return b.promise};g.dynamicLinkXssFilter=function(a){return a.toLowerCase().trim().startsWith("javascript:")?
a.substring(11):a};return g});