// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/Deferred dojo/topic dojo/Evented dojo/on dojo/aspect dojo/json dojo/query dojo/request/xhr dojo/promise/all ./utils jimu/tokenUtils ./dijit/Message ./portalUrlUtils ./portalUtils".split(" "),function(D,f,p,q,l,m,E,F,t,A,G,x,u,k,B,y,C,H){var v=null,z=D(E,{constructor:function(){this.loaded=[];this.missedActions=[];this.activeWidget=null;this.widgetsUri={};window.isBuilder?(m.subscribe("app/sceneViewLoaded",f.hitch(this,
this._onSceneViewLoaded)),m.subscribe("app/sceneViewChanged",f.hitch(this,this._onSceneViewChanged))):(m.subscribe("sceneViewLoaded",f.hitch(this,this._onSceneViewLoaded)),m.subscribe("sceneViewChanged",f.hitch(this,this._onSceneViewChanged)));window.isBuilder?(m.subscribe("app/appConfigLoaded",f.hitch(this,this._onAppConfigLoaded)),m.subscribe("app/appConfigChanged",f.hitch(this,this._onAppConfigChanged))):(m.subscribe("appConfigLoaded",f.hitch(this,this._onAppConfigLoaded)),m.subscribe("appConfigChanged",
f.hitch(this,this._onAppConfigChanged)));m.subscribe("userSignIn",f.hitch(this,this._onUserSignIn));m.subscribe("userSignOut",f.hitch(this,this._onUserSignOut));m.subscribe("builder/actionTriggered",f.hitch(this,this._onActionTriggered));m.subscribe("/dnd/move/start",f.hitch(this,this._onMoveStart))},loadWidget:function(a){var b=new l,c;a=f.clone(a);a.folderUrl||k.processWidgetSetting(a);(c=this.getWidgetById(a.id))?b.resolve(c):this.getWidgetUri(a).then(f.hitch(this,function(d){a.uri=d;u([this.loadWidgetClass(a),
this.loadWidgetManifest(a)]).then(f.hitch(this,function(e){var h=e[0],g=e[1];this.loadWidgetResources(g).then(f.hitch(this,function(n){try{var r=this.createWidget(g,h,n);console.log("widget ["+g.uri+"] created.")}catch(w){console.log("create ["+g.uri+"] error:"+w.stack),new y({message:window.jimuNls.createWidgetError+": "+g.uri}),b.reject(w)}setTimeout(f.hitch(this,function(){b.resolve(r);this.emit("widget-created",r);m.publish("widgetCreated",r)}),50)}),function(n){b.reject(n)})}),function(e){b.reject(e)})}));
return b},loadWidgetClass:function(a){var b=new l;var c=a.isRemote?a.uri+".js":a.uri;require(k.getRequireConfig(),[c],f.hitch(this,function(d){b.resolve(d)}));k.checkError(a.uri,b);return b},loadWidgetResources:function(a){var b=new l,c=[];var d=f.clone(a);a=this.tryLoadWidgetConfig(d);var e=this._tryLoadResource(d,"i18n");var h=this._tryLoadResource(d,"style");d=this._tryLoadResource(d,"template");c.push(a);c.push(e);c.push(d);c.push(h);u(c).then(f.hitch(this,function(g){var n={};n.config=g[0];n.i18n=
g[1];n.template=g[2];n.style=g[3];b.resolve(n)}),function(g){b.reject(g)});return b},getWidgetUri:function(a){if(this.widgetsUri[a.id])return this.widgetsUri[a.id];var b=a.itemId?H.getPortal(window.portalUrl).getItemById(a.itemId).then(function(c){if(C.isOnline(window.portalUrl)){if(!C.isOnline(c.url)||"Web AppBuilder Widget"!==c.type)return(new l).reject("Not allow.",a.itemId)}else if("AppBuilder Extension"!==c.type)return(new l).reject("Not allow.",a.itemId);return k.widgetJson.getUriFromItem(c)}):
k.getUriInfo(a.uri).isRemote?(new l).reject("Not allow.",a.uri):(new l).resolve(a.uri);return this.widgetsUri[a.id]=b},loadWidgetManifest:function(a){var b=new l;return this.getWidgetUri(a).then(f.hitch(this,function(c){a.uri=c;if(a.manifest)return b.resolve(a),b;c=k.getUriInfo(c).folderUrl+"manifest.json";x(c,{handleAs:"json",headers:{"X-Requested-With":null}}).then(f.hitch(this,function(d){if(d.error&&d.error.code)return b.reject(d.error);d.amdFolder=a.amdFolder;d.category="widget";a.label?(this._processManifest(d),
k.addManifest2WidgetJson(a,d),b.resolve(a)):k.addI18NLabel(d).then(f.hitch(this,function(){this._processManifest(d);k.addManifest2WidgetJson(a,d);b.resolve(a)}))}),function(d){b.reject(d)});return b}))},getWidgetMarginBox:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return{};if(a._marginBox)return a._marginBox;a.setPosition({left:-9999,top:-9999,relativeTo:a.position.relativeTo});this.openWidget(a);a._marginBox=a.getMarginBox();this.closeWidget(a);return a._marginBox},_processManifest:function(a){k.addManifestProperies(a);
k.processManifestLabel(a,window.dojoConfig.locale)},createWidget:function(a,b,c){if(this.getWidgetById(a.id))return this.getWidgetById(a.id);c.config&&c.i18n&&(c.config=k.replacePlaceHolder(c.config,c.i18n));a.rawConfig=a.config;a.config=c.config||{};this.appConfig._appData&&this._mergeAgolConfig(a);a.nls=c.i18n||{};c.template&&(a.templateString=c.template);a["class"]="jimu-widget";a.label||(a.label=a.name);a.sceneView=this.sceneView;a.appConfig=this.appConfig;c={};for(var d in a)a.hasOwnProperty(d)&&
(c[d]=a[d]);c.widgetManager=this;a=new b(c);a.clazz=b;t.after(a,"startup",f.hitch(this,this._postWidgetStartup,a));t.before(a,"destroy",f.hitch(this,this._onDestroyWidget,a));F(a.domNode,"click",f.hitch(this,this._onClickWidget,a));this.loaded.push(a);return a},getAllWidgets:function(){return this.loaded},destroyAllWidgets:function(){var a=p.map(this.loaded,function(b){return b.id});p.forEach(a,function(b){this.destroyWidget(b)},this);this.loaded=[]},loadWidgetSettingPage:function(a){var b=new l;
a=f.clone(a);a.id+="_setting";u([this.loadWidgetSettingClass(a)]).then(f.hitch(this,function(c){var d=c[0];this.loadWidgetSettingPageResources(a).then(f.hitch(this,function(e){var h={nls:e.i18n,appConfig:this.appConfig,sceneView:this.sceneView,"class":"jimu-widget-setting"};null!==e.template&&(h.templateString=e.template);for(var g in a)a.hasOwnProperty(g)&&(h[g]=a[g]);try{var n=new d(h);t.before(n,"destroy",f.hitch(this,this._onDestroyWidgetSetting,n));b.resolve(n)}catch(r){new y({message:window.jimuNls.createWidgetSettingError+
":"+a.uri}),b.reject(r)}}),function(e){console.log(e)})}),function(c){b.reject(c)});return b},loadWidgetSettingClass:function(a){var b=new l;var c=a.isRemote?a.folderUrl+"setting/Setting.js":a.amdFolder+"setting/Setting";require(k.getRequireConfig(),[c],f.hitch(this,function(d){b.resolve(d)}));k.checkError(a.folderUrl+"setting/Setting.js",b);return b},loadWidgetSettingPageResources:function(a){var b=new l,c=[];a=f.clone(a);var d=this._tryLoadResource(a,"settingI18n");var e=this._tryLoadResource(a,
"settingTemplate");a=this._tryLoadResource(a,"settingStyle");c.push(d);c.push(e);c.push(a);u(c).then(f.hitch(this,function(h){var g={};g.i18n=h[0]||{};g.template=h[1];g.style=h[2];b.resolve(g)}),function(h){console.log(h)});return b},getWidgetById:function(a){var b;p.some(this.loaded,function(c){if(c.id===a)return b=c,!0},this);return b},getWidgetByLabel:function(a){var b;p.some(this.loaded,function(c){if(c.label===a)return b=c,!0},this);return b},getWidgetsByName:function(a){var b=[];p.some(this.loaded,
function(c){c.name===a&&b.push(c)},this);return b},changeWindowStateTo:function(a,b){"normal"===b?this.normalizeWidget(a):"minimized"===b?this.minimizeWidget(a):"maximized"===b?this.maximizeWidget(a):console.log("error state: "+b)},closeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;if("closed"!==a.state){this.activeWidget&&this.activeWidget.id===a.id&&(this.activeWidget.onDeActive(),this.activeWidget=null);q.setStyle(a.domNode,"display","none");a.setState("closed");
try{a.onClose()}catch(b){console.log(console.error("fail to close widget "+a.name+". "+b.stack))}}},openWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;if(!a.started)try{a.started=!0,a.startup()}catch(b){console.error("fail to startup widget "+a.name+". "+b.stack)}if("closed"===a.state){q.setStyle(a.domNode,"display","");a.setState("opened");try{a.onOpen()}catch(b){console.error("fail to open widget "+a.name+". "+b.stack)}}},activateWidget:function(a){if("string"===
typeof a&&(a=this.getWidgetById(a),!a))return;"opened"===a.state&&this._activeWidget(a)},maximizeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("maximized");try{a.onMaximize()}catch(b){console.log(console.error("fail to maximize widget "+a.name+". "+b.stack))}},minimizeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("minimized");
try{a.onMinimize()}catch(b){console.log(console.error("fail to minimize widget "+a.name+". "+b.stack))}},normalizeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;"closed"===a.state&&this.openWidget(a);a.setWindowState("normal");try{a.onNormalize()}catch(b){console.log(console.error("fail to normalize widget "+a.name+". "+b.stack))}},destroyWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;this._removeWidget(a);try{a.destroy()}catch(b){console.log(console.error("fail to destroy widget "+
a.name+". "+b.stack))}},tryLoadWidgetConfig:function(a){return this._tryLoadWidgetConfig(a).then(f.hitch(this,function(b){return this._upgradeWidgetConfig(a,b).then(function(c){return a.config=c})}))},triggerWidgetOpen:function(a){function b(h){var g=t.after(h,"onOpen",function(){g.remove();c.resolve(h)})}var c=new l,d=this.getWidgetById(a);if(d){if("closed"!==d.state)return c.resolve(d),c;b(d)}else var e=m.subscribe("widgetCreated",f.hitch(this,function(h){h.id===a&&(e.remove(),c.resolve(h))}));
m.publish("openWidget",a);return c},_tryLoadWidgetConfig:function(a){var b=new l;if(a.config&&f.isObject(a.config))return b.resolve(a.config),b;if(a.config){if(require.cache["url:"+a.config])return b.resolve(A.parse(require.cache["url:"+a.config])),b;b=k.processUrlInAppConfig(a.config);b=b.split("/");b[b.length-1]=encodeURIComponent(b[b.length-1]);b=b.join("/");return x(b,{handleAs:"json"})}return this._tryLoadResource(a,"config").then(function(c){a.isDefaultConfig=!0;return c})},_upgradeWidgetConfig:function(a,
b){var c=new l,d=a.manifest.version,e=a.version,h;if(d===e)return c.resolve(b),c;if(!1===a.hasVersionManager)return a.version=d,c.resolve(b),c;require(k.getRequireConfig(),[a.amdFolder+"VersionManager"],f.hitch(this,function(g){g=new g;var n=g.getVersionIndex(e),r=g.getVersionIndex(d);if(n>r)c.reject("Bad widget version number, "+a.name+","+e);else try{h=g.upgrade(b,e,d),a.version=d,c.resolve(h)}catch(w){console.log("Read widget ["+a.name+"] old config error,"+w.stack),c.resolve(b)}}));return c},
loadWidgetStyle:function(a){var b="widget/style/"+a.uri,c=new l;b=this._replaceId(b);return q.byId(b)?(c.resolve("load"),c):k.loadStyleLink(b,a.styleFile,"theme_"+this.appConfig.theme.name+"_style_common")},loadWidgetSettingStyle:function(a){var b="widget/style/"+a.uri+"/setting",c=new l;b=this._replaceId(b);return q.byId(b)?(c.resolve("load"),c):k.loadStyleLink(b,a.settingStyleFile)},loadWidgetConfig:function(a){a=require(k.getRequireConfig()).toUrl(a.configFile);if(require.cache["url:"+a]){var b=
new l;b.resolve(A.parse(require.cache["url:"+a]));return b}return x(a,{handleAs:"json"})},loadWidgetI18n:function(a){var b=new l;require(k.getRequireConfig(),["dojo/i18n!"+a.i18nFile],function(c){b.resolve(c)});return b},loadWidgetSettingI18n:function(a){var b=new l;require(k.getRequireConfig(),["dojo/i18n!"+a.settingI18nFile],function(c){b.resolve(c)});return b},loadWidgetTemplate:function(a){var b=new l;require(k.getRequireConfig(),["dojo/text!"+a.templateFile],function(c){b.resolve(c)});k.checkError(a.templateFile,
b);return b},loadWidgetSettingTemplate:function(a){var b=new l;require(k.getRequireConfig(),["dojo/text!"+a.settingTemplateFile],function(c){b.resolve(c)});k.checkError(a.settingTemplateFile,b);return b},removeWidgetStyle:function(a){q.destroy(this._replaceId("widget/style/"+a.uri))},removeWidgetSettingStyle:function(a){q.destroy(this._replaceId("widget/style/"+a.uri+"/setting"))},getControllerWidgets:function(){return p.filter(this.loaded,function(a){return a.isController})},getOffPanelWidgets:function(){return p.filter(this.loaded,
function(a){return!a.inPanel})},getOnScreenOffPanelWidgets:function(){return p.filter(this.loaded,function(a){return a.isOnScreen&&!a.inPanel})},closeOtherWidgetsInTheSameGroup:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),!a))return;for(var b=0;b<this.loaded.length;b++)this.loaded[b].gid===a.gid&&this.loaded[b].id!==a.id&&this.closeWidget(this.loaded[b])},closeAllWidgetsInGroup:function(a){for(var b=0;b<this.loaded.length;b++)this.loaded[b].gid===a&&this.closeWidget(this.loaded[b])},
_mergeAgolConfig:function(a){var b=this.appConfig._appData.values,c="widgets["+a.id+"]",d;for(d in b){var e=d.replace(/\//g,"_").indexOf(c+"_config");0<=e&&k.template.setConfigValue(a,d.replace(/\//g,"_").substr(e,d.length).replace(c,"widget"),b[d])}},_onUserSignIn:function(a){p.forEach(this.loaded,function(b){b.onSignIn(a)},this)},_onUserSignOut:function(){p.forEach(this.loaded,function(a){a.onSignOut()},this)},_activeWidget:function(a){if(this.activeWidget){if(this.activeWidget.id===a.id){!1===
this.activeWidget.inPanel&&this.activeWidget.moveTopOnActive&&q.setStyle(this.activeWidget.domNode,"zIndex",101);return}"active"===this.activeWidget.state&&(this.activeWidget.setState("opened"),!1===this.activeWidget.inPanel&&q.setStyle(a.domNode,"zIndex","zIndex"in a.position?a.position.zIndex:"auto"),this.activeWidget.onDeActive())}this.activeWidget=a;"opened"===this.activeWidget.state&&(this.activeWidget.setState("active"),!1===this.activeWidget.inPanel&&this.activeWidget.moveTopOnActive&&q.setStyle(this.activeWidget.domNode,
"zIndex",101),this.activeWidget.onActive(),m.publish("widgetActived",a))},_onClickWidget:function(a,b){var c=G(".jimu-widget",a.domNode);if(0<c.length)for(var d=0;d<c.length;d++)if(b.target===c[d]||q.isDescendant(b.target,c[d]))return;this._activeWidget(a)},_onMoveStart:function(a){p.forEach(this.loaded,function(b){b.domNode===a.node&&this._activeWidget(b)},this)},_onAppConfigLoaded:function(a){this.appConfig=a=f.clone(a);B.setPortalUrl(a.portalUrl)},_onSceneViewLoaded:function(a){this.sceneView=
a},_onSceneViewChanged:function(a){this.sceneView=a},_onAppConfigChanged:function(a,b,c,d){var e=f.clone(a);this.appConfig=e;p.forEach(this.loaded,function(h){h&&(h.onAppConfigChanged(e,b,c,d),"widgetChange"===b&&this._onConfigChanged(c.id,c.config,d))},this)},_onConfigChanged:function(a,b){if(a=this.getWidgetById(a))a.onConfigChanged(b),f.mixin(a.config,b)},_onActionTriggered:function(a){if("map"!==a.elementId&&"app"!==a.elementId){var b=this.getWidgetById(a.elementId);if(b)b.onAction(a.action,a.data);
else this.missedActions.push({id:a.elementId,action:{name:a.action,data:a.data}});p.forEach(this.getControllerWidgets(),function(c){if(c.widgetIsControlled(a.elementId))c.onAction(a.action,{widgetId:a.elementId,data:a.data})},this)}},_postWidgetStartup:function(a){a.started=!0;k.setVerticalCenter(a.domNode);t.after(a,"resize",f.hitch(this,k.setVerticalCenter,a.domNode));this.openWidget(a);var b=B.getPortalCredential(this.appConfig.portalUrl);if(b)a.onSignIn(b);else a.onSignOut();this._triggerMissedAction(a)},
_triggerMissedAction:function(a){this.missedActions.forEach(function(b){if(b.id===a.id)a.onAction(b.action.name,b.action.data)})},_remove:function(a){delete this.widgetsUri[a];return p.some(this.loaded,function(b,c){if(b.id===a)return this.loaded.splice(c,1),!0},this)},_tryLoadResource:function(a,b){var c=new l,d=function(){if("config"===b)var h=this.loadWidgetConfig(a);else if("style"===b)h=this.loadWidgetStyle(a);else if("i18n"===b)h=this.loadWidgetI18n(a);else if("template"===b)h=this.loadWidgetTemplate(a);
else if("settingTemplate"===b)h=this.loadWidgetSettingTemplate(a);else if("settingStyle"===b)h=this.loadWidgetSettingStyle(a);else if("settingI18n"===b)h=this.loadWidgetSettingI18n(a);else return c;h.then(function(g){c.resolve(g)},function(g){console.error("Load widget resource error. resource:",b);console.error(g);new y({message:window.jimuNls.loadWidgetResourceError+": "+a.uri});c.reject(g)})};if("config"===b){var e=a.amdFolder+"config.json";a.configFile=e;e="hasConfig"}else if("style"===b)e=a.amdFolder+
"css/style.css",a.styleFile=e,e="hasStyle";else if("i18n"===b)e=a.amdFolder+"nls/strings.js",a.i18nFile=a.isRemote?e:a.amdFolder+"nls/strings",e="hasLocale";else if("template"===b)e=a.amdFolder+"Widget.html",a.templateFile=e,e="hasUIFile";else if("settingTemplate"===b)e=a.amdFolder+"setting/Setting.html",a.settingTemplateFile=e,e="hasSettingUIFile";else if("settingI18n"===b)e=a.amdFolder+"setting/nls/strings.js",a.settingI18nFile=a.isRemote?e:a.amdFolder+"setting/nls/strings",e="hasSettingLocale";
else if("settingStyle"===b)e=a.amdFolder+"setting/css/style.css",a.settingStyleFile=e,e="hasSettingStyle";else return c;a[e]?d.apply(this):c.resolve(null);return c},_replaceId:function(a){return a.replace(/\//g,"_").replace(/\./g,"_")},_onDestroyWidget:function(a){"closed"!==a.state&&this.closeWidget(a);this._removeWidget(a);console.log("destroy widget ["+a.uri+"].")},_onDestroyWidgetSetting:function(a){this.removeWidgetSettingStyle(a)},_removeWidget:function(a){if("string"===typeof a&&(a=this.getWidgetById(a),
!a))return;this.activeWidget&&this.activeWidget.id===a.id&&(this.activeWidget=null);this._remove(a.id);0===this.getWidgetsByName(a.name).length&&this.removeWidgetStyle(a)}});z.getInstance=function(a){null===v&&(v=new z(a),window._widgetManager=v);return v};return z});