//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/declare esri/core/lang esri/views/3d/webgl-engine/lib/Util ../../webgl-engine-extensions/VertexBufferLayout ../../webgl-engine-extensions/GLVertexArrayObject ../../webgl-engine-extensions/GLXBO ../../support/fx3dUtils ../../support/fx3dUnits ../Effect ./PulseMaterial ../../webgl-engine-extensions/constraints".split(" "),function(q,w,x,G,y,z,A,t,n,u,B,C,D){var E=y.assert,v=D.VertexAttrConstants,F={circle:48,square:4,triangle:3,hexagon:6};return x([B],
{declaredClass:"esri.views.3d.effects.Pulse.PulseEffect",effectName:"Pulse",constructor:function(b){q.hitch(this,b);this.orderId=2;this._sizeInMeters=[]},_initRenderingInfo:function(){this.renderingInfo.radius=1E4;this.renderingInfo.solidColor=[255,255,20];this.renderingInfo.haloColors=[n.rgbNames.cadetblue,n.rgbNames.yellowgreen,n.rgbNames.lightpink,n.rgbNames.orangered,n.rgbNames.green,n.rgbNames.indianred];this._colorBarDirty=!0;this.renderingInfo.shapeType="circle";this._shapeDirty=this._vacDirty=
this._renderingInfoDirty=this._drawRing=!0;this.inherited(arguments)},_doRenderingInfoChange:function(b){this.inherited(arguments);for(var a in b)b.hasOwnProperty(a)&&this.renderingInfo.hasOwnProperty(a)&&(n.endsWith(a.toLowerCase(),"info")?n.isInforAttrChanged(this.renderingInfo[a],b[a])&&(this._renderingInfoDirty=!0):n.endsWith(a.toLowerCase(),"color")?b[a]instanceof Array&&3==b[a].length&&(this.renderingInfo[a]=[b[a][0]/255,b[a][1]/255,b[a][2]/255]):n.endsWith(a.toLowerCase(),"colors")?b[a]instanceof
Array&&(this.renderingInfo[a]=b[a],this._colorBarDirty=!0,this._renderingInfoDirty=!0):"shapetype"===a.toLowerCase()?this.renderingInfo[a]!=b[a].toLowerCase()&&(this._vacDirty=!0,this._shapeDirty=!0,this._isAddingGeometry=!1,this._renderingInfoDirty=!0,this.renderingInfo[a]=b[a].toLowerCase(),this._colourMapDirty=!0):"radius"===a.toLowerCase()||"transparency"===a.toLowerCase()?(this._clampScope(b,a),"radius"==a&&this._radiusUnit?this.renderingInfo[a]=u.toMeters(this._radiusUnit,b[a],this._view.viewingMode):
this.renderingInfo[a]=b[a]):typeof b[a]==typeof this.renderingInfo[a]&&(this.renderingInfo[a]=b[a]))},_updateDefaultLabelHeight:function(){this._layer._labelDefaultHeight=null},setContext:function(b){this.inherited(arguments);this._effectConfig&&q.isArray(this._effectConfig.renderingInfo)&&(this._radiusUnit=null,w.forEach(this._effectConfig.renderingInfo,function(a){"radius"===a.name.toLowerCase()&&(this._radiusUnit=a.unit,this.renderingInfo.radius=u.toMeters(this._radiusUnit,this.renderingInfo.radius,
this._view.viewingMode))}.bind(this)))},destroy:function(){this._resetXBOs();this._dispose("_vao")},_resetXBOs:function(){this._dispose("_vbo");this._dispose("_ibo")},_initVertexLayout:function(){this._vertexAttrConstants=[v.POSITION,v.AUXPOS1];this._vertexBufferLayout=new z(this._vertexAttrConstants,[3,3],[5126,5126])},_initRenderContext:function(){this.inherited(arguments);this._vacDirty&&(this._initVertexLayout(),this._resetXBOs(),this._vacDirty=!1,this._vao&&(this._vao.unbind(),this._vao._initialized=
!1));this._vbo||(this._vbo=new t(this._gl,!0,this._vertexBufferLayout));this._ibo||(this._ibo=new t(this._gl,!1));this._vaoExt&&(this._vao=new A(this._gl,this._vaoExt));var b=!1;switch(this.renderingInfo.shapeType){case "circle":case "triangle":case "square":case "hexagon":this._geometryVertexNum=4;this._geometryIndexNum=6;this._drawRing=!0;b=this._buildRingGeometries();break;case "wave":this._geometryVertexNum=3;this._geometryIndexNum=6;this._drawRing=!1;b=this._buildWaveGeometries();break;default:this._drawRing=
!1}return b},_getAltitude:function(b){return"number"==typeof b?40.11>b&&(b=40.11):b=40.11,b},_buildRingGeometries:function(){var b=this._isAddingGeometry?this._addedGraphics:this._allGraphics(),a=this._isAddingGeometry?this._toAddGraphicsIndex:0;if(0<b.length){var e,h,d,c,k=Math.max(3,F[this.renderingInfo.shapeType]),f=c=0,p=k*this._geometryVertexNum,m=this._vertexBufferLayout.getStride(),g=new Float32Array(b.length*m*p),l=new Uint32Array(b.length*k*this._geometryIndexNum),r=f=0;for(h=0;h<b.length;h++)if(e=
b[h],null!=e.geometry){for(d=0;d<p;d++)c=(h*p+d)*m,f=d%this._geometryVertexNum,g[0+c]=e.geometry.longitude,g[1+c]=e.geometry.latitude,g[2+c]=this._getAltitude(e.geometry.altitude),g[3+c]=h+a,g[4+c]=f,r=Math.floor(d/4),2!==f&&3!==f||(r+=1),g[5+c]=r/k;c=(h+a)*p;for(d=0;d<k;d++)f=(h*k+d)*this._geometryIndexNum,l[0+f]=0+c+d*this._geometryVertexNum,l[1+f]=2+c+d*this._geometryVertexNum,l[2+f]=1+c+d*this._geometryVertexNum,l[3+f]=0+c+d*this._geometryVertexNum,l[4+f]=3+c+d*this._geometryVertexNum,l[5+f]=
2+c+d*this._geometryVertexNum}return this._vbo.addData(this._isAddingGeometry,g),this._ibo.addData(this._isAddingGeometry,l),this._vao&&(this._vao._initialized=!1),this._resetAddGeometries(),!0}return!1},_buildWaveGeometries:function(){var b=this._isAddingGeometry?this._addedGraphics:this._allGraphics(),a=this._isAddingGeometry?this._toAddGraphicsIndex:0;if(0<b.length){this._waveSegments=32;var e,h,d,c,k=this._waveSegments;var f=k-1;var p=[],m=[];for(d=0;d<k;d++)for(h=0;h<k;h++)p.push([h,d]),d<k-
1&&h<k-1&&(c=d*k+h,e=(d+1)*k+h,m.push([c,e,c+1,c+1,e,e+1]));h=p.length;d=this._vertexBufferLayout.getStride();c=new Float32Array(b.length*d*h);f=f*f*this._geometryIndexNum;E(m.length*m[0].length===f);k=new Uint32Array(b.length*f);var g=0;for(f=g=0;f<b.length;f++){var l=b[f];for(e=0;e<h;e++)g=(f*h+e)*d,c[0+g]=l.geometry.longitude,c[1+g]=l.geometry.latitude,c[2+g]=this._getAltitude(l.geometry.altitude),c[3+g]=f+a,c[4+g]=p[e][0],c[5+g]=p[e][1];l=f*h+a;for(e=0;e<m.length;e++)g=(f*m.length+e)*this._geometryIndexNum,
k[0+g]=m[e][0]+l,k[1+g]=m[e][1]+l,k[2+g]=m[e][2]+l,k[3+g]=m[e][3]+l,k[4+g]=m[e][4]+l,k[5+g]=m[e][5]+l}return this._vbo.addData(this._isAddingGeometry,c),this._ibo.addData(this._isAddingGeometry,k),this._resetAddGeometries(),!0}return!1},_initColorBar:function(){if(!this._colorBarDirty)return!0;this._colorBarTexture||(this._colorBarTexture=this._gl.createTexture());var b=this._gl.getParameter(32873);this._gl.bindTexture(3553,this._colorBarTexture);this._gl.pixelStorei(37440,!0);this._gl.texParameteri(3553,
10240,9728);this._gl.texParameteri(3553,10241,9728);this._gl.texParameteri(3553,10242,33071);this._gl.texParameteri(3553,10243,33071);var a=n.createColorBarTexture(32,1,this.renderingInfo.haloColors);return this._gl.texImage2D(3553,0,6408,6408,5121,a),this._gl.generateMipmap(3553),this._gl.bindTexture(3553,b),0===this._gl.getError()},_loadShaders:function(){return this.inherited(arguments),this._material||(this._material=new C({pushState:this._pushState.bind(this),restoreState:this._restoreState.bind(this),
gl:this._gl,viewingMode:this._view.viewingMode,shaderSnippets:this._shaderSnippets})),this._material.loadShaders()},_localBinds:function(){this._vbo.bind(this._material._program);this._vertexBufferLayout.enableVertexAttribArrays(this._gl,this._material._program);this._ibo.bind()},_bindBuffer:function(){this._vao?(this._vao._initialized||this._vao.initialize(this._localBinds.bind(this)),this._vao.bind()):this._localBinds()},_unBindBuffer:function(){this._vao?this._vao.unbind():(this._vbo.unbind(),
this._vertexBufferLayout.disableVertexAttribArrays(this._gl,this._material._program),this._ibo.unbind())},render:function(b,a){this.inherited(arguments);this._layer.visible&&this.ready&&this._bindPramsReady()&&(this._hasSentReady||(this._layer.emit("fx3d-ready"),this._hasSentReady=!0),this._material.bind(q.mixin({},{pe:this._drawRing,el:this._waveSegments,ep:this._vizFieldVerTextures[this._vizFieldDefault],oe:this._vizFieldVerTextures[this._vizFields[this._currentVizPage]],mo:this._vizFieldVerTextureSize,
ss:this.renderingInfo.animationInterval,sp:[this._scopes.radius[0],this.renderingInfo.radius],ls:this.renderingInfo.transparency,ps:this._colorBarTexture,me:this._vizFieldMinMaxs[this._vizFieldDefault].min>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min?this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].min:this._vizFieldMinMaxs[this._vizFieldDefault].min,sl:this._vizFieldMinMaxs[this._vizFieldDefault].max>this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max?
this._vizFieldMinMaxs[this._vizFieldDefault].max:this._vizFieldMinMaxs[this._vizFields[this._currentVizPage]].max,ol:this.renderingInfo.solidColor},b),a),this._bindBuffer(),this._gl.drawElements(4,this._ibo.getNum(),5125,0),this._material.release(a),this._unBindBuffer())}})});