// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dojo/_base/lang dojo/_base/html dojo/on dojo/_base/Color dijit/TooltipDialog dijit/popup dojox/widget/ColorPicker jimu/utils".split(" "),function(l,m,n,g,c,h,e,p,k,q,r){return l([m,n],{baseClass:"jimu-color-picker",declaredClass:"jimu.dijit.ColorPicker",templateString:"\x3cdiv\x3e\x3c/div\x3e",_isTooltipDialogOpened:!1,color:null,showHex:!0,showHsv:!0,showRgb:!0,ensureMode:!1,showLabel:!1,postMixInProperties:function(){this.nls=window.jimuNls.common},
postCreate:function(){this.inherited(arguments);this.color?this.color instanceof e||(this.color=new e(this.color)):this.color=new e("#ccc");c.setStyle(this.domNode,"backgroundColor",this.color.toHex());this.showLabel&&this._changeLabel(this.color);this._createTooltipDialog(this.domNode);this._hideTooltipDialog()},destroy:function(){k.close(this.tooltipDialog);this.picker.destroy();this.tooltipDialog.destroy();this.inherited(arguments)},isPartOfPopup:function(a){var f=this.tooltipDialog.domNode;return a===
f||c.isDescendant(a,f)},hideTooltipDialog:function(){this._hideTooltipDialog()},_showTooltipDialog:function(){k.open({parent:this.getParent(),popup:this.tooltipDialog,around:this.domNode});this._isTooltipDialogOpened=!0},_hideTooltipDialog:function(){k.close(this.tooltipDialog);this._isTooltipDialogOpened=!1},_createTooltipDialog:function(){var a=c.create("div");this.tooltipDialog=new p({content:a});c.addClass(this.tooltipDialog.domNode,"jimu-color-picker-dialog");var f=new q({showHex:this.showHex,
showRgb:this.showRgb,showHsv:this.showHsv,value:this.color.toHex(),onChange:g.hitch(this,function(b){this.ensureMode||(b=new e(b),this.setColor(b))})});f.placeAt(a);f.startup();if(this.ensureMode){var d=c.create("div",{"class":"jimu-btn jimu-btn-vacation jimu-float-trailing",title:this.nls.cancel,innerHTML:this.nls.cancel},a);this.own(h(d,"click",g.hitch(this,function(){this._hideTooltipDialog()})));"undefined"===typeof this.showOk&&(d=c.create("div",{"class":"jimu-btn jimu-float-trailing ok",title:this.nls.ok,
innerHTML:this.nls.ok},a),this.own(h(d,"click",g.hitch(this,function(){var b=this.picker.get("value");this.setColor(new e(b));this._hideTooltipDialog()}))));a=c.create("div",{"class":"jimu-btn jimu-float-trailing",title:this.nls.apply,innerHTML:this.nls.apply},a);this.own(h(a,"click",g.hitch(this,function(){var b=this.picker.get("value");this.setColor(new e(b))})))}this.own(h(this.domNode,"click",g.hitch(this,function(b){b.stopPropagation();b.preventDefault();this._isTooltipDialogOpened?this._hideTooltipDialog():
this._showTooltipDialog()})));this.own(h(document.body,"click",g.hitch(this,function(b){this.isPartOfPopup(b.target||b.srcElement)||this._hideTooltipDialog()})));this.picker=f},setColor:function(a,f){if(a instanceof e){var d=this.color,b="";d&&(b=d.toHex());d=a.toHex();this.color=a;c.setStyle(this.domNode,"backgroundColor",d);if(b!==d&&(this.picker.set("value",d),!1!==f))this.onChange(new e(d))}},getColor:function(){return this.color},_changeLabel:function(a){c.empty(this.domNode);c.create("span",
{innerHTML:a.toHex(),className:"color-label",style:{color:r.invertColor(a.toHex())}},this.domNode)},onChange:function(a){this.showLabel&&this._changeLabel(a)},getPopup:function(){return this.tooltipDialog||null},setLabel:function(a){c.empty(this.domNode);c.create("span",{innerHTML:a||"",className:"text-label"},this.domNode)}})});